### ISSUE TITLE
C++ --> Python code giving "attemping to reference a deleted function errror

### ISSUE THREAD

**Issue by TechArtistG** [swig/swig#1793] opened 2020-05-20 06:33 UTC
Here's a cut down version of the class.  The error doesn't occur when trying to wrap the class, but when a method of another class tries to return an instance.

Class Def:

```
namespace nsA
{
    namespace nsB
    {

#define DISABLE_COPYING_AND_ASSIGNING(ClassName) ClassName(const ClassName&) = delete;   ClassName& operator=(const ClassName&) = delete         

            class myClass
            {
            public:
                DISABLE_COPYING_AND_ASSIGNING(myClass);

                myClass(myClass_t opaque);

                myClass(myClass&& other);

                ~myClass();

                uint32_t myMethod() const;                

            private:
                myClass_t mOpaque;                
            };

            enum class myEnum
            {
               A= 0,
               B= 1
            };
    }
}
```

Method that causes compile error:
```
myClass otherClass::getMyClass() const
{
    myClass_t inner = cfunctions_myClass(mOpaque, ThrowOnError{});
    return myClass(inner);
}
...
typedef struct myClass* myClass_t;
```

**Comment by ojwb** [comment] 2022-02-28 05:08
The example provided is not complete enough to actually use to reproduce this (and I'm very dubious about the `myClass_t` typedef - does `myClass` really have a member which typedef-ed pointer to its own type?  This looks like PIMPL idiom to me otherwise, which would make `myClass_t` a pointer to an implementation class corresponding to `myClass`) but the crux of this report looks to be that SWIG tries to use the copy constructor even though it's deleted, and we have #1044 for that already.

I'm going to close this as a duplicate but if you don't think this is completely covered by the existing ticket, please provide a complete small and self-contained reproducer to show what's missing and we can reopen this ticket.

**Closed by ojwb** 2022-02-28 05:08 UTC
