### ISSUE TITLE
Must %template precede use of the type?

### ISSUE THREAD

**Issue by dbankieris** [swig/swig#2898] opened 2024-04-30 17:42 UTC
Before e07957ad, the following code compiled.

```c++
%module test

%inline %{

template<typename T>
class Foo {
  public:
    T t;
    Foo() {}

  private:
    Foo& operator=(const Foo&) = delete;
};

%}

%inline %{

class Bar {
  public:
    Foo<int> foo;
};

%}

%template (Foo_int) Foo<int>;
```

After e07957ad, SWIG creates a setter for Bar::foo.

```bash
$ swig -c++ -python test.i
$ g++ `python3-config --includes` -fPIC -shared -o test.so test_wrap.cxx
test_wrap.cxx: In function ‘PyObject* _wrap_Bar_foo_set(PyObject*, PyObject*)’:
test_wrap.cxx:3520:28: error: use of deleted function ‘Foo<T>& Foo<T>::operator=(const Foo<T>&) [with T = int]’
 3520 |   if (arg1) (arg1)->foo = *arg2;
      |                            ^~~~
test_wrap.cxx:3318:10: note: declared here
 3318 |     Foo& operator=(const Foo&) = delete;
      |          ^~~~~~~~
```

Moving the `%template` directive to before the declaration of `Bar` solves the problem. Was this change in behavior intended? That is, is `%template` now required to precede use of the type?

**Comment by ojwb** [comment] 2024-05-24 00:16
> That is, is `%template` now required to precede use of the type?

I think it's not really a new requirement since the typemaps for the templated type need to be available when it is used, but SWIG seems a bit less forgiving than it was before that change.  This requirement doesn't seem to be clearly documented in the manual that I can see though.  @wsfulton e07957ad4c2e501e349d1c7eb8032f4c8a387f1f was committed by you - any thoughts?

(It's rather unhelpful that you currently have to put `%template` after the template is defined but before wrapping code that references to the templated type as those two points are often in the same header file, requiring adding SWIG-specific code to the header (or a copy of it).  https://sourceforge.net/p/swig/bugs/978/ in the old tracker is about that.)

**Comment by wsfulton** [comment] 2024-06-30 21:06
C++ compilers absolutely require full type information in the correct order to work correctly. SWIG is absolutely expected to work correctly when type information is provided in the correct order, like a C++ compiler. However, one of SWIG's goals is to try and generate working wrappers with missing type information. This is only done on best efforts as assumptions can only be made if the the appropriate type information is unavailable in the correct order. SWIG may produced sub-optimal wrapper or wrappers that do not compile if the type information is not correct as documented at https://swig.org/Doc4.2/SWIG.html#SWIG_nn46, but as ever, if the docs could be made clearer, then please submit a pull request to improve them.

For this particular issue, the type information can only be correctly determined after an appropriate explicit %template instantiation as SWIG requires a template instantiation in order to obtain the appropriate type information. https://swig.org/Doc4.2/SWIGPlus.html#SWIGPlus_template_directive does clearly state that %template needs to be placed before the template definition is parsed. Any usage of the template before the %template instantiation is a case of missing type information. Correctly determining assignability does requires the template instantiation of `Foo<int>` in order for SWIG to see that that assignment operator is not available when generating the wrappers for `Bar::foo`. The commit does state:
```
Template instantiation via %template is required in order for this to
work for templates that are not assignable.
```
so closing as expected behaviour.

**Closed by wsfulton** 2024-06-30 21:06 UTC
Labels: C++
