### ISSUE TITLE
C++11: the parser fails on SFINAE with `&&`

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2836] opened 2024-03-15 20:19 UTC
This leads to a syntax error on the `&&`:

```swig
%module sfinae_with_and;

%inline %{

struct C {
  template <typename T, typename std::enable_if<std::is_function<T>::value &&
                                                            !std::is_reference<T>::value,
                                                        int>::type = 0>
  void method();
};

%}
```

**Comment by ojwb** [comment] 2024-03-15 20:24
Duplicate of #2228.

**Closed by ojwb** 2024-03-15 20:24 UTC
