### ISSUE TITLE
error: reference to 'XXX' is ambiguous

### ISSUE THREAD

**Issue by magic0121** [swig/swig#2336] opened 2022-08-05 20:38 UTC
Hi

Apologies, I don't really know C++ or SWIG however have been tasked to wrap a complex C++ library using SWIG for Python. I have some test C++ code that uses the library that compiles fine so I know which header files I need, shared libs, tags etc. I first copied the header files from this test code to my interface file and ran swig and g++. swig worked fine (with a collection of warnings) however the first g++ errors I got were

`error: 'FP' was not declared in this scope ....
      note:   'H::D::FP`

There were a few of these so I added them the interface file as

%{
#include <header1.h>
#include <header2.h>
#include <header3.h>
.....
using namespace H::D;
using namespace A::M;

}

However the next error was

`error: reference to 'SID' is ambiguous`

As the class SID is in both the namespaces H::D and A::M. I tried using rename as 

`%rename(HD_SID)  H::D:SID;`

but that didn't seem to do anything. How do I resolve this 'ambiguous' issue?

Thanks and Regards

**Comment by ojwb** [comment] 2022-08-11 02:43
In #2289 :
> I had issues with %rename from https://github.com/swig/swig/issues/2336 , did I use it incorrectly?

There seems to be a stray `.` in your `%rename` which looks wrong.  If that's not the problem it's hard to say as you've not really provided enough detail.

I suspect from the snippets shown here (and the fact you commented on the other ticket) that this is essentially a duplicate of #2289.  If you don't agree it is, providing a small, self-contained example which demonstrates the problem would make it much more likely someone will investigate.

**Comment by magic0121** [comment] 2022-08-12 12:55
Apologies, I fixed the typo.  I will try and build a small, self-contained example, I initially had some issues around this but the issue seems to be around the %rename. You can generally %rename classes fine but it doesn't seem to be working in this case and the only thing I can see it could is be is the 

```
using namespace H::D;
using namespace A::M;
```

part. Is there anything else I can try? Should I use adding `using namespace` like this when I get  `was not declared in this scope`  issues?

Many thanks

**Comment by ojwb** [comment] 2022-09-28 21:07
> [...] the class SID is in both the namespaces H::D and A::M

@magic0121 I wonder if fa00622614d35716b429b12aa9dc1bde8e4b586d fixes your problem here - can you test with current git master?

**Comment by wsfulton** [comment] 2022-10-01 09:45
The `error: reference to ‘SID’ is ambiguous` is a C++ compiler error which can be seen putting this through g++:

```c++
//#include <header1.h>
//#include <header2.h>
//#include <header3.h>
namespace H {
  namespace D {
    struct SID {};
  }
}
namespace A {
  namespace M {
    struct SID {};
  }
}

using namespace H::D;
using namespace A::M;

void useSID(SID s) {}
//void useSID(H::D::SID s) {}
```
Use the uncommented line to fix your C++ problem. SWIG requires valid C++ to work. The corrected version will result in a SWIG error though:
`Error: 'SID' is multiply defined in the generated target language module.` This is due to the duplicate SID name in different namespaces discussed in #2289. You can fix htis using the %rename workaround by giving either or both SID instances a different name.

**Closed by wsfulton** 2022-10-01 09:45 UTC
