### ISSUE TITLE
Upgrade to Swig 4.2 C++ to C# assertion failed

### ISSUE THREAD

**Issue by lucatersi** [swig/swig#2755] opened 2024-01-12 16:11 UTC
I tryed to upgrade from  SWIG-4.1.1 to SWIG-4.2.0. Compiling my project from C++ to C# I get this assertion failed message:

Assertion failed: 0, file Swig/stype.c, line 461

It was working properly with previous version

Could you provide any hint to debug the issue?

**Comment by ojwb** [comment] 2024-01-13 02:30
> Could you provide any hint to debug the issue?

I'd suggest trying to reduce your source tree to a small self-contained reproducer.

If that seems too hard, you could use `git bisect` on the SWIG source tree to find what change made it start to fail.  There's less than 1000 commits so it should be <= 10 steps.  That might be enough to know what the problem is, but we might still need a way to reproduce the failure.

**Comment by wsfulton** [comment] 2024-01-14 08:17
Alternatively provide the preprocessed output from swig-4.1.1 here. Simply add `-E` to your swig options and redirect the output into a file and post here. When swig-4.2.0 is invoked with this file, it should also assert.

**Comment by wsfulton** [comment] 2024-01-17 19:34
@lucatersi were you able to follow any of these suggestions? We'd like to have details to reproduce asap before we make a new release.

**Comment by lucatersi** [comment] 2024-01-18 11:37
We decided to remain with SWIG 4.1 for the moment. I didn't try git bisect, but please find attached the compilation log with version 4.1.1 and 4.2 where I removed the part relative to my code which is huge.
I hope this is helpfull.

[4.1.txt](https://github.com/swig/swig/files/13976037/4.1.txt)
[4.2.txt](https://github.com/swig/swig/files/13976038/4.2.txt)

**Comment by wsfulton** [comment] 2024-01-18 20:11
These two files required manual hacking to tidy up. You need to redirect output simply to a file, like this:
```
swig -csharp -c++ libLaser3D.i > liblLaser3D-preprocessed.i
```
I tried to tidy up the file, but when I use `swig -csharp -c++` on it there was no segfault. You will need to check that SWIG still asserts before sending, so you would rerun on the preprocessed output like this:
```
swig -csharp -c++ libLaser3D.preprocesesed.i
```
to validate that it still asserts before sending us libLaser3D-preprocessed.i.

Don't remove the bit relevant to your code as that must be the bit that is asserting! If you can't send all the code, then you'll need to try the other suggestions, (cut down to a minimum that makes it seg fault, or git bisect). Or you could build and debug the swig source and send a stack trace. It'll be much easier to send us the full preprocessed output.

**Comment by ojwb** [comment] 2024-01-19 20:51
I've started a milestone for 4.2.1 and added this, though realistically it's not going to be fixed for 4.2.1 without a way to reproduce it or a backtrace or finding the commit which introduced the problem with git bisect.

**Comment by wsfulton** [comment] 2024-02-10 09:38
@lucatersi we do you need the preprocessed output in order to fix this. If you are unable to process it publicly, consider sending it to me privately.

**Comment by ojwb** [comment] 2024-02-14 23:12
I had a quick look at the failed assertion - it means we called `SwigType_default_deduce(t)` and `Len(SwigType_split(t))` was <= 0 - presumably it actually was zero.  If I follow `SwigType_split()`'s code that seems to mean that `t` must be an empty string (which isn't a valid `SwigType`).  There's only one caller of `SwigType_default_deduce()` and it seems this must mean we're ending up with an empty `type` attribute on some node in the parse tree.

I wondered if that was thanks to `NewSwigType()` being called with a type code it doesn't explicitly handle, since that results in it returning an empty string.  A look at possible culprits found me a bug I could reproduce to fix which I did in ceafa131def6bba843c32027c5f728ce2aa7e411, though that bug resulted in generating code that didn't compile with 4.1.1.  Maybe it was possible to trigger this bug with 4.1.1 while still generating code that compiled so @lucatersi if you can't supply a way to reproduce it'd be worthwhile testing with SWIG git master to see if it still happens.

**Comment by wsfulton** [comment] 2024-02-23 07:34
I've dropped this as something to fix for tomorrow's 4.2.1 release due to lack of information. If no more information is provided, we should close this ticket in the month or so.

**Comment by ojwb** [comment] 2024-02-23 20:04
FWIW, I concluded there weren't any other places where a `type` attribute could get set to an empty string, which would suggest my fix must have fixed the reporter's case too.  However there were a lot of places to check so I may have missed something.

**Comment by lucatersi** [comment] 2024-02-25 22:44
Sorry for the late update! Just wanted to confirm that v4.2.1 is all good now. Huge thanks to everyone who helped fix this. Really appreciate it!

**Comment by ojwb** [comment] 2024-02-25 22:51
Thanks for confirming.

**Closed by ojwb** 2024-02-25 22:51 UTC
