### ISSUE TITLE
Type needs to be declared before template of type

### ISSUE THREAD

**Issue by andershol** [swig/swig#2399] opened 2022-10-13 17:54 UTC
Given this code
```
%module TestModule
%include "std_vector.i"

%apply size_t { std::vector<MyDoubleStruct>::size_type };
%template(MyDoubleStructVector) std::vector<MyDoubleStruct>;

template<typename T> class MyStruct { T v; };
typedef MyStruct<double> MyDoubleStruct;
%template(MyDoubleStruct) MyStruct<double>;
```
In the swig 3.x this would compile to c# on windows with these commands (csc is the c# compiler):
```
> del *.cs *.cxx *.h *.dll
> swigwin-3.0.12\swig.exe -csharp -c++ -outfile test-3.0.12.cs -o test-3.0.12.cxx test.i
> csc /target:library test-3.0.12.cs
```
But it generates invalid c# in swig 4.x:
```
> swigwin-4.0.0\swig.exe -csharp -c++ -outfile test-4.0.0.cs -o test-4.0.0.cxx test.i
> csc /target:library test-4.0.0.cs
test-4.0.0.cs(77,14): error CS0029: Cannot implicitly convert type
        'SWIGTYPE_p_std__vectorT_MyDoubleStruct_t__value_type' to 'MyDoubleStruct'
```
Correct code is generated if the middle two lines are moved to the bottom. But e.g. when bisecting it would be nice if swig 4.x could handle the old code.

**Comment by ojwb** [comment] 2022-10-18 18:18
I think this probably changed as part of the resolution of #1051, which actually specified and enforced clear rules around `%template` and aligned it with how C++ templates themselves work.  The docs now say:

> The <tt>%template</tt> directive for a class template is the equivalent to an explicit instantiation of a C++ class template.

Your example is like this invalid C++ code:

```
#include <vector>

template class std::vector<MyDoubleStruct>;

template<typename T> class MyStruct { T v; };
typedef MyStruct<double> MyDoubleStruct;
```

Moving `template class std::vector<MyDoubleStruct>;` to the end is needed here, similarly to your SWIG example.

This indeed broke some user interface files which worked before, but having documented and logical rules going forward is much more helpful to everyone.  Interface files which follow the now documented requirements should work with older versions of SWIG too.

I can see your point about bisecting, but assuming #1051 was the cause this hasn't worked since 4.0.0 which was released 2019-04-27 so it's not worked for 3½ years now so you'll have to deal with it when bisecting anyway.

So sorry, but I think this is "wontfix".

**Closed by ojwb** 2022-10-18 18:18 UTC
