### ISSUE TITLE
Getting swig/python detected a memory leak of type 'BinaryOp *', no destructor found.

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2154] opened 2022-01-20 23:00 UTC
The following swig code:
```
%module(directors="1") tst1

%feature("director") BinaryOp;

%inline %{
class BinaryOp {
 public:
    virtual int handle(int a, int b) = 0;
    virtual ~BinaryOp() { std::cout << "A" << std::endl; }
};

int binary_op_wrapper(int a, int b, BinaryOp *handler) {
    return handler->handle(a, b);
}
%}
```
And a python program usetst1.py:
```
import tst1

# PythonBinaryOp class is defined and derived from C++ class BinaryOp
class PythonBinaryOp(tst1.BinaryOp):

    # Define Python class 'constructor'
    def __init__(self):
        # Call C++ base class constructor
        tst1.BinaryOp.__init__(self)

    # Override C++ method: virtual int handle(int a, int b) = 0;
    def handle(self, a, b):
        # Return the product
        return a * b

handler = PythonBinaryOp()
result = tst1.binary_op_wrapper(10, 20, handler)
print(result)
```
Compile with:
```
$ swig -python -py3 -c++ tst1.i
$ g++ -fPIC -g -shared -I /usr/include/python3.8 -o _tst1.so tst1_wrap.cxx
```
And run:
```
$ python3 usetst1.py
200
swig/python detected a memory leak of type 'BinaryOp *', no destructor found.
```
If I add 'del handler' to usetst1.py, the problem goes away.  But the automatic destructors should handle this.

I get exactly the same issue with end of git tree, running the tests that come with swig.  In the swig directory:
```
$ make
$ make check-examples PY3=y
$ cd Examples/python/callback/
$ $ python3 runme.py 
Adding and calling a normal C++ callback
----------------------------------------
Callback::run()
Callback::~Callback()

Adding and calling a Python callback
------------------------------------
PyCallback.run()
Callback::~Callback()

Adding and calling another Python callback
------------------------------------------
PyCallback.run()
Callback::~Callback()

python exit
swig/python detected a memory leak of type 'Caller *', no destructor found.
```
I also tried with version 4.0.1 that comes with Ubuntu 20.04.

**Comment by ojwb** [comment] 2022-01-21 04:49
84ff84f is since the last release, so I'm setting the 4.1.0 milestone on this as it would be good to resolve before it makes it into a release.  Clearly not a blocker, but we also have the option of reverting that commit for 4.1.0 and it would be better to make a conscious call rather than just ship this new bug by default.

**Comment by wsfulton** [comment] 2022-02-06 15:59
Hi @adr26, are you looking at this? Our test-suite is now full of these leak errors (for python 3, not python 2) and indeed this started with 84ff84f. I confess I missed this when reviewing the patch and would have asked for this to be resolved if I had spotted it. Given the additional leak messages we now see, alas, I intend to revert this for the 4.1.0 release until resolved.

**Comment by ojwb** [comment] 2022-02-06 19:53
> I intend to revert this for the 4.1.0 release until resolved.

FYI, `git revert` doesn't revert it cleanly (or else I'd probably have just reverted it for the time being as the warnings from the testsuite are annoying as they obscure whether the testsuite ran cleanly or not).

**Comment by wsfulton** [comment] 2022-02-07 20:43
No worries, I'll figure out the revert if there is no fix forthcoming from @adr26.

**Comment by adr26** [comment] 2022-02-07 20:49
Hi @wsfulton, @ojwb,

I'm sorry I've not been able to look at this yet. The codebase I use SWIG with has brought up a Py3 port, but continues to be used with Py2 in production and we hadn't seen this regression.

I don't know how long you can hold off, but I will try and look at this soon and prepare a fix.

Thanks, Andrew R

**Comment by adr26** [comment] 2022-02-12 17:26
@cminyard &mdash; I've flipped PR#2208 to be ready for review, having completed some internal testing on my fix.

As well as internal testing, I checked the fix against your minimal example. If you have the scope to check my fix resolves the problem that originally caused you to report it, I'd be glad of any feedback prior to the PR being reviewed/merged.

Thanks, Andrew R

**Comment by cminyard** [comment] 2022-02-13 00:46
I tested and it seems to solve the problem.  I haven't seen it in a while, for my tests I have to delete all the objects so the end code can make sure all the GC cleans everything up.  But if I defeat that mechanism, with main end of tree I see this message, with your end of tree I don't.  Thanks for fixing this.

**Comment by adr26** [comment] 2022-02-13 07:33
Thank you for checking @cminyard &mdash; I'm glad it resolves the issue you originally hit.

Andrew R

**Comment by cminyard** [comment] 2022-03-06 12:37
I guess I should close this.  Thanks again for fixing it.

**Comment by adr26** [comment] 2022-03-06 13:12
@cminyard &mdash I'd suggest we leave this issue open until #2208 is merged, since it's still pending CR and hasn't been merged to master yet.

Thanks, Andrew

**Comment by cminyard** [comment] 2022-03-06 13:21
Sorry, reopening.

**Comment by ojwb** [comment] 2022-03-06 17:19
There's really not much point having two tickets open for the same problem - it just clogs up the issue list.  It seems poorly thought out that you don't just open a PR as part of an existing issue really.

**Closed by ojwb** 2022-03-06 17:19 UTC
Labels: Python, regression
