### ISSUE TITLE
Files read by %insert aren't reported as dependencies

### ISSUE THREAD

**Issue by vdanjean** [swig/swig#2036] opened 2021-06-09 08:03 UTC
Hi,
When using %pythoncode with a filename in a swig file, it seems there is no ways to get back this information into the generated dependency file (whereas the python file is searched through the "-I" options, so its real path is not necessarily clear)
Example:
```
vdanjean@eyak:~/tmp/swig$ cat test.i 
%module "test"
%include "test.h"

%pythoncode "test-base.py"
vdanjean@eyak:~/tmp/swig$ cat test.h
extern int test;
vdanjean@eyak:~/tmp/swig$ cat test-base.py 
def foo():
	pass
vdanjean@eyak:~/tmp/swig$ swig -MMD -MF deps.mk -python test.i 
vdanjean@eyak:~/tmp/swig$ cat deps.mk 
test_wrap.c: \
  test.i \
  test.h 
```
It would be useful to either:
1) add the dependency to the generated one (even if the C file do not really depends on the python file)
2) or add a dependency line for the `test.py` generated file (that would depend on the test.i file and the included python files)

As a side note, it would also be very convenient if you add a '-MP' option (such as gcc/clang) to add a phony target for each dependency other than the main file, causing each to depend on nothing (see gcc doc for example https://gcc.gnu.org/onlinedocs/cpp/Invocation.html#Invocation )

**Comment by wsfulton** [comment] 2021-06-20 15:30
`%pythoncode` is actually using the `%insert` directive. If `%insert` is inserting a 

SWIG does actually support `-MP`.

**Comment by wsfulton** [comment] 2021-06-20 15:34
`%pythoncode` is actually using the `%insert` directive. If `%insert` is inserting a file contents rather than a simple string, then yes, it makes sense to add it into the list of dependent files. However, `%insert` reads in the file contents after the preprocessing stage and it would then make sense to change `%insert` to read in the file contents during the preprocessing stage instead. That's quite a change, but should be given consideration.

SWIG does actually support -MP.

**Comment by ojwb** [comment] 2024-09-06 03:06
Duplicate of #1902.

**Closed by ojwb** 2024-09-06 03:06 UTC
Labels: preprocessor
