### ISSUE TITLE
BUG: Directors in python when function has an argument named `result`

### ISSUE THREAD

**Issue by erezinman** [swig/swig#2571] opened 2023-05-05 22:57 UTC
Consider the following example:

_./file.h_:
```c++
class ResultHandler
{
public:
    virtual ~ResultHandler() = default;
    virtual void error(const int& result) = 0;
};
```
_./file.cpp_:
```c++
#include "file.h"
```
_./swig.i_:
```
%module(directors="1") swig
%feature("director") ResultHandler;                   // Causes errors
%{
    #include "file.h"
%}

%include "file.h"
```

_./build.sh_:
```bash
current_dir=$(dirname "$0")
cd "$current_dir"

mkdir -p build
echo "$current_dir/build"
swig -c++ -python -outdir build -o build/swig.cxx -v swig.i
g++ -O2 -fPIC -c file.cpp -o build/file.o
g++ -O2 -fPIC -c build/swig.cxx -I/usr/include/python3.9 -o build/swig.o -I $current_dir
g++ -shared build/file.o build/swig.o -o build/final.so
```

Leads to an error:
> build/swig.cxx:3726:26: error: declaration of ‘swig::SwigVar_PyObject result’ shadows a parameter
>  3726 |   swig::SwigVar_PyObject result = PyObject_CallMethodObjArgs(swig_

**Comment by ojwb** [comment] 2023-05-06 01:40
See #1077

**Comment by ojwb** [comment] 2023-05-23 20:33
Closing as a duplicate of #1077.

**Closed by ojwb** 2023-05-23 20:33 UTC
