### ISSUE TITLE
swig/python detected a memory leak, no destructor found (reopen #2072)

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#2080] opened 2021-09-22 22:54 UTC
Hi,

I was recompiling my c++ code with the latest version of swig, and now my python code give some warning message :

swig/python detected a memory leak of type 'ThreadCallback *', no destructor found.
swig/python detected a memory leak of type 'Callback *', no destructor found.
swig/python detected a memory leak of type 'Timer *', no destructor found.

Here a small test where I am able to have the issue, if you have a swig object member of a class it seems you need to call del on the python object to remove the warning about the memory leak.

Any suggestion about what I am doing wrong ?

```
class MyClassNoLeak:
 """Test print no leak message."""
     def __init__(self) -> None:
         elt = core.MySwigElt()
         elt.dump()
         
 class MyClassLeak:
 """Test print leak message."""
     def __init__(self) -> None:
        self.elt = core.MySwigElt()
        self.elt.dump()
       
 myclassnoleak = MyClassNoLeak()
 myclassleak = MyClassLeak()
 # Explicitely call del -  the class remove the warning
 del myclassleak
 ```

**Comment by ferdnyc** [comment] 2021-09-25 17:27
This is mostly covered in the SWIG documentation, see in particular [§ 6.6.1 – 6.6.3 on constructor wrapping](http://www.swig.org/Doc4.0/SWIGDocumentation.html#SWIGPlus_nn7) and [§ 14.2 on `%newobject`](http://www.swig.org/Doc4.0/SWIGDocumentation.html#Customization_ownership).

You're seeing issues leaking pointers to objects, which I assume are member variables of the `MySwigElt()` class? And probably point to non-wrapped classes? If the constructor for `MySwigElt()` is allocating that memory, then it's memory the Python bindings have no control over and can't manage.

> if you have a swig object member of a class it seems you need to call del on the python object to remove the warning about the memory leak.

Well, the issue isn't so much that it's a member of a Python class, it's that _something_ has to delete that (wrapped) object at some point.

In `MyClassNoLeak`, the `elt` wrapper instance is unreferenced the moment it reaches the end of `__init__`, and it'll then be garbage-collected. So, it's being deleted _implicitly_ by the interpreter. But because in `MyClassNoLeak`, you've stored the return from `MySwigElt()` as an instance variable, **that** instance is still "live" in the interpreter.

You don't necessarily have to delete the class _holding_ the wrapped class — it's not where the problem lives. The leak is happening in the (C++-originated) object that `elt` wraps. You could just `del myclassleak.elt` directly, to plug the leak — the rest of `myclassleak` is fine. The point is to get rid of the wrapped class referencing memory that SWIG doesn't know how to manage.

(Or, alternately, you can teach SWIG to teach Python how to manage `MySwigElt` instances, by adding wrapper code. See the documentation sections I referenced.)

**Comment by slbuilder** [comment] 2021-09-28 17:10
Hi @ferdnyc,

So I tried following your comment to figure out but unfortunately I was not lucky so far, the only way I was able to really solve the trouble by calling manually the __swig_destroy__

I checked and the destructor of my C++ destructor is called when calling this method. I created a utility function to do that in my code, but will try to make a real full example as soon I have time.

```
@staticmethod
    def swig_destructor(swig_obj: any) -> None:
        """Force the destruction of a swig object."""
        if swig_obj:
            swig_obj.__swig_destroy__(swig_obj)
```

**Comment by wolfviking0** [comment] 2021-09-28 17:12
Hi @ferdnyc,

So I tried following your comment to figure out but unfortunately I was not lucky so far, the only way I was able to really solve the trouble by calling manually the __swig_destroy__

I checked and the destructor of my C++ destructor is called when calling this method. I created a utility function to do that in my code, but will try to make a real full example as soon I have time.

```
    @staticmethod
    def swig_destructor(swig_obj: any) -> None:
        """Force the destruction of a swig object."""
        if swig_obj:
            swig_obj.__swig_destroy__(swig_obj)
```

**Comment by ferdnyc** [comment] 2021-09-28 17:43
@wolfviking0 It would help to post your C++ class definitions. Where are you holding pointers to `Timer` or `ThreadCallback`? How are those allocated.

Actually, though, this isn't really the appropriate venue for this discussion. It would be better to take this to stackoverflow or a similar site — the problem you're having is not an issue with SWIG.

**Comment by ojwb** [comment] 2021-12-29 05:54
Not an issue with SWIG so closing.

**Closed by ojwb** 2021-12-29 05:54 UTC
