### ISSUE TITLE
std/boost_shared_ptr.i for Go

### ISSUE THREAD

**Issue by proteneer** [swig/swig#514] opened 2015-09-03 12:32 UTC
I'm opening this issue in hopes of getting some help to wrap std/boost_shared_ptr for Go. So far the code for python/boost_shared_ptr is pretty opaque looking so far. If anyone has tips please let me know.

One immediate thing I noticed is that there is no SWIG_ConvertPtrAndOwn equivalent for Go.

**Comment by ojwb** [comment] 2022-04-05 22:09
Closing as duplicate of #2030.

**Closed by ojwb** 2022-04-05 22:09 UTC
Labels: enhancement, Go
