### ISSUE TITLE
Provide support for C++ standard integer types

### ISSUE THREAD

**Issue by mwpowellhtx** [swig/swig#1137] opened 2017-10-27 16:40 UTC
Such as are exposed by [``#include <cstdint>``](http://en.cppreference.com/w/cpp/types/integer).

For example, when I use ``int32_t`` or ``uint32_t`` throughout my code, SWIG fails to see the definition and instead assumes marshaling machinations, when the underlying type is expected.

For instance, in *C#* that would be ``int`` or ``uint``, respectively. Or even ``global::System.Int32`` or ``global::System.UInt32``, if you really preferred that. However, I would accept the first.

Possibly requiring end user to provide include paths. Having to provide include path would be a small price to pay for that.

At least some recommendations how to shim that support in, if you please.

**Comment by wsfulton** [comment] 2017-11-02 19:50
Duplicate of #973.

**Closed by wsfulton** 2017-11-02 19:50 UTC
