### ISSUE TITLE
Don't discard null return value in function with output parameters

### ISSUE THREAD

**Issue by vadz** [swig/swig#2905] opened 2024-05-13 13:18 UTC
Consider the following example:

```cpp
%module outparam

%include <std_string.i>

%{
#include <string>
%}

%apply std::string* OUTPUT { std::string* out };

%inline {
std::string hi = "Hello ";

std::string* TestOutput(bool ok, std::string* out) {
  *out = "world";
  return ok ? &hi : nullptr;
}
}
```

and Python code to test it:

```python
import outparam

print(type(outparam.TestOutput(True)), type(outparam.TestOutput(False)))
```

I'd expect this to output

```
<class 'list'> <class 'list'>
```

but it actually outputs

```
<class 'list'> <class 'str'>
```

because `SWIG_Python_AppendOutput()` [replaces null values](https://github.com/swig/swig/blob/b6f7460fda0c754aacefc822759c1d356da9d159/Lib/python/pyrun.swg#L123-L125) instead of appending to them and so when the function returns `nullptr` its output parameter is returned directly, as a string, instead of returning a list.

This is pretty annoying as it means you can't use natural

```python
first, second = outparam.TestOutput(whatever)
```

in Python as this gives a run-time error if the function happens to return null for some value of `whatever`.

This behaviour dates from a very long time ago, see 6e77a6ba2 (fixes for swigrun example, 2005-12-07), but I don't think this was done intentionally or makes sense even if it was, and would like to fix this, but please let me know if you think it is and the current behaviour is actually expected.

**Comment by vadz** [comment] 2024-05-13 14:39
Hmm, the behaviour is the same (and still wrong IMO) for Ruby too:

```ruby
#!/usr/bin/env ruby
require './outparam';

puts Outparam.TestOutput(true).class, Outparam.TestOutput(false).class
```

outputs

```
Array
String
```

**Comment by vadz** [comment] 2024-05-13 16:40
OTOH JS behaves correctly:

```js
#!/usr/bin/env node

let outparam = require('outparam');

console.log(outparam.TestOutput(true));
console.log(outparam.TestOutput(false));
```

outputs 2 2-element arrays.

**Comment by ojwb** [comment] 2024-05-13 20:55
There's a similar (maybe fundamentally the same) issue in SWIG/PHP:

https://github.com/swig/swig/issues/2027#issuecomment-999988949

It was a while ago, but ISTR the problem is essentially that `NULL` gets used as an initial placeholder for "no OUTPUT values accumulated yet", so can't be told apart from an actual `NULL` value.

**Comment by vadz** [comment] 2024-05-13 22:19
Thanks, this is indeed the same problem. I'm not sure of the best way to fix it yet, but it seems weird to me that both `Lib/typemaps/inoutlist.swg` and `Lib/typemaps/cstrings.swg` use `%append_output` as the latter shouldn't need to append to anything.

Using a different macro, e.g. some `%append_output_without_discarding_null`, in the former would solve the problem, if we default it to `%append_output` for the languages not defining it explicitly, but I wonder if we could just change `cstrings.swg` to use `%set_output` instead. I'll try to experiment with this soon.

**Comment by ojwb** [comment] 2024-05-13 22:47
> Thanks, this is indeed the same problem. I'm not sure of the best way to fix it yet, but it seems weird to me that both `Lib/typemaps/inoutlist.swg` and `Lib/typemaps/cstrings.swg` use `%append_output` as the latter shouldn't need to append to anything.

You might reasonably use the macros from `cstrings.swg` on a parameter of a function which has another parameter to which you've applied an `OUTPUT` typemap and/or has an actual return value.

**Comment by vadz** [comment] 2024-05-14 15:01
Yes, you're right, of course, sorry for somehow not thinking about this. This means that my proposed solution still wouldn't work for a function like `std::string* TestOutput(bool ok, char* out)` (with the appropriate cstring typemap for `out`) returning `nullptr`.

The real fix would need to distinguish between `Py_None` assigned to `resultobj` by default and the same `Py_None` returned from `SWIG_Python_NewPointerObj()` if the pointer is null. The problem is that this would require a lot of changes because we'd need to record this in a local variable (probably not too difficult, but would be redundant in many cases but I'm not sure how to avoid using it unless it's really needed) and pass it to `SWIG_AppendOutput()`, which would require modifying all languages using UTL. Not sure if it's really worth it just for a probably relatively rare case of C functions returning (possibly null) objects...

**Comment by wsfulton** [comment] 2024-06-15 22:23
Still needs fixing for scripting languages supporting argout. f3d46986d34d3abb14ed1268b1d0996dca3e2bb2...d9401905f2316aa95376a6128f1e31f8cd5acc1f from #2907 contains the fix for Python, but still needs extending for Ruby, PHP etc. @vadz, perhaps you could add in this and create testcases? If not, I'll get to it later.

**Comment by vadz** [comment] 2024-06-15 22:51
I can do Ruby but I'm completely unfamiliar with PHP, so I'd rather leave this one to someone else.

**Comment by ojwb** [comment] 2024-06-16 19:33
I can probably do PHP.  I actually looked at this before for PHP but couldn't see an easy fix and concluded it was a low priority corner case as Python had essentially the same problem (https://github.com/swig/swig/issues/2027#issuecomment-999988949) but if `$isvoid` solves that problem it should be fairly simple to fix.

**Comment by ojwb** [comment] 2024-06-16 21:10
@wsfulton I looked at sorting this out for PHP but noticed your fix seems to mishandle the case where the first parameter outputs Python `None` - here's a reproducer:

```
diff --git a/Examples/test-suite/inout.i b/Examples/test-suite/inout.i
index 26425edc..7baddbb2 100644
--- a/Examples/test-suite/inout.i
+++ b/Examples/test-suite/inout.i
@@ -36,6 +36,15 @@
     a += 1;
   } 
 
+  inline void VoidOutOK(double* b, char* p) {
+    (void)p;
+    if (b) *b += 1;
+  }
+
+  inline void VoidOutBad(char* p, double* b) {
+    (void)p;
+    if (b) *b += 1;
+  }
 %}
 
 %template() std::pair<double, double>;
@@ -46,6 +55,8 @@ void AddOne1p(std::pair<double, double>* INOUT);
 void AddOne2p(std::pair<double, double>* INOUT, double* INOUT);
 void AddOne3p(double* INOUT, std::pair<double, double>* INOUT, double* INOUT);
 void AddOne1r(double& INOUT);
+void VoidOutOK(double* INOUT, char* INOUT);
+void VoidOutBad(char* INOUT, double* INOUT);
 
 %inline %{
   inline void StringNot(char** INOUT) {
diff --git a/Examples/test-suite/python/inout_runme.py b/Examples/test-suite/python/inout_runme.py
index d1f2f5ff..15b1a4b0 100644
--- a/Examples/test-suite/python/inout_runme.py
+++ b/Examples/test-suite/python/inout_runme.py
@@ -20,6 +20,15 @@ a = inout.AddOne3p(1, (1, 1), 1)
 if a != [2, (2, 2), 2]:
     raise RuntimeError
 
+a = inout.VoidOutOK(1, None)
+if a != [2, None]:
+    raise RuntimeError
+
+a = inout.VoidOutBad(None, 1)
+if a != [None, 2]:
+    print(str(a))
+    raise RuntimeError
+
 ret, out = inout.NonVoidOut(-42)
 if ret is not None:
     raise RuntimeError
```

I'd expect `[None, 2]` for `inout.VoidOutBad(None, 1)` (but we actually discard the `None`), especially since we return `[2, None]` if the arguments are swapped as in `inout.VoidOutOK(1, None)`.

It seems `$isvoid` is not enough - we also need to check if this is the first `INOUT` or `OUTPUT` parameter we're processing, or something like that.

FWIW, I tested this with cd39cf132c96a0887be07c826b80804d7677a701 and it seems @vadz approach also mishandles this case in the same way (as does SWIG 4.2.1, tested with the Debian package).

**Comment by ojwb** [comment] 2024-06-17 05:46
Having though about this more, I'm thinking even more strongly that we need to return `[None, 2]` for `inout.VoidOutBad(None, 1)` - otherwise a more realistic example which only sometimes returns `NULL` results in a variable length array which can't be assigned to a tuple of variables in the pythonic way:

```
p, b = inout.VoidOutBad(None, 1)
```

**Comment by vadz** [comment] 2024-06-17 18:59
I can fix this with something like this:

```diff
commit cbc03c3f062ee4fcf6f46e8edf7c9f4f62e2870f
Author: Vadim Zeitlin <vz-swig@zeitlins.org>
Date:   2024-06-17 20:51:23 +0200

    Python: Fix handling multiple "out" parameters in void functions
    
    The previous fix didn't work correctly for the void functions with more
    than one output parameter if "None" was returned for any but the last
    one of them.
    
    Fix this by only taking "isvoid" flag into account for the first output
    parameter, but not any others.
    
    See #2905.

diff --git a/Lib/python/pyrun.swg b/Lib/python/pyrun.swg
index efe02e41f..9740e758c 100644
--- a/Lib/python/pyrun.swg
+++ b/Lib/python/pyrun.swg
@@ -117,10 +117,11 @@ SWIG_Python_SetConstant(PyObject *d, const char *name, PyObject *obj) {
 /* Append a value to the result obj */
 
 SWIGINTERN PyObject*
-SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
+SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int* is_void) {
   if (!result) {
     result = obj;
-  } else if (result == Py_None && is_void) {
+  } else if (result == Py_None && *is_void) {
+    *is_void = 0;
     SWIG_Py_DECREF(result);
     result = obj;
   } else {
diff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
index 00c38173c..ad4320474 100644
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -2769,6 +2769,11 @@ public:
 
     Wrapper_add_local(f, "resultobj", "PyObject *resultobj = 0");
 
+    String *isvoid_decl = NewString("");
+    Printf(isvoid_decl, "int isvoid = %d", Cmp(returntype, "void") ? 0 : 1);
+    Wrapper_add_local(f, "isvoid", isvoid_decl);
+    Delete(isvoid_decl);
+
     // Emit all of the local variables for holding arguments.
     emit_parameter_variables(l, f);
 
@@ -3238,9 +3243,7 @@ public:
 
     /* Substitute the cleanup code */
     Replaceall(f->code, "$cleanup", cleanup);
-
-    bool isvoid = !Cmp(returntype, "void");
-    Replaceall(f->code, "$isvoid", isvoid ? "1" : "0");
+    Replaceall(f->code, "$isvoid", "&isvoid");
 
     /* Substitute the function name */
     Replaceall(f->code, "$symname", iname);
```

but this breaks the new `typemap_isvoid.cpptest` as `$isvoid` is not replaced with 0 or 1 any longer.

I thought about resetting `isvoid` variable to 0 in the function being wrapped instead of doing it in `SWIG_Python_AppendOutput()`, but this seems much harder to do and still requires using a variable instead of hard-coded 0 and 1, so the test would still have to be changed.

@wsfulton Can I adjust the test or do you see some other way to do it?

**Comment by ojwb** [comment] 2024-06-18 22:21
If we go that route, I think the `isvoid` name should be changed (and possibly `$isvoid` left in as a feature by itself if it looks more widely useful).

I'm going to hold off actually implementing for PHP until we've agreed a solution to this `NULL`-handling issue, in case it significantly changes the mechanism.

Incidentally, while looking at this for PHP I noticed the `%append_output()` macro which seems like a slightly more generic solution (there's code to define `%append_output()` if it's not already defined, which defines it in terms of `SWIG_AppendOutput()`, which is itself defined in terms of `SWIG_Python_AppendOutput()`, etc).  The `%append_output()` interface looks more workable for PHP where there's a standard pre-defined variable for the return value.  Mentioning this here in case it helps for other target languages that need changes for this.

**Comment by ojwb** [comment] 2024-09-12 21:55
Unassigning myself as I can't really usefully do the PHP part until we've agreed a solution to the `NULL`-handling issue.

@wsfulton I think it would be good for you to take a quick look at this before 4.3.0 - `$isvoid` hasn't been in a release yet, and if we're likely to change how it works (or if we're likely to replace it with something else and remove it because we don't see wider uses for it) then it'd be helpful to add a note to the current docs for it to warn it's not a stable interface.

We could also add such a note for 4.3.0 just in case.

**Comment by wsfulton** [comment] 2024-10-02 22:54
I've been giving this quite a bit of thought but it is not as obvious as suggested above. I've been reading around to try figure out what the original intention is for these typemaps as it isn't clear to me.

Let's consider INPUT, OUTPUT and INOUT and None as input:

* The INPUT typemaps are clearly stated as providing pass by value semantics instead of by pointer/reference types, from the code:
https://github.com/swig/swig/blob/e587e2be0dacc014b85d4ac256ce918fb14e7f4a/Lib/typemaps/typemaps.swg#L15-L17

None is arguably not valid for pass by value and should error in the same way as if passing None to a function that takes by value. However, it doesn't work like this and None is accepted as a valid input for INPUT* and INOUT* but seg faults for INPUT& and INOUT&.

* The OUTPUT typemaps do not take an input as they support output only, so passing None as input is impossible.

* INOUT is a combination of INPUT and OUTPUT typemaps, from the code:
https://github.com/swig/swig/blob/e587e2be0dacc014b85d4ac256ce918fb14e7f4a/Lib/typemaps/typemaps.swg#L101-L104
So passing by value semantics again.
An interpretation of the docs is that INOUT does not consider None as a valid input, it talks about there being an "_input and an output value_":
https://github.com/swig/swig/blob/e587e2be0dacc014b85d4ac256ce918fb14e7f4a/Doc/Manual/Arguments.html#L322-L323
Quite how these should be combined and what is a valid input is not clear and what needs clearly defining.
However, the implementation is clearly a combination of the 'in' INPUT typemap and the 'argout' OUTPUT typemap as the pattern is:
```swig
%typemap(in) Type *INOUT = Type *INPUT;
%typemap(argout) Type *INOUT = Type *OUTPUT;
```


Summarising above, handling None is not clearly defined, but the pointers ('scuse pun) are that the family of typemaps provide pass by value semantics and by inference None (that's pointer semantics, not value semantics) is not a valid input. In reality, this isn't enforced though. If there are some other clues leading to a different summary, please point them out.

While I think that summary is unbiased from what is documented, we all know that many of the earlier SWIG contributions were not documented so it is hard to really know. My own impression, and I emphasise it was just an impression, was None is a valid input, but the normal expected behaviour for None passed to the INOUT typemaps was to simply not append a value. In other words quite the opposite expectation that @ojwb mentioned. My assumption was that arguments not requested would not be returned, so this would actually be the correct code as only one argument should be returned:
```python
b = inout.VoidOutBad(None, 1)
```
and not
```python
p, b = inout.VoidOutBad(None, 1)
```

Arguably either approach is correct, but the one I was expecting is possibly more user friendly dealing with functions with lots of INOUT argument parameters (not that I would advocate such API designs), such as:

`x, y = inout.LotsOfArgs(None, 1, None, None, None, None, 1, None, None)`

The patch below implements this behaviour:
```patch
diff --git a/Lib/python/pyrun.swg b/Lib/python/pyrun.swg
index 1aa72bea0..c88ccf9e4 100644
--- a/Lib/python/pyrun.swg
+++ b/Lib/python/pyrun.swg
@@ -124,6 +124,8 @@ SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
     SWIG_Py_DECREF(result);
     result = obj;
   } else {
+    /* Don't append if NULL is passed as an input parameter to the wrapped function */
+    if (obj != Py_None) {
       if (!PyList_Check(result)) {
         PyObject *o2 = result;
         result = PyList_New(1);
@@ -137,6 +139,7 @@ SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
       PyList_Append(result,obj);
       SWIG_Py_DECREF(obj);
     }
+  }
   return result;
 }
``` 

Choose a solution:

1. Don't attempt to return None where no output is requested. Patch above is clean and just requires some documentation to define behaviour clearly about None as input.
2. This is a bug that no user has reported as a problem, don't attempt to fix it in swig-4.3, kick the can down the road. Wait for someone to report it who has a strong feeling on what an ideal solution would be. As @ojwb points out `$isvoid` doesn't change the behaviour for None as an input since 4.2.1 as this inconsistency has always been there. 
3. Define the inconsistent behaviour and decide to do nothing more - low risk won't break anyone's code. Suggest in the docs for users to add a 'check' typemap to throw an exception if None is passed in to prevent the inconsistent behaviour. So users can decide on behaviour.
4. Return fixed size lists as per @vadz proposal. Personally, I think this is too much of a quirky oddity for my liking by building a relationship between different types and typemaps as the proposal stands. Passing of data between typemaps is avoided even between typemaps for the same argument (never mind different arguments and different types), see [Passing data between typemaps](https://swig.org/Doc4.2/Typemaps.html#Typemaps_nn47) written by the original typemap architect.
5. Return fixed size lists so return None if None is an input. This will require going against the original typemap design intentions and finding some sort of inter-typemap communication mechanism as a refinement and generic solution to what @vadz proposed. Too late to do this for swig-4.3, I've thought about this though, I have some ideas, but don't have anything I think is good enough to propose yet and can't be coded up quickly.
6. The typemaps are documented as implementing `pass by value` and using None is not passing by value, so enforce this, make a change to prevent None as input by throwing an exception if None is passed in.

1,4,5 and 6 could break someone's code somewhere. 3 won't break code ever. 2 won't break code for the time being (in swig-4.3).

* From the analysis of what is documented, that is, None is not a valid input, 2, 3 or 6 would be the solution.
* From an easy to implement point of view with no fundamental rethink of typemaps, 1 would be a good solution.
* Defining None as an acceptable input which results in a fixed size return list would be a longer term solution if there is a body of opinion that thinks this is important and high priority, so then choose 5.

I'm just about leaning towards 1 on balance as it defines a consistent behaviour with probably hopefully minimal impact, but to be honest I think this is a low priority issue and so hope others can chime in to make a quick decision as I want to get the release out and focus on other things asap. If you have a strong opinion or don't really mind, please say either way.

**Comment by ojwb** [comment] 2024-10-03 19:01
> Outlawing it entirely (6) at least is a clear behaviour that doesn't lay traps for the unwary, but means you can't use it to wrap the C API pattern where you pass a pointer to where to put a returned value, but that pointer can be `NULL` when you don't want the value to save the caller needing to create a dummy variable (and potentially allowing the function to do less work)

Having thought about it more, this seems a more appealing option for the case where the pointer being passed in is `NULL`.  It's simple for us to implement and simple for the user to understand.  The user can wrap such a function in other ways - e.g. ignore the parameter, or `%ignore` and `%extend` to add a thin wrapper around the method to provide an adjusted API to wrap.

However there's also the case of an `OUTPUT` typemap which actually returns a pointer type (so it takes a pointer to pointer or reference to pointer) - e.g.:

```
void foo(Foo*& a, Foo*& b);
```

Here you can't pass in `NULL` for `a` or `b` themselves (because they're references) but after

```
Foo dummy;
Foo* a = &dummy;
Foo* b = &dummy;
foo(a, b);
```

`a` and/or `b` could have been set to `NULL` by the call to `foo()`.  With PHP's `t_output_helper` that leads to quirky behaviour where the returned value/array sometimes has a PHP `Null` for such values and sometimes it's swallowed, depending on the order of arguments added to the output array and which set to `NULL` by the function:

```
%fragment("t_output_helper","header") %{
static void
t_output_helper(zval *target, zval *o) {    
  zval tmp;
  if (Z_TYPE_P(target) == IS_ARRAY) {
    /* it's already an array, just append */
    add_next_index_zval(target, o);
    return;
  }
  if (Z_TYPE_P(target) == IS_NULL) {
    /* NULL isn't refcounted */
    ZVAL_COPY_VALUE(target, o);
    return;
  }
  ZVAL_DUP(&tmp, target);
  array_init(target);
  add_next_index_zval(target, &tmp);
  add_next_index_zval(target, o);
}
%}
```

The return value starts as a PHP `NULL` if the function being wrapped returns `void`, then the first `OUTPUT` value replaces that `NULL` with the returned value, and the second turns the return value into a PHP `array` containing the first and second values, then third and subsequent append to the array.  The problem is that if the first `OUTPUT` value is a PHP `NULL` things go wrong when the second output value is processed, because the return value is PHP `NULL` and it looks like it's actually the first value, so it just replaces rather than creating the array.

The equivalent helper for Python is `SWIG_Python_AppendOutput()` which has a similar problem (it's just Python `None` instead of PHP `NULL`), and it seems likely other target language implementations will too.

`$isvoid` addresses the case where the function doesn't have a `void` return (the PHP helper just doesn't yet make use of it yet as I was holding off until we resolved how we were going to fix this).  To fix this for the `void` return case it seems either:

* we need to know when this is the second value being appended (and we need to create an array), or
* we need to use a different initial placeholder return value which can be distinguished from any value being appended (and either only do that when there are OUTPUT parameters or fix it up before returning when there aren't), or
* we need to turn the return value into an array if it isn't already in the helper (and either turn a single element array back into a single value before returning, or know how many OUTPUT parameters there are going to be and only turn into an array if there's more than one).

`git grep` suggests we ship `SWIGTYPE** OUTPUT` typemaps for at least guile, lua and PHP (and `SWIGTYPE *& OUTPUT` for C#).  There's also a more extensive collection of `** OUTPUT` typemaps for guile in `Lib/guile/pointer-in-out.i`, and `char **OUTPUT` in `Lib/guile/typemaps.i`.

The PHP `void **OUTPUT` and `void *&OUTPUT` seem to actually be for PHP's pass-by-reference feature though, so aren't relevant here.  It's unhelpful they have the same name, but also unhelpful to change it now.

Looks like the C# one is similar (it aims to support `f(out x)` in C# it seems.

However the guile ones definitely seem to be appending return values, and I think the Lua one is too.

Also users can write their own `Foo** OUTPUT` typemaps using our `t_output_helper()`/equivalent helper function.

**Comment by vadz** [comment] 2024-10-03 21:51
FWIW I definitely agree with Olly that (1) is very unhelpful, the signature of the function really, really shouldn't depend on the values of its arguments.

Also, at least for Python, I'd be perfectly fine with forbidding `INOUT` typemaps entirely (I don't see how can they be used in a nice way) and, a fortiori, with forbidding passing `None` for them, i.e. (6).

And IMHO (2) would be quite acceptable too, but I agree again that we should clearly document that `$isvoid` is an experimental/internal feature that shouldn't be relied on, as it will probably need to be changed if we ever return to this later.

**Comment by wsfulton** [comment] 2024-10-03 22:04
> Pointers are rather a C/C++ way to think

Yes, that's my interpretation given the INPUT typemap is for wrapping a C pointer and wrapping C is SWIG's primary function. The snippet I showed:
https://github.com/swig/swig/blob/e587e2be0dacc014b85d4ac256ce918fb14e7f4a/Lib/typemaps/typemaps.swg#L15-L17
is quite clearly talking in terms of C as it uses the C term 'pointers' and in the same sentence as using 'value', so is a stretch to interpret this in terms of something other than C's notion of 'passing by value'. Python None is solidly mapped to a C NULL and I really do not see how None can be interpreted as being a valid primitive value in C.

The original authors are, first and foremost, mapping input and output value semantics onto pointer/reference semantics, I just don't think they properly considered the impossible mapping of a NULL pointer to a valid value.

> That's perhaps tolerable for the case where the None is literally written in the call. The problematic cases are when you pass in a value which might or might not be None ...

I fully agree with this, but would suggest that hard coding None is the more common approach and passing in None instead of a value is a programming error, which rightfully should error out. It just doesn't make sense to me to accept None as an output for these typemaps, even more so when None is ambiguous, meaning  a 'missing value' or a valid value for pointers being wrapped 'by value' as in the case of pointers to pointers or references to pointers.

I always understood these typemaps were for primitive types. I also considered revisiting my long held understanding for these typemaps and did the same search as you. I might be wrong, but there is a case for the original intention being for primitive types as per the initial Python docs I could find for these typemaps:
https://github.com/swig/swig/blob/12a43edc2df8853e8e0315f742e57be88f0c4269/Doc/Manual/Python.html#L2333
and more convincingly so for the early Java docs:
https://github.com/swig/swig/blob/12a43edc2df8853e8e0315f742e57be88f0c4269/Doc/Manual/Java.html#L2167-L2170
Caveat: I'm pretty sure I wrote that despite what the blame says so would have been my understanding at the time. 

Since then there's a been a slight feature creep into non-primitive types by some perhaps unaware target language authors, although I checked out the 'great merge' 516036631c4f08dcd57cfd2d7d1f4eead94fe243 and found the guile typemaps mentioned above, and this was the only language back then with these typemaps for non-primitive types (but was work by Matthias who only had a hand in the scheme languages).

> $isvoid addresses the case where the function doesn't have a void return (the PHP helper just doesn't yet make use of it yet as I was holding off until we resolved how we were going to fix this). To fix this for the void return case it seems either:

All the append functions should work the same, so for now I suggest implementing it like in Python's `SWIG_Python_AppendOutput` and this needs doing the same for all language I think still. The bugs will be flushed out when the missing tests are written. To me the behaviour in is fine for value types `SWIG_Python_AppendOutput` (where NULL is not a valid input value). We just document that a NULL equivalent, such as None, is not a valid input value. Handling this bad case in a defined manner (by ignoring it as in solution 1) is better than just returning back what is effectively invalid/junk, but another alternative is to return an error instead of accepting None.

> Also users can write their own Foo** OUTPUT typemaps using our t_output_helper()/equivalent helper function.

Yes absolutely users can write typemaps of their choosing, but I think we should agree and document that the append functions only work for primitive types. Users can write their own append functions and maybe we should just remove all the non-primitive typemaps and suggest if users really want them, they can copy and maintain legacy versions in their own code bases. I can't see this affecting a tiny number of users, probably no-one. Alternatively accept patches for a completely different implementation for non-primitive types.

I think `$isvoid` stands on its own legs as a useful feature and I see it as orthogonal to implementing a solution 5 and even remaining part of that solution. It's fully documented, so can go for 2(b), although my personal preference is still for 1 - it's a trade off between begrudgingly accepting NULL as an input without unnecessarily erroring out for existing usage (such as using NULL for INPUT typemaps) and still being able to pass NULL indicating an output is not wanted.

Digesting my own post, there is no perfect solution, but I think another could be a variation on 6, let's call it number 7:

7. Accept NULL for INPUT typemaps. Error out if NULL is passed in for INOUT typemaps, that is, implement an error in the append functions if a NULL equivalent is passed in as an input for appending. The whole ambiguity of NULL goes away by just not accepting it and the append functions are clearly documented for appending primitive values only.

**Comment by wsfulton** [comment] 2024-10-05 10:43
So seems like option 2(b), but independent of that, the actual bug reported is not yet fixed across all languages to use `$isvoid`.

> Still needs fixing for scripting languages supporting argout. [f3d4698...d940190](https://github.com/swig/swig/compare/f3d46986d34d3abb14ed1268b1d0996dca3e2bb2...d9401905f2316aa95376a6128f1e31f8cd5acc1f) from #2907 contains the fix for Python, but still needs extending for Ruby, PHP etc. @vadz, perhaps you could add in this and create testcases? If not, I'll get to it later.

I'll start this now so we can maybe get the release out later in the weekend, but leaving Ruby and PHP until last in case one of you is around to do this. I'll be adding in the missing `inout_runme.*` scripting language tests.

**Comment by vadz** [comment] 2024-10-05 21:26
Sorry, I hadn't returned to this because I was unsure what exactly had to be done. If the decision is taking now, I could try to do it for Ruby (I know absolutely nothing about PHP), but probably not before Tuesday.

**Comment by wsfulton** [comment] 2024-10-05 22:44
> Sorry, I hadn't returned to this because I was unsure what exactly had to be done. If the decision is taking now, I could try to do it for Ruby (I know absolutely nothing about PHP), but probably not before Tuesday.

No worries, it wasn't clear what we were going to do and I just did Ruby (was easy compared to the other languages for me).

Relevant updates in 8e65f9101...60a476982. Current problems are:

* D - D code fails to compile.
* Lua - more than one INOUT paremter simply does not work- no array is created for adding additional elements.
* Ocaml - not my area of expertise, ran out of patience getting tests to work!
* Octave - more than one INOUT parameter simply does not work, not sure why as the returned list seems to be correct in C++ code, but not in Octave.
* PHP - I didn't attempt this, @ojwb, would appreciate it if you had a go.
* R - ends up in an infinite loop with simple INOUT test.

**Comment by wsfulton** [comment] 2024-10-05 23:03
> D - D code fails to compile.

inout is a keyword in D, so I've renamed the testcase from inout to inout_typemaps. Will push this shortly.

**Comment by wsfulton** [comment] 2024-10-06 19:45
I've added a bunch of changes to add missing runtime tests.

@ojwb, I've also fixed PHP to support `$isvoid` in bb796b632a38137f9b99447046c16c4431875d9a. Commit c85e7ff8eab6f14238291673789435fc449e8512 also makes PHP consistent with the other scripting languages in that the append function is always available. The latter commit deprecates the `t_output_helper` which was deprecated by the other languages many years ago. Up to you when you remove the `t_output_helper` function and fragment, or if you feel PHP shouldn't be consistent with the other scripting languages, then please revert c85e7ff8eab6f14238291673789435fc449e8512.

**Comment by wsfulton** [comment] 2024-10-06 19:51
Final list of INOUT related problems I found is listed below. I leave them for interested parties to look at:

>     * Lua - more than one INOUT parameter simply does not work- no array is created for adding additional elements.
>     * Ocaml - not my area of expertise, ran out of patience getting tests to work!
>     * Octave - more than one INOUT parameter simply does not work, not sure why as the returned list seems to be correct in C++ code, but not in Octave.
>     * R - ends up in an infinite loop with simple INOUT test.

**Comment by ojwb** [comment] 2024-10-07 00:48
I was also intending to switch PHP to use the much better helper name and make it consistent with other languages so that's totally fine with me.

It should really be `SWIGINTERN` rather than `static` though so we don't add a warning about an unused static function when compiling wrappers that don't use it (which is probably the majority of wrappers) - I've pushed a change to do that.

What the original authors of these typemaps thought is somewhat interesting, but it's not uncommon for a feature to evolve beyond the scope originally conceived for it - I don't see why we aren't allowed to think about supporting non-primitive types here because that's all they originally had in mind.  Output via a pointer or non-const reference parameter is a pretty common pattern for C++ objects.

**Comment by wsfulton** [comment] 2024-10-07 06:55
The feature evolving is fine, but I'm not sure about the wisdom of building it on top the rather poorly implemented primitive foundations. It would probably need a different append function to deal with NULL. It occurred to me that if the append function took an additional input parameter indicating whether or not NULL was passed in, then there'd be enough logic to differentiate the ambiguous output NULL. $argnum could perhaps also be used.

Anyway, with the chosen solution 2(b), am closing. In summary, the bug reported in this issue is now implemented for the languages where INOUT actually works and anyone who is affected by any of the INOUT quirks/bugs should raise a separate issue.

**Closed by wsfulton** 2024-10-07 06:55 UTC
Labels: Python, PHP, Ruby
