### ISSUE TITLE
Error C4576 compiling an interface with an array initialiser in Visual Studio

### ISSUE THREAD

**Issue by Dijji** [swig/swig#1851] opened 2020-07-30 11:19 UTC
A simple repro is attached: 
[Swig C4576.zip](https://github.com/swig/swig/files/5000882/Swig.C4576.zip)

I have taken the supplied example of the use of std::vector with Python and added an initialiser to the average function:

double average(std::vector<int> v = {2048}) {
    return std::accumulate(v.begin(),v.end(),0.0)/v.size();
}

This generates wrapper code that initialises the argument as follows:

  std::vector< int,std::allocator< int > > arg1 = (std::vector< int,std::allocator< int > >) {
    2048
  } ;

This is in fact valid C99, but not correct C++. gcc will compile it, but msvc has become progressively less tolerant over time, producing a warning for a few versions, and in recent versions an error:

Error	C4576	a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax	Example	D:\Dev\Downloads\Swig C4576\example_wrap.cxx	9284	

Removing the type makes it compile happily:
 
  std::vector< int,std::allocator< int > > arg1 = {
    2048
  } ;

But obviously, this is not a desirable thing to do manually. Is there some fragment I can override to stop this happening, or something of the sort?

**Comment by ojwb** [comment] 2022-07-24 23:04
This seems specific to initializer lists which are C++11 so adjusting labels.

Reproduces with git master using command `swig -c++ -python -keyword example.i` (`-py3` is no longer useful there).  Dropping `-keyword` seems to avoid generating the bad code, so this seems to be specific to `-keyword`.  If you can do without keyword argument support, that would seem to be a workaround.

**Comment by ojwb** [comment] 2024-10-28 19:47
>  I don't know if this can also suggest some kind of fix?

We already know that simply omitting the `(Foo)` gives code that compiles and should work.  The likely tricky part which is still to be done is to come up with a patch that achieves that without breaking any cases which currently work but don't without that cast.

**Comment by wsfulton** [comment] 2024-10-30 19:50
I think I've got a fix for this, testing it atm.

**Closed** 2024-11-04 23:21 UTC
Labels: C++11
