### ISSUE TITLE
Feature Proposal: import_all from a given prefix

### ISSUE THREAD

**Issue by mmomtchev** [swig/swig#2484] opened 2023-01-12 19:47 UTC
I am currently making an interface for ImageMagick for Node.js - https://github.com/mmomtchev/node-magickwand

ImageMagick - when used from C++ - comes with 134 includes files - that must be included/imported in the right order in the swig interface definition.

I ended writing a generator using `g++ -H` to follow the include order.

However all this can be avoided if I am able to specify `-include_all`/`-import_all` with a prefix or a regexp - since all these files live under `/usr/include/ImageMagick`.

**Comment by ojwb** [comment] 2023-01-26 22:37
Closing as a duplicate of #2167.

**Closed by ojwb** 2023-01-26 22:37 UTC
