### ISSUE TITLE
swig4 not support template < class T, class = decltype(&T::to_json) >

### ISSUE THREAD

**Issue by kematy** [swig/swig#1590] opened 2019-07-14 04:44 UTC
I use swig4 compile json11,encounted an error:Error: Syntax error in input(3).
Here is the relevant code:
 template < class T, class = decltype(&T::to_json) >
    Json(const T & t) : Json(t.to_json()) {}

**Comment by ojwb** [comment] 2021-09-29 04:29
As I just noted in #1589, currently `decltype` only works on a variable, not an expression.

Closing this as a duplicate of #1589.

**Comment by wsfulton** [comment] 2023-07-25 21:49
After recent constructor handling improvements, the warning had changed to a more simple:
```
cpp11_template_parameters_decltype.i:36: Warning 302: Identifier 'Json' redefined (ignored),
cpp11_template_parameters_decltype.i:36: Warning 302: previous definition of 'Json'.
```
With 94ab6990752966758af5af3d6e43be9ae782eca8 comes consistency between constructors and methods in how this redefined identifier is warned about. More useful information is provided with the following commit 856d6f25e933fc7de9c00bd4179e458a7aef07b3, so that now the warning is:
```
cpp11_template_parameters_decltype.i:101: Warning 322: Redundant redeclaration of identifier 'Json' as Json::Json(Converter const &),
cpp11_template_parameters_decltype.i:101: Warning 322: previous declaration of 'Json' as Json::Json(Converter const &).
```
and requires `-Wall` for it to be shown by default.

This is a somewhat intractable problem to deal with because
```swig
%template(Json) Json::Json<Converter, std::string>;
```
 without the full type information for `decltype` and `std::enable_if` dumbly matches both of the two templated constructors:
```c++
  template < class T, class = decltype(&T::to_json) >
    Json(const T & t) : Json(t.to_json()) { ctor = 1; }

  // Implicit constructor: map-like objects (std::map, std::unordered_map, etc)
  template <class M, typename std::enable_if<
      std::is_constructible<std::string, decltype(std::declval<M>().begin()->first)>::value,
      int>::type = 0>
          Json(const M & m) : Json(object(m.begin(), m.end())) { ctor = 2; }
```
and so there is a duplicate Json constructor wrapper. This is what the warning is trying to say and ignores one of them. It generates one wrapper function which calls the right C++ function because the C++ compiler will call the right one. So at the end of the day, this is not ideal, but does end up working. The off by default warning seems sensible.

It is somewhat questionable weather all this template meta-programming in this example is ever going to be simple to use with SWIG due to the vast number of template instantiations required in order to wrap one constructor. I've actually enhance the testcase for the 3rd templated constructor originally posted in #1589, got quite confused trying to understand it, but eventually got it working, where you can see the java calls do match the C++ calls for all the constructor overloads. See the [tester() function](https://github.com/swig/swig/blob/856d6f25e933fc7de9c00bd4179e458a7aef07b3/Examples/test-suite/cpp11_template_parameters_decltype.i#L68) for the c++ output. I think this is all good enough to close this issue.

**Closed by wsfulton** 2023-07-25 21:49 UTC
Labels: C++11
