### ISSUE TITLE
Syntax error in input(1).

### ISSUE THREAD

**Issue by kothapraveen** [swig/swig#2980] opened 2024-07-30 13:05 UTC
Hi @vmiklos 

SWIG Version 3.0.9
we have included header file, which contains below lines in interface file, while compiling .i file facing error(Error Syntax error in input(1).)

#define STD(name) std::name

const STD (wstring)DATE_NULL_STRINGW (L"00000000");
const STD(string) DATE_NULL_STRING ("00000000");

interface file has below lines of code
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
namespace std {
	%apply const string & {string &};
};

%apply const std::wstring & {std::wstring &};

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by ojwb** [comment] 2024-07-31 02:18
The issue is reproducible with just:

```
const std::wstring DATE_NULL_STRINGW(L"00000000");
```

or even more simply:

```
int x(0);
```

If you're able to modify the code being wrapped, either of these are workarounds (the second requires C++11):

```
const std::wstring DATE_NULL_STRINGW = L"00000000";
```

```
const std::wstring DATE_NULL_STRINGW{L"00000000"};
```

Closing as a duplicate of #869.

**Closed by ojwb** 2024-07-31 02:18 UTC

**Comment by vmiklos** [comment] 2024-07-31 07:03
Hi Olly, good to see you're still alive. :-) And thanks for looking up what is the duplicate; having done ~nothing for SWIG in the past 10 years, I couldn't remember if this is a known problem or something new.
