### ISSUE TITLE
4.2.1: li_std_list test fails for java

### ISSUE THREAD

**Issue by dvzrv** [swig/swig#2859] opened 2024-04-04 10:57 UTC
Hi! :wave: 

When upgrading the package on Arch Linux I ran into the following:

```
./IntPtrList.java:222: error: removeLast() in IntPtrList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with SWIGTYPE_p_int
  where E is a type-variable:
    E extends Object declared in interface List
./IntPtrList.java:226: error: removeFirst() in IntPtrList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with SWIGTYPE_p_int
  where E is a type-variable:
    E extends Object declared in interface List
checking lua testcase derived_nested
./IntConstPtrList.java:222: error: removeLast() in IntConstPtrList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with SWIGTYPE_p_int
  where E is a type-variable:
    E extends Object declared in interface List
./IntConstPtrList.java:226: error: removeFirst() in IntConstPtrList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with SWIGTYPE_p_int
  where E is a type-variable:
    E extends Object declared in interface List
./StructList.java:221: error: removeLast() in StructList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
./StructList.java:225: error: removeFirst() in StructList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
checking python testcase python_moduleimport (with run test)
./StructPtrList.java:222: error: removeLast() in StructPtrList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
./StructPtrList.java:226: error: removeFirst() in StructPtrList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
./StructConstPtrList.java:222: error: removeLast() in StructConstPtrList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
checking java testcase abstract_typedef
./StructConstPtrList.java:226: error: removeFirst() in StructConstPtrList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with Struct
  where E is a type-variable:
    E extends Object declared in interface List
checking guile testcase derived_nested
./FruitList.java:221: error: removeLast() in FruitList cannot implement removeLast() in List
  public void removeLast() {
              ^
  return type void is not compatible with Fruit
  where E is a type-variable:
    E extends Object declared in interface List
./FruitList.java:225: error: removeFirst() in FruitList cannot implement removeFirst() in List
  public void removeFirst() {
              ^
  return type void is not compatible with Fruit
  where E is a type-variable:
    E extends Object declared in interface List
using C++ compiler: ‘g++ (GCC) 13.2.1 20230801’
36 errors
make[1]: *** [Makefile:95: li_std_list.cpptest] Error 1
```
[swig-4.2.1-1-x86_64-check.log](https://github.com/swig/swig/files/14865263/swig-4.2.1-1-x86_64-check.log)
[swig-4.2.1-1-x86_64-build.log](https://github.com/swig/swig/files/14865264/swig-4.2.1-1-x86_64-build.log)

This seems to have been reported against openjdk 21 in https://github.com/swig/swig/issues/2819
However, I'm not sure if the proposed fix is supposed to work for openjdk 22 as well and would be happy about clarification!

**Comment by wsfulton** [comment] 2024-04-04 18:19
Duplicate of #2767 and would also apply to openjdk 22 too.

**Closed by wsfulton** 2024-04-04 18:19 UTC
