### ISSUE TITLE
`SWIG_AsVal_int` doesn't fail correctly (returns `true`) when input value greater than INT_MAX

### ISSUE THREAD

**Issue by adewise1** [swig/swig#1036] opened 2017-07-26 21:01 UTC
In `SWIG_AsVal_int`, when `int res = SWIG_AsVal_long(obj, &v);` is executed, `SWIG_AsVal_long` calls `PyInt_Check(obj)`, which returns `true` even for numbers greater than `INT_MAX`. When `if(val) { *val = PyInt_AsLong(obj); }` then executes, it actually throws an OverflowError and returns `-1`, but `SWIG_AsVal_long` isn't checking for the return value, or that an error occurred, it just always returns `SWIG_OK`, so `SWIG_AsVal_int` ultimately thinks everything is okay and since the returned int is `-1`, the bounds check `if((v < INT_MIN || v > INT_MAX))` in `SWIG_AsVal_int` doesn't fail, which isn't correct.

**Comment by ojwb** [comment] 2017-07-26 21:28
It seems you understand the problem - any chance of a patch to address it?

**Comment by adewise1** [comment] 2017-07-26 22:31
I could, but I'm only a casual user of SWIG and an expert might better know the right way to fix this. 

My proposed fix would be to change the return statement in the if-statement `if PyInt_Check(obj)` in `SWIG_AsVal_long` function from `return SWIG_OK` to `return (!PyErr_Occurred() ? SWIG_OK : SWIG_ERROR);` Perhaps the actual error, in this case, `SWIG_OverflowError` can replace `SWIG_ERROR`

**Comment by ojwb** [comment] 2023-12-10 21:30
No reproducer was provided, but with SWIG 4.1.0:

```
$ cat test.i
%module x
%inline %{
#include <stdio.h>
void test(int v) { printf("In C v is %d\n", v); }
%}
$ swig -python test.i
$ gcc `python2-config --cflags` test_wrap.c -fPIC -shared -o _x.so
$ python2 -c 'import x; x.test(0x80000000)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "x.py", line 63, in test
    return _x.test(v)
OverflowError: in method 'test', argument 1 of type 'int'
$ gcc `python3-config --cflags` test_wrap.c -fPIC -shared -o _x.so
$ python3 -c 'import x; x.test(0x80000000)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/olly/git/swig/gh1036/x.py", line 63, in test
    return _x.test(v)Not reproducible w
           ^^^^^^^^^^
OverflowError: in method 'test', argument 1 of type 'int'
```

I tested Python2 as well `PyInt_Check()` seems to be specific to Python2.

It seems this has been fixed in the meantime so closing.

**Closed by ojwb** 2023-12-10 21:30 UTC
Labels: Python
