### ISSUE TITLE
[C#] %constant strips f suffix from values with %csconst(1)

### ISSUE THREAD

**Issue by rokups** [swig/swig#1917] opened 2021-01-09 16:45 UTC
bug.i:
```swig
%csconst(1);
%constant const float VariantValueSize = 4.0f;
```

Command line: `swig -csharp -module bug bug.i`

Result:

bug.cs
```cs
public class bug {
  public const float VariantValueSize = 4.0;
}
```

This is not a valid C# code:
```
% csc bug.cs
Microsoft (R) Visual C# Compiler version 3.6.0-4.20224.5 (ec77c100)
Copyright (C) Microsoft Corporation. All rights reserved.

bug.cs(13,41): error CS0664: Literal of type double cannot be implicitly converted to type 'float'; use an 'F' suffix to create a literal of this type
```

**Comment by matze** [comment] 2021-03-15 11:51
On the other hand it does not drop the literal where it's supposed to be.
```
%javaconst(1)
%include "enumsimple.swg"
enum Foo { BAR = 1U << 1 };
```
turns into
```java
public interface bugConstants {
   // Foo
   public final static int BAR = 1U << 1;
}
```
which is not valid Java code.

**Comment by ojwb** [comment] 2022-03-03 23:59
The docs for `%javaconst` explicitly note the second limitation:

>Be careful using the `%javaconst(1)` directive as not all C code will compile as Java code. For example neither the 
`1000LL` value for `BIG` nor `2000ULL` for `LARGE` above would generate valid Java code.

The first case is more curious in that SWIG is adjusting the value, but (if I follow) it would actually work better if it didn't.

It looks like it's a special case in the scanner:

```
      } else if ((c == 'e') || (c == 'E')) {
        state = 82;
      } else if ((c == 'f') || (c == 'F')) {
        Delitem(s->text, DOH_END);
        return SWIG_TOKEN_FLOAT;
      } else if (isdigit(c)) {
        state = 8;
      } else if ((c == 'l') || (c == 'L')) {
        state = 87;
      } else if ((c == 'u') || (c == 'U')) {
        state = 88;
```

Removing that would need careful testing as other things may be relying on it currently.  Perhaps the C# backend should handle this as it'd be nicer if this also generated valid C#:

```
%constant const float VariantValueSize = 4.0;
```

**Comment by ak-ldube** [comment] 2024-07-09 01:03
Is there any known workaround for this?
We're getting bad cs code after updating the swig 4.2.1.
Our c++ is `#define OUR_CONSTANTS (0.0f)`
it gets converted to
`public const float OUR_CONSTANTS = (0.0);`


Before 4.2.1, it was getting converted to double, so we weren't gettins this issue, but now it's "properly" being converted to float, but we get this issue now.

Thanks!

**Comment by ojwb** [comment] 2024-07-09 21:53
You could workaround by defining such constants as `double` in your interface file before SWIG parses the headers which define them (the `%warnfilter` suppresses a warning about the constant already being defined):

```
%constant double OUR_CONSTANTS = 0.0;
%warnfilter(302) OUR_CONSTANTS;
```

or:

```
%constant float OUR_CONSTANTS = (float)0.0;
%warnfilter(302) OUR_CONSTANTS;
```

That does require duplicating their names and values from the C/C++ header though.

If you can change the header being wrapped, using a `(float)` cast instead of the suffix should work for both C/C++ and older and current SWIG:

```
#define OUR_CONSTANTS ((float)0.0)
```

It seems to fix this in SWIG ideally the C# backend would suffix literals with `f` when they're initialising `float` constants, as that would allow `%constant const float VariantValueSize = 4.0;` to work.  From past discussion, @wsfulton seems reluctant to go down the road of rewriting values though and the excursion into doing it in SWIG/Python did result in multiple bugs - it's quite easy to do some text munging which fixes the cases in front of you but breaks others.  I think doing it in the parser would be the way to go, and the parser is steadily getting smarter at dealing with expressions and their types (driven mainly by improving support for C++ `auto` and `decltype`).

The current removal of the `f` suffix in the scanner seems wrong since it violates the idea that `%csconst(1);` works so long as the C/C++ initialisers are valid for C#, so perhaps we should stop doing that even if we do try to fix the generated C# code for `float` constant values.  I do worry that stopping doing that may also cause fallout, but I'll push a branch so we can at least see from CI if it breaks anything with test coverage.

**Comment by ak-ldube** [comment] 2024-07-09 23:47
Yep, we ended up working around the issue using the %constant definition in our .swig file. It's just not ideal since the c++ could change (IE, they could remove the constant all together) and the c# wouldn't be updated unless we remember to do it.

Sadly we cannot change the c++ header, so that's why we ended up going for the workaround. 

Thank you for looking into it. we had to add ~15 constant definition to the swig file and if the constant value on the c++ side change without warning (different team, as much as team talk between each other, this is the stuff that is easy to miss), we could end up having some bugs on the c# side.

**Comment by wsfulton** [comment] 2024-07-10 07:27
Similar to #2576 where some ideas proposed for a generic solution can be discussed and would solve the problem of having to replicate the C++ constants again on the SWIG side.

**Comment by ojwb** [comment] 2024-07-12 01:10
A key difference here is that SWIG actually goes slightly out of its way to break `%constant const float VariantValueSize = 4.0f;` by unconditionally stripping the `f` suffix from float literals.  That's been done basically forever it seems, and I suspect it was done because SWIG used to treat `float` and `long double` literals as having type `double`.  I fixed that in 4.2.0 because otherwise C++ `auto` and `decltype` get the type wrong, so I think we should probably stop stripping `f` suffixes to realign things (and similarly `l` suffixes from `long double` literals).

Another difference is that this case is a regression as it worked before 4.2.0.

My experimental commit to do the former (linked above) passed CI, which is promising.  I think we should merge it, but I'd like to review the handling of this for all the target languages first just to check it only leads to us using the suffixed constant value in target languages which support it (like C#).

**Comment by wsfulton** [comment] 2024-07-12 17:47
Fixing `%constant` to be realign with C and C++ code make sense.

**Comment by ak-ldube** [comment] 2024-07-12 18:18
The automatic generation should be fixed too.

**Comment by ojwb** [comment] 2024-07-15 05:41
> I think we should merge it, but I'd like to review the handling of this for all the target languages first just to check it only leads to us using the suffixed constant value in target languages which support it (like C#).

I tested with this test-suite patch:

```
--- a/Examples/test-suite/constant_expr_c.i
+++ b/Examples/test-suite/constant_expr_c.i
@@ -77,3 +77,26 @@ const int s9a = sizeof(-s8a);
 // const int s9b = sizeof -s8a; /* not currently supported */
 
 %}
+
+#ifdef SWIGCSHARP
+%csconst(1);
+#endif
+#ifdef SWIGJD
+%dconst(1);
+#endif
+#ifdef SWIGJAVA
+%javaconst(1);
+#endif
+#ifdef SWIGSCILAB
+%scilabconst(1);
+#endif
+
+%inline %{
+
+#define fltest4 3.625f
+const float fltest1 = 0.625f;
+
+%}
+
+%constant fltest2 = 1.625f;
+%constant float fltest3 = 2.625f;
```

We only get the `f` suffixed constant used in target language code for C# and Java, both of which also take an `f` or `F` suffix to mean a `float` literal.

The Python code which decides if it can use a C/C++ literal in Python already removes an `f` or `F` suffix - this code gets used e.g. for wrapping:

```
%inline %{
float x(float y = 4.625f) { return y; }
%}
```

Aside from C#, Java and Python, poking around SWIG's code I don't see any other paths which could result in such constants being used in another target language, so I'm increasingly confident ee146fd0c7af8595eca7ac590b5410126c2cd204) is a safe change.  It ought to include a regression test for the case here though.

**Closed** 2024-07-18 04:15 UTC
Labels: C#

**Comment by ojwb** [comment] 2024-07-18 04:21
Fixed for `f` and `F` suffixes.

The similar case for `long double` with `l` and `L` suffixes doesn't actually work properly currently for other reasons.  I've opened #2964 to track that.

The `enum Foo { BAR = 1U << 1 };` case is covered by #2576.
