### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by DemiMarie** [swig/swig#919] opened 2017-02-26 00:52 UTC
Looking at some of the code related to exceptions seems to indicate that CLR exceptions are being thrown across C++ stack frames.  This isn't supported on .NET Core and will summarily terminate the process.

Instead, the data needs to be returned as an unmanaged struct, from which the C# code will decide what exception to throw.

**Comment by ojwb** [comment] 2022-01-27 07:36
Closing as a duplicate of #1299 (newer but has a lot more discussion).  Despite the title it's not only about Linux.

**Closed by ojwb** 2022-01-27 07:36 UTC
Labels: C#
