### ISSUE TITLE
"using" keyword with operator== on parent method hides child method

### ISSUE THREAD

**Issue by jschueller** [swig/swig#2687] opened 2023-10-10 14:58 UTC
consider the following class hierarchy with a base class "Object", a Distribution class and its two children with comparison operators, classic C++(98?), nothing fancy:

```
  class Object
  {
  public:
    Object() {}

    virtual ~Object() {}

    inline virtual
    bool operator ==(const Object & /*other*/) const
    {
      std::cout << "Object operator =="<<std::endl;
      return true;
    }

    virtual std::string __repr__() const {return "Object"; }

    inline virtual
    bool operator !=(const Object & other) const
    {
      std::cout << "Object operator !="<<std::endl;
      return !operator==(other);
    }
  };

  class Distribution : public Object
  {
  public:
    Distribution() : Object() {}

    std::string __repr__() const override {return "Distribution"; }
    
    /** Comparison operator */
// #ifndef SWIG
    using Object::operator ==;
// #endif
    bool operator ==(const Distribution & other) const
    {
      std::cout << "Distribution operator == this="<<this->__repr__() << " other=" << other.__repr__()<<std::endl;
      if (this == &other) return true;
      // Compare both this to other and other to this to ensure symmetry
      return equals(other) && other.equals(*this);
    }
    
    using Object::operator !=;
    bool operator !=(const Distribution & other) const
    {
      std::cout << "Distribution operator != this="<<this->__repr__() << " other=" << other.__repr__()<<std::endl;
      return !operator==(other);
    }

  protected:
    virtual bool equals(const Distribution & /*other*/) const {throw std::runtime_error("notyet"); }
  };
  
  class Uniform : public Distribution
  {
  public:
    Uniform(double a = 0., double b = 1.) : Distribution(), a_(a), b_(b) {}

    using Distribution::operator ==;
    bool operator ==(const Uniform & other) const
    {
      if (this == &other) return true;
      return a_ == other.a_ && b_ == other.b_;
    }
    
    std::string __repr__() const override {return "Uniform";}
    
  protected:
    bool equals(const Distribution & other) const override
    {
      std::cout << "Uniform equals="<<this->__repr__() << " other=" << other.__repr__()<<std::endl;
      const Uniform* p_other = dynamic_cast<const Uniform*>(&other);
      return p_other && (*this == *p_other);
    }

  private:
    double a_ = 0.;
    double b_ = 1.;
  };
  
  class Gumbel : public Distribution
  {
  public:
    Gumbel(double beta = 0., double gamma = 1.) : Distribution(), beta_(beta), gamma_(gamma) {}

    using Distribution::operator ==;
    bool operator ==(const Gumbel & other) const
    {
      if (this == &other) return true;
      // Compare both this to other and other to this to ensure symmetry
      return beta_ == other.beta_ && gamma_ == other.gamma_;
    }

    std::string __repr__() const override {return "Gumbel";}
  protected:
    bool equals(const Distribution & other) const override
    {
      std::cout << "Gumbel equals="<<this->__repr__() << " other=" << other.__repr__()<<std::endl;
      const Gumbel* p_other = dynamic_cast<const Gumbel*>(&other);
      return p_other && (*this == *p_other);
    }
  private:
    double beta_ = 0.;
    double gamma_ = 1.;
  };
```

in Distribution I redefine the operator== so  I want to add "using Object::operator ==;" to avoid the gcc warning:
```
/tmp/Mesh.hxx:17:10: warning: ‘virtual bool OT::Object::operator==(const OT::Object&) const’ was hidden [-Woverloaded-virtual=]
   17 |     bool operator ==(const Object & /*other*/) const
      |          ^~~~~~~~
/tmp/Mesh.hxx:44:10: note:   by ‘bool OT::Distribution::operator==(const OT::Distribution&) const’
   44 |     bool operator ==(const Distribution & other) const
```

but by doing so, from Python the operator== now does not go into children classes and returns the default "true" value of the Object class:

```
import openturns as ot
d1 = ot.Uniform(2,5)
d2 = ot.Gumbel(3,4)
print(d1 == d2)
print(d1 != d2)
```

gives the output True instead of False for the first comparison:
```
Object operator ==
True
Distribution operator != this=Uniform other=Gumbel
Distribution operator == this=Uniform other=Gumbel
Uniform equals=Uniform other=Gumbel
True
```

from pure c++ the same header gives the correct answer:
```
int main() {
  OT::Uniform d1(2,5);
  OT::Gumbel d2(3,4);
std::cout << (d1 == d2)<<std::endl;
std::cout << (d1 != d2)<<std::endl;
std::cout << "OK"<<std::endl;
  return 0;
}

Distribution operator == this=Uniform other=Gumbel
Uniform equals=Uniform other=Gumbel
0
Distribution operator != this=Uniform other=Gumbel
Distribution operator == this=Uniform other=Gumbel
Uniform equals=Uniform other=Gumbel
1
OK
```

so the code is correct from a c++ view point

if I hide the `using Object::operator ==;` line from swig with the "ifndef SWIG" it goes fine:
```
Distribution operator == this=Uniform other=Gumbel
Uniform equals=Uniform other=Gumbel
False
Distribution operator != this=Uniform other=Gumbel
Distribution operator == this=Uniform other=Gumbel
Uniform equals=Uniform other=Gumbel
True
OK
```

to reproduce:

```
git clone -b opequal https://github.com/jschueller/swig-field-example.git
cmake -S swig-field-example -B build -DCMAKE_INSTALL_PREFIX=$PWD/build/install
make -C build install
PYTHONPATH=$PWD/build/install/lib/python3.10/site-packages/ python3 test-fieldfunction.py
```

sorry for the long post

**Comment by wsfulton** [comment] 2023-10-11 17:29
93732bb19562534c81c537b8a83e38451556415c recently committed should have fixed this, but does not cover your use case. It needs enhancing for the using declaration being declared before the overloaded method. Looking at fixing... It's not related to the fact that it is an operator from what I can tell.

**Comment by wsfulton** [comment] 2023-10-11 20:28
Simple reproducer tweaking the test-suite:
```diff
diff --git a/Examples/test-suite/using_member_multiple_inherit.i b/Examples/test-suite/using_member_multiple_inherit.i
index 0b4660c9b..efec643f5 100644
--- a/Examples/test-suite/using_member_multiple_inherit.i
+++ b/Examples/test-suite/using_member_multiple_inherit.i
@@ -18,12 +18,12 @@ protected:
 };
 struct Using2 : Using1 {
 protected:
-  void usingmethod(int i, int j) {}
   using Using1::usingmethod;
+  void usingmethod(int i, int j) {}
 };
 struct Using3 : Using2 {
-  void usingmethod(int i, int j, int k) {}
   using Using2::usingmethod;
+  void usingmethod(int i, int j, int k) {}
 };
 
 // Multiple inheritance, multiple using declarations
```
Using3 class is missing wrappers for 
```
Using2::usingmethod(int i, int j)
```
because of a peculiarity in the symbol table lookups calling `Swig_symbol_clookup`.  If a symbol found is a using declaration then the using declarations are chased up the inheritance hierarchy. When the symbol is overloaded, then behaviour is not consistent, such as in this case if the using declaration is declared before the overloaded method declaration. In the case above, the parse tree is not correct as https://github.com/swig/swig/blob/34e25241e7f3d5e6547aa6f065a50a654e0c5b17/Source/CParse/parser.y#L4477-L4478 returns `uname = "Using1::usingmethod"` instead of `uname = "Using2::usingmethod"` processing:
```c++
  using Using2::usingmethod;
```
Even if this was corrected, 
https://github.com/swig/swig/blob/34e25241e7f3d5e6547aa6f065a50a654e0c5b17/Source/Modules/allocate.cxx#L802-L803
will return `Using1::usingmethod` again, thereby missing out adding in all the methods from `Using2::usingmethod`.

Notes above are for me really to look at this again, but it won't be soon. In the meantime, I suggest using a workaround of putting the using declaration after the method declarations.

**Comment by jschueller** [comment] 2023-10-12 07:46
yes, changing the order of the using works for me too, thanks for looking into it

**Comment by wsfulton** [comment] 2023-10-16 19:00
I couldn't help looking at this some more and thought of a reasonably undramatic fix, commit arriving shortly.

**Closed** 2023-10-17 20:37 UTC
Labels: C++

**Comment by jschueller** [comment] 2023-10-18 06:49
thanks a lot
