### ISSUE TITLE
Consider converting docs to something easier to maintain like Sphinx

### ISSUE THREAD

**Issue by tleonhardt** [swig/swig#933] opened 2017-03-01 23:03 UTC
I recently submitted a PR with some documentation updates.  Compared to other projects I've updated documentation for, this took me about 5 to 10 times as long for the same amount of work because updating hand-written HTML is a lot of work.

We all know how the average developer hates writing documentation.  Anything which makes writing documentation more painful means that much of the time it simply won't get done.

It would probably require a significant up-front one-time investment of time, but I think the core SWIG developers should consider converting the docs to a format that is easier to maintain.  I would recommend [Sphinx](http://www.sphinx-doc.org) but there are certainly other alternatives as well.

I haven't tried it, but [this](https://github.com/averagehuman/python-html2rest) open-source project is designed to help automate the process.

**Comment by vadz** [comment] 2017-03-02 21:47
I think Sphinx is a good choice, but ideally I'd like to use it with Markdown rather than reST. I know that this is possible now, although I haven't had any chance to test it yet. If it works half decently, I think we should prefer Markdown just because almost everybody, and absolutely everybody using Github, is already familiar with it and would lower the barrier for updating the docs even more than reST (which is, admittedly, also not difficult to learn, but is still more idiosyncratic than Markdown).

**Comment by tleonhardt** [comment] 2017-03-03 01:38
[recommonmark](https://github.com/rtfd/recommonmark) allows you to use both Markdown (*.md) and reStructuredText (*.rst) inside of the same Sphinx project.

**Comment by ojwb** [comment] 2017-03-03 02:16
> I think Sphinx is a good choice, but ideally I'd like to use it with Markdown rather than reST. I know that this is possible now, although I haven't had any chance to test it yet. If it works half decently, I think we should prefer Markdown just because almost everybody, and absolutely everybody using Github, is already familiar with it and would lower the barrier for updating the docs even more than reST (which is, admittedly, also not difficult to learn, but is still more idiosyncratic than Markdown).

Except there are various different flavours of markdown (e.g. github
uses "github-flavoured markdown"), so with markdown everyone would
need to watch out for the quirks of the flavour they're writing for vs
those of flavour they know.

> recommonmark allows you to use both Markdown (.md) and reStructuredText (.rst) inside of the same Sphinx project.

Using two different but conceptually similar markup languages in one
set of documentation seems like a recipe for confusion.

**Comment by tleonhardt** [comment] 2017-03-06 13:29
If you do choose to use Markdown with Sphinx, it is specifically the strongly defined [CommonMark](http://commonmark.org/) variant which is supported.

And when I pointed out that Sphinx can simultaneously support Markdown and reStructuredText side-by-side in the same project, I did not mean to imply that doing so would be a good idea.   I just wanted to point out that it doesn't tie you to one and you could freely choose between the two formats to find which one would best suit the needs of your project.

**Comment by thorade** [comment] 2018-05-25 08:43
also see #1204

**Comment by sethrj** [comment] 2018-05-25 17:10
Ha thanks for the cross-reference, I didn't see this issue before.

**Comment by ojwb** [comment] 2022-01-26 03:39
I'm going to close this as a duplicate of #1204 (this one is older, but #1204 has more discussion.

**Closed by ojwb** 2022-01-26 03:39 UTC
Labels: enhancement, documentation
