### ISSUE TITLE
TypeError in Python with 'std::string const &'

### ISSUE THREAD

**Issue by Alexander-Eck** [swig/swig#620] opened 2016-02-27 18:28 UTC
Passing a string from Python via a SWIG-compiled module to a C++ function that expects input in the form of `std::string const &` does not work.

To provide an example of what is happening, this is a revevant part in one of the `.h` files:
```
Config init(const std::string& flags);
```

And here from the corresponding `.cpp`:
```
Config init(const std::string& flags) {
	Config conf;
	try { ......... }
	catch (std::exception& e) {
		std::cerr << e.what() << std::endl;
	}
	return conf;
}
```

This is how the `.i` file was configured:
```
%module test
%{
#include "src/test.h"
%}
%include "std_string.i"
%include "src/test.h"
```

Swig apparently captured the const `std::string&`, as the wrapper code shows:
```
SWIGINTERN PyObject *_wrap_init(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  std::string *arg1 = 0 ;
  int res1 = SWIG_OLDOBJ ;
  PyObject * obj0 = 0 ;
  Config result;
  
  if (!PyArg_ParseTuple(args,(char *)"O:init",&obj0)) SWIG_fail;
  {
    std::string *ptr = (std::string *)0;
    res1 = SWIG_AsPtr_std_string(obj0, &ptr);
    if (!SWIG_IsOK(res1)) {
      SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "init" "', argument " "1"" of type '" "std::string const &""'"); 
    }
    if (!ptr) {
      SWIG_exception_fail(SWIG_ValueError, "invalid null reference " "in method '" "init" "', argument " "1"" of type '" "std::string const &""'"); 
    }
    arg1 = ptr;
  }
  result = init((std::string const &)*arg1);
  resultobj = SWIG_NewPointerObj((new Config(static_cast< const Config& >(result))), SWIGTYPE_p_Config, SWIG_POINTER_OWN |  0 );
  if (SWIG_IsNewObj(res1)) delete arg1;
  return resultobj;
fail:
  if (SWIG_IsNewObj(res1)) delete arg1;
  return NULL;
} 
```

In Python 3.4 64-bit running on Windows 10, I've tried to pass the value in these ways:
Variant A:
```
conf = test.init("--two-level -v -N2")
```
Variant B:
```
flags = "-2 -v -N2"
conf = test.init(flags)
```
Variant C:
```
conf = test.init(str("--two-level -v -N2"))
```

Where's the error? Because I can't find one, even after many hours of tracing what is happening.

Besides 3.0.8 I've tried compilation with 2.0.12, 3.0.0, 3.0.2, and 3.0.6. All produced the same results (1.3.xx did not compile with the setup that I have).

**Comment by wsfulton** [comment] 2016-04-01 18:43
The above should work in all versions and does worked for me using swig-3.0.8. Did you debug it to see if the string values appear in the C++ code as expected? What error are you expecting? The code as it stands won't print any error assuming your code in the try block does not error out. I suggest you use the class example working that is shipped with SWIG, then you'll be sure you have a working environment, then modify the code to try out a simple std::string function.

**Comment by Alexander-Eck** [comment] 2016-04-01 19:00
Unfortunately, I've reset the machine since trying to compile the code mentioned above. Specifically, I tried to get a wrapper for this package: http://www.mapequation.org/code.html#Examples-with-other-languages

Sorry I can't be of more help here. Re-configuring everything would cost me easily a day of work, as I am an absolute novice when it comes to the Swig ecosystem.

**Comment by wsfulton** [comment] 2016-04-01 19:25
Closing as not enough info to reproduce.

**Closed by wsfulton** 2016-04-01 19:25 UTC

**Comment by mikesparr** [comment] 2016-08-29 15:18
Same thing occurring for me with a C lib using SWIG for Python bindings called librets.  I have this error appearing recently on both Mac OS and Ubuntu Linux:

~~~
  File "/Users/mike/Work/etl-service/etlservice/util/rets_client.py", line 919, in _get_photos
    request = librets.GetObjectRequest(ptype.decode('utf-8'), otype.decode('utf-8'))
  File "/Library/Python/2.7/site-packages/librets.py", line 1282, in __init__
    this = _librets.new_GetObjectRequest(resource, type)
TypeError: in method 'new_GetObjectRequest', argument 1 of type 'std::string'
~~~

Here is the source from project:
 * https://github.com/NationalAssociationOfRealtors/libRETS/blob/master/project/librets/src/GetObjectRequest.cpp

It is merely instantiating a class with two arguments but that fails now. I have tried to recompile/build the library and still failing. I'm unsure why it fails to instantiate a class (not even perform any request actions) with these errors but appreciate any insights.

**Comment by mikesparr** [comment] 2016-08-29 15:56
Ah, it appears strings were passing as <'unicode'> type so forcing ASCII type `str(varname)` into argument solved. I hope this is helpful to others.

~~~
>>> v = u'Photos'
>>> 
>>> type(v)
<type 'unicode'>
>>> 
>>> type(v.decode('utf-8'))
<type 'unicode'>
>>> 
>>> type(str(v))
<type 'str'>
>>> 
>>> type(v.decode('ascii'))
<type 'unicode'>
>>> 
~~~

**Comment by thorade** [comment] 2017-05-22 15:11
I just ran into this error after I added 
`from __future__ import unicode_literals`
to my scripts.

**Comment by wsfulton** [comment] 2017-05-22 18:57
Have you tried using `SWIG_PYTHON_2_UNICODE`, see http://swig.org/Doc3.0/Python.html#Python_2_unicode?

**Comment by gbmhunter** [comment] 2017-08-17 16:30
I had the same error:

````
TypeError: in method 'xxx', argument 2 of type 'std::string const &'
````

which I managed to fix by adding:

````
%include <std_string.i>
````

to the SWIG `MyModule.i` file.

**Comment by TimSC** [comment] 2017-09-01 03:51
I had to add:
```
%include std_string.i
using std::string;
```
to my interface file. This applied to both python 2 and 3.

**Comment by artgoldberg** [comment] 2017-10-07 15:07
I'm experiencing this error also, but inconsistently. I'm running Python 3 on OS X and Linux (Docker Python) without error. But in some cases Python 2.7 calls fail repeatedly on Linux (Docker Python).

I'm happy to share all the code involved.

**Comment by ojwb** [comment] 2017-10-07 20:00
A small, self-contained reproducer would be useful.

**Comment by artgoldberg** [comment] 2017-10-08 00:46
I understand, but unfortunately I can't. I'm using a fairly big body of python code which in turn uses libsbml](http://sbml.org/Software/libSBML/docs/python-api/index.html), a 50+ KLOC library, which uses SWIG to interface to C++. 
But I'll let you know what I learn.

**Comment by artgoldberg** [comment] 2017-10-08 16:23
The comment by mikesparr regarding unicode solved my problem.

ojwb, I suggest that you try 4 ways of calling C++ from Python through SWIG: {python 2.7, Python 3.x where 5<=x} x {pass unicode text, pass str text}. I predict that all calls will succeed, **except** for (python 2.7, pass unicode text). I've never written SWIG and rarely write C++ now, so I'm not the right man for this job.

**Comment by ojwb** [comment] 2017-10-08 19:38
Um, that's **as documented** - see wsfulton's comment above:

> Have you tried using `SWIG_PYTHON_2_UNICODE`, see http://swig.org/Doc3.0/Python.html#Python_2_unicode?

Presumably this wasn't just made the default for compatibility reasons.

**Comment by artgoldberg** [comment] 2017-10-10 16:22
I didn't write the SWIG code. I'm just using a package that contains it.

What compatibility is achieved by not using SWIG_PYTHON_2_UNICODE? The docs don't explain that.

**Comment by ojwb** [comment] 2017-10-10 20:28
Note this is a closed ticket, not a discussion forum.  If you want a discussion forum then please use the mailing lists for discussion, as far more people read them than read incoming ticket comments.

> I didn't write the SWIG code. I'm just using a package that contains it.

Then tell whoever maintains that package to use this option, or regenerate the SWIG code in the package for yourself.

> What compatibility is achieved by not using SWIG_PYTHON_2_UNICODE? The docs don't explain that.

Compatibility with how SWIG worked before `SWIG_PYTHON_2_UNICODE` was added.

Some users added custom typemaps to their interface files to handle `unicode` for `std::string` before `SWIG_PYTHON_2_UNICODE` was added.  If this feature was on by default, we have to worry about how it would interact with such custom typemaps.

**Comment by artgoldberg** [comment] 2017-10-10 22:43
Thanks for the reply ojwb.
I don't want a discussion forum, as I've learned what I need to know. I've recommended that the developers of the package make the change, as it would make my code cleaner and possibly help other users, but I cannot compel them nor will I make the change myself.

**Comment by yuanzhedong** [comment] 2018-02-06 00:22
Just a note, I got same error message and find out it's caused by not adding `std::` prefix:`void init(const string& flags)`, changing to `init(const std::string& flags)` will fix mine.

**Comment by gaoyiyeah** [comment] 2018-09-12 16:27
Had the same error and add %include <std_string.i> works for me.

**Comment by burlen** [comment] 2019-05-14 17:59
I hit this issue with Python 2 when using a string returned from my SWIG wrapped object. When my wrapped code returned a string, SWIG converted it to a unicode string, and then it can no longer be passed through the wrapped API. 

I believe that it is a bug in SWIG. In Python 2 strings are not unicode and SWIG should not return them as such. Am I wrong?

here is an example
```
from teca import *

md = teca_metadata()                                                                                                                                                                                    
md['key_name']='key_value'
md['key_value']=5

print "md['key_name']=%s"%(md['key_name'])
print "md['key_value']=%s"%(md['key_value'])

try:
    print "md[md['key_name']]=%d"%(md[md['key_name']])
except:
    print "md[md['key_name']] <------------------------------ FAIL!"
    print "type(md['key_name'])=%s"%(str(type(md['key_name'])))
    print "type(str(md['key_name']))=%s"%(str(type(str(md['key_name']))))

print "md[str(md['key_name'])]=%d"%(md[str(md['key_name'])])
```

and when run it does this
```
pipin:~/TECA/bin$python ../test.py 
md['key_name']=key_value
md['key_value']=5
md[md['key_name']] <------------------------------ FAIL!
type(md['key_name'])=<type 'unicode'>
type(str(md['key_name']))=<type 'str'>
md[str(md['key_name'])]=5
```
this shows SWIG is returning std::string as a unicode string, which is both self inconsistent and inconsistent with Python 2 convention.

` #define SWIG_PYTHON_2_UNICODE` works around it, as well as explicit conversion `str(md['key_name'])`

**Comment by burlen** [comment] 2019-05-14 18:15
I hit this, but it was a problem in my code, a stray `PyUnicode_FromString` had snuck in when we upgraded from Python 2 to Python 3.
