### ISSUE TITLE
Unit tests failing with GCC 7.2

### ISSUE THREAD

**Issue by matlo607** [swig/swig#1211] opened 2018-03-21 15:03 UTC
Version: 3.0.12
The error messages changed a bit with GCC 7.2
The failing tests are :
* cpp_extra_brackets
```
# cat Examples/test-suite/errors/cpp_extra_brackets.stderr
cpp_extra_brackets.i:5: Error: Unexpected ')'.
# cat Examples/test-suite/errors/cpp_extra_brackets.newerr
cpp_extra_brackets.i:5: Error: Syntax error in input(3).
```
* c_missing_semi
```
# cat Examples/test-suite/errors/c_missing_semi.stderr
c_missing_semi.i:3: Error: Syntax error - possibly a missing semicolon.
# cat Examples/test-suite/errors/c_missing_semi.newerr
c_missing_semi.i:3: Error: Syntax error in input(1).
```

**Comment by ojwb** [comment] 2018-03-21 20:32
Those are SWIG error messages, not GCC error messages, so I don't think this is connected to your GCC version (and `make check-errors-test-suite` passes for me with GCC 7.3).

Those test cases are checking that SWIG gives a useful error rather than a generic one for common mistakes, so it looks to me like you're running the testsuite using an older SWIG version from before those errors were improved.  Perhaps an installed one rather than the one in the source tree?

**Comment by matlo607** [comment] 2018-03-22 13:19
@ojwb, you are right, they are not GCC's error messages.
You were also right about the old testsuite, I had an old swig version installed on my machine.
However, even after removal of the old swig, I still get the tests failing.

Just to be sure if it was not my configuration, I ran the build inside a docker `gcc:7.3` (https://hub.docker.com/r/library/gcc/tags/) and I managed to reproduce the 2 failures mentionned above.
Please follow the procedure below to reproduce it.

Dockerfile:
```
FROM gcc:7.3

RUN apt-get update \
 && apt-get install -y "byacc" "python-pip" \
 && pip install "conan" \
 && conan profile new --detect "default"

CMD ["bash"]
```

```
docker build --network=host --tag gcc73-swig:latest .
docker run --network=host -it gcc73-swig:latest bash
git clone https://github.com/matlo607/conan-swig.git
cd conan-swig
conan create . swig/testing
```

**Comment by ojwb** [comment] 2018-03-22 22:03
I'm happy to look if you can supply a small and self-contained reproducer, but anything that involves me having to install huge software stacks such as docker and wade through a build system I've never even heard of before isn't likely to happen though, sorry.

Does this happen for you with SWIG git master?

**Comment by matlo607** [comment] 2018-03-23 00:06
I gave you the Dockerfile and 5 commands to run so that you be able to test it in less than 10 minutes without having to care about changing the environment on your machine. I can hardly provide you a better procedure. Installing Docker can be done easily using the distribution's package manager, they provide repositories for CentOS, Ubuntu, Fedora and Debian (https://docs.docker.com/install/linux/docker-ce/ubuntu/). You should not pay attention to conan, it's just a package manager, it's exactly the same as you will do to build a RPM or a DEB package => [CppCon 2016: Diego Rodriguez-Losada “Conan, a C and C++ package manager for developers"](https://www.youtube.com/watch?v=xvqH_ck-5Q8)
If you still don't want to run a Docker container, just run `pip install conan` on your machine and follow the steps I gave in the previous comment.

I have never tested the master before, I will do it tomorrow.

**Comment by ojwb** [comment] 2022-01-26 20:48
Closing as unreproducible.

**Closed by ojwb** 2022-01-26 20:48 UTC

**Comment by wsfulton** [comment] 2022-01-26 23:48
Looks like the problem is as @ojwb suspected, the https://github.com/matlo607/conan-swig/blob/master/conanfile.py is installing an old version: swig-3.0.12.
