### ISSUE TITLE
functions declared in a namespace

### ISSUE THREAD

**Issue by Guyiming** [swig/swig#2459] opened 2022-12-05 11:18 UTC
I have below c++ code:
```cpp
namespace AA
{
      namespace BB
      {
            void methodA();
      }
}
```
and the following interface file:
```
%module DataManager
//...
```
now swig generate the `methodA` in DataManager.cs file:
```csharp
namespace DataManagerSharp
{
    public class DataManager
    {
        public static void methodA()
        {
            DataManagerPINVOKE.methodA();
        }
    }
}
```
I want to know can swig convert the `BB` namespace to a C# class (I have read the document and `nspace` doesn't support), like this:
```csharp
namespace DataManagerSharp.AA
{
      public class BB
      {
           public static void methodA()
           {
               DataManagerPINVOKE.methodA();
           }
      }
}
```
or can I config where the global function or variables to generate in? (not the default cs file with module name).

**Comment by ojwb** [comment] 2022-12-06 03:18
I think this is essentially a duplicate of #591.

Really `%nspace` should provide a solution to this, but currently it doesn't - perhaps because it originated in SWIG/Java and in Java functions have to be in a class.

**Comment by ojwb** [comment] 2022-12-09 02:19
Yeah, that's a reasonable workaround.  Really `%nspace` should support this, but we have #591 for that so closing.

**Closed as completed by ojwb** 2022-12-09 02:19 UTC

**Comment by christophe-calmejane** [comment] 2023-05-09 09:07
> Thanks @ojwb . I solved it using `%rename`, works normal.

How did you manage to solve this with `%rename`?
Can you share an example for others?

**Comment by ojwb** [comment] 2023-05-09 19:35
Something like (untested):

```
%rename(foo) AA::BB::methodA();
%rename(bar) CC::DD::methodA();
%rename(baz) EE::FF::methodA();
```

**Comment by christophe-calmejane** [comment] 2023-05-10 07:14
Oh ok, I thought he was able to keep the same method name in the correct namespace using `%rename` (some sort of special syntax or something). Not what I need then, thanks :)
