### ISSUE TITLE
SWIG4 and php wrapper api file 

### ISSUE THREAD

**Issue by Alexufo** [swig/swig#2754] opened 2024-01-11 14:31 UTC
In SWIG3 we have a php file with an api wrapper. It was good for documentation and distribution. In SWIG4, the wrapper api php file is now unused.

How can we provide documentation for the wrapper? Maybe you know some tools.

**Comment by ojwb** [comment] 2024-01-11 18:57
I'm not sure what your really asking here.  Maybe it is the same issue raised in #2425?

Note you will still get a `.php` file generated if you use `%pragma(php) include=`[...] which might be useful to you depending what you're wanting (it won't contain any code, that's now all wrapped via PHP's C API but will contain the content you asked SWIG to include).

(Also, this actually changed in SWIG 4.1.0 rather than "swig4".)

**Comment by Alexufo** [comment] 2024-01-11 19:24
Yeah. That's exactly what I'm looking for

**Comment by ojwb** [comment] 2024-01-11 21:12
> Yeah. That's exactly what I'm looking for

Not sure which part "that" refers to, but closing as either a duplicate of #2425 or as being answered.

**Closed by ojwb** 2024-01-11 21:12 UTC
Labels: PHP

**Comment by Alexufo** [comment] 2024-01-16 09:21
issue 2425 helped me figure out where to go. I will have to make a stub file for the php extension myself.
