### ISSUE TITLE
Multiple compilation units per module?

### ISSUE THREAD

**Issue by paroj** [swig/swig#1782] opened 2020-04-21 10:09 UTC
we have a rather large swig module wrapping C++  code with many templates.
This causes resource depletion on various CI builders, as compiling that module requires several GB of RAM and lots of (single core) CPU time. See
https://github.com/OGRECave/ogre/issues/1546

Is there a way to let swig generate multiple cpp files per module, which would reduce peak RAM usage and distribute processing?

**Comment by jschueller** [comment] 2020-07-18 08:15
yes, you have to split it your .i files, and declare several modules, see openturns

**Comment by simonschmeisser** [comment] 2021-02-02 07:54
We tried following your advise but are not certain whether the API can be preserved while splitting (ie using the same python import commands afterwards)?

**Comment by jschueller** [comment] 2021-02-02 15:06
it can, with a pure Python meta-module that would import all the swig submodules

**Comment by ojwb** [comment] 2021-12-30 00:24
Answered question so closing.

**Closed by ojwb** 2021-12-30 00:24 UTC

**Comment by mmomtchev** [comment] 2023-07-26 16:21
@jschueller @ojwb This a Python-specific solution, what about other languages?

In fact, simply splitting the code into multiple compilation units, then linking them together in a single library is not difficult to implement, the problem is that with the current architecture, it will have to be implemented separately for every single generator. I wonder if there isn't a tool that could do this automatically from the `_wrap.cxx`?

**Comment by mmomtchev** [comment] 2023-10-14 15:10
I have started implementing this as part of SWIG Node-API for WASM. Compilation for WASM targets with `emscripten` has reached new previously unseen memory usage records and WASM won't be possible without this feature.

Initially only SWIG Node-API will support it and there is quite lots of tedious work necessary for each language generator in order to support it.
