### ISSUE TITLE
c++: const static vs static const in include file 

### ISSUE THREAD

**Issue by alex4747-pub** [swig/swig#2272] opened 2022-04-27 21:24 UTC
I creating python wrapper and my code includes .hpp file that that has const static class member declared as
```
const static int xxx;
```
It is flagged by swig-4.0.2 as Error: Syntax error in input(3)
If I change to
```
static const int xxx;
```
It does not have the problem

**Comment by ojwb** [comment] 2022-04-27 21:57
Closing as duplicate of #241.

**Closed by ojwb** 2022-04-27 21:57 UTC
