### ISSUE TITLE
shared_ptr for swig/go

### ISSUE THREAD

**Issue by tamama** [swig/swig#2030] opened 2021-05-29 10:46 UTC
shared_ptr for swig/go is broken

$ swig -version                                                                                                                                            │
                                                                                                                                                                           │
SWIG Version 4.0.2                                                                                                                                                         │
                                                                                                                                                                           │
Compiled with x86_64-conda_cos6-linux-gnu-c++ [x86_64-conda_cos6-linux-gnu]                                                                                                │
                                                                                                                                                                           │
Configured options: +pcre

**Comment by tamama** [comment] 2021-05-29 10:46
/mnt/vagrant/workspace/src/gitlab.com/tamama/tamama-exchangeconnectivity/tamama-exchangeconnectivity/image-dev/rootfs/var/workspace/application/src/main/cpp/pkg/model/appl│
ication/tamamaexchangeconnectivity/servicepolicy/.interface/swiggo/def/servicepolicy.go.i:8: Error: Unable to find 'std_shared_ptr.i'

**Comment by tamama** [comment] 2021-05-29 10:47
`%module "servicepolicy"

%{
#include <tamama/exchangeconnectivity/model/service/servicepolicy.hpp>
%}

%include <std_string.i>
%include <std_shared_ptr.i>
%include <tamama/exchangeconnectivity/model/service/servicepolicy.hpp>`

**Comment by tamama** [comment] 2021-05-29 10:49
Any idea of getting a quick wrapper for <std_shared_ptr.i> ?

Any hint would do.

Thanks in advance.

**Comment by wsfulton** [comment] 2021-06-20 08:52
I'm afraid that no-one has contributed support for `shared_ptr` for Go, but contributions are welcome.

**Comment by tamama** [comment] 2021-06-20 12:09
Per discussed, I am working on it.

**Comment by tamama** [comment] 2021-09-16 18:43
PR: https://github.com/swig/swig/pull/2041

**Comment by ojwb** [comment] 2022-02-09 21:10
The linked pull request was closed by the submitter before anyone got a chance to review it, but is incomplete anyway.

**Comment by tamama** [comment] 2022-02-09 22:08
Nope, this is sufficient to do the wrap. At least at that time.

Due to Swig inactivity, I decide to leave this behind for gRPC. <- That's the honest truth @ojwb

**Comment by tamama** [comment] 2022-02-09 22:16
+ We are already at Go 1.17, this version of Swig-Go is incompatible => this is unfortunate.

**Comment by ojwb** [comment] 2022-02-10 03:51
As wsfulton commented on the PR, there are no runtime tests added - we really need those for any new feature to ensure (a) it actually works and (b) to catch if a future change breaks it.

> We are already at Go 1.17, this version of Swig-Go is incompatible => this is unfortunate.

We have a CI build with Go 1.17 which seems to be passing the testsuite: https://github.com/swig/swig/runs/5131842949?check_suite_focus=true

If you're hitting a situation where SWIG isn't compatible with Go 1.17, please open a new issue with a reproducer.

**Closed** 2023-05-14 09:11 UTC
Labels: enhancement, Go
