### ISSUE TITLE
Lack of support for ingesting C++11 headers

### ISSUE THREAD

**Issue by jengelh** [swig/swig#814] opened 2016-10-11 16:10 UTC
```
%module t
%{
class A final {};
class B : public A {};
%}
class A final {};
class B : public A {};
```
```
$ swig -c++ -python t.i
t.i:4: Warning 401: Nothing known about base class 'A'. Ignored.
$ g++ 
t_wrap.cxx: In function ‘int Swig_var_final_set(PyObject*)’:
t_wrap.cxx:3134:7: error: ‘final’ was not declared in this scope
       final = *temp;
```
swig-3.0.10 claims it knows nothing about class A, it misses the opportunity to point out that derivation is not even permitted, and generates a cxx code file which does not compile because it took `final` to be the class name.

**Comment by ojwb** [comment] 2016-10-12 01:23
Duplicate of #672.

SWIG supports a significant amount of C++11, but not the `final` keyword for classes yet.

**Closed by ojwb** 2016-10-12 01:23 UTC
