### ISSUE TITLE
Compile failure for %typemap(in) const std::string & (std::string temp)

### ISSUE THREAD

**Issue by kchen** [swig/swig#806] opened 2016-10-03 23:36 UTC
The foo_wrap.cxx file fails to compile with the following file (tested with swig-3.0.10):
```c
%module foo

%include "std_string.i"

%typemap(in) const std::string & (std::string temp) {
    temp = "foo";
    $1 = &temp;
}

%include "foo.h"
```

foo.h is:
```c
#include <string>
void asdf(const std::string& baz) {}
```

If I remove '%include "std_string.i"' or the const keywords above, the file does compile.  The compilation error occurs because res1 is not defined below:
```c
SWIGINTERN PyObject *_wrap_asdf(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  std::string *arg1 = 0 ;
  std::string temp1 ;
  PyObject * obj0 = 0 ;
  
  if (!PyArg_ParseTuple(args,(char *)"O:asdf",&obj0)) SWIG_fail;
  {
    temp1 = "foo";
    arg1 = &temp1;
  }
  asdf((std::string const &)*arg1);
  resultobj = SWIG_Py_Void();
  if (SWIG_IsNewObj(res1)) delete arg1;
  return resultobj;
fail:
  if (SWIG_IsNewObj(res1)) delete arg1;
  return NULL;
}
```

**Comment by ojwb** [comment] 2016-10-10 20:38
The problem here is you're including the standard typemaps for `std::string` and then just overriding one of them.  So you still get the standard `freearg` typemap, but that relies on the `res$argnum` variable having been declared by the corresponding `in` typemap.

So either don't `%include "std_string.i`, or specify a replacement `freearg` typemap too (in this case, it can just have an empty value).

Removing `const` means the you get a different typemap set, as the value of a parameter passed by non-const reference may be modified by the function, and that value needs to then be propagated back to Python.

I'd say this is a usage error not a bug, so closing.

**Closed by ojwb** 2016-10-10 20:38 UTC
