### ISSUE TITLE
varargs missing in the python wrapper source

### ISSUE THREAD

**Issue by JensMunkHansen** [swig/swig#1076] opened 2017-08-25 10:40 UTC
A function with prototype 

`int RwParamSet(int fsel, const float* iMultiData, size_t nDim, ...);`

is wrapped as:

`
    def RwFloatParamSet(self, fsel, iMultiData):
        return _example.A_RwFloatParamSet(self, fsel, iMultiData)
`
The parameter nDim and varargs are ignored. It was working well in version 3.0.8, but in 3.0.10 the error is introduced.

Before in version 3.0.8 it was wrapped as

 `def RwFloatParamSet(self, *args): return _swig_fnm.ApertureFloat_RwFloatParamSet(self, *args)`

which is `correct.

Regards
Jens Munk

**Comment by ojwb** [comment] 2017-08-28 03:15
The information provided seems to be inconsistent (`RwParamSet` vs `RwFloatParamSet`) - I wonder if that explains the missing `nDim`, as creating a simple example out of the given prototype the varargs are indeed not accessible but `nDim` is there.

However, I also seem to get the same wrapping with 3.0.8, so I can't bisect to find what broke this...

Please can you provide a complete self-contained example (including the SWIG command line used to process it).

**Comment by JensMunkHansen** [comment] 2017-08-28 23:20
I will provide a complete example tomorrow. There is definitely an issue. I
have fixed it locally by extending my class with python code to correctly
wrap the function.

Till later
Jens

**Comment by JensMunkHansen** [comment] 2017-08-29 18:05
Hi again.

I have attached an example, which demonstrates how functions with varargs results in a wrong python wrapper file.

My workaround now is to use `sed` after running SWIG

Kind Regards
Jens


[varargs2.zip](https://github.com/swig/swig/files/1261207/varargs2.zip)

**Comment by ojwb** [comment] 2021-12-30 21:59
Looking at the example, you have a custom `in` typemap which says to wrap multiple C++ parameters as a single parameter in Python:

```
%typemap(in) (const float* iMultiData, size_t nDim, ...) (PyArrayObject* array=NULL, int is_new_object=0, size_t vargs[3]) {
  // Some code
}
```

So there's no `nDim` parameter in the Python wrapper because you've explicitly told SWIG to do that!

Not a bug, so closing.

**Closed by ojwb** 2021-12-30 21:59 UTC
Labels: Python
