### ISSUE TITLE
[SCILAB] Compilation failure on windows when using the MinGW compiler

### ISSUE THREAD

**Issue by ibell** [swig/swig#332] opened 2015-02-09 22:29 UTC
On windows, when trying to compile an extension using MinGW, I get the following include error:

```
[ 93%] Building CXX object CMakeFiles/XXXXXXXXX.dir/XXXXXXXSCILAB_wrap.cxx.obj
In file included from C:/TDM-GCC-64/x86_64-w64-mingw32/include/stdlib.h:668:0,
                 from C:/PROGRA~1/scilab-5.5.1/modules/core/includes/core_math.h:19,
                 from C:/PROGRA~1/scilab-5.5.1/modules/core/includes/stack-c.h:29,
                 from C:/PROGRA~1/scilab-5.5.1/modules/api_scilab/includes/api_scilab.h:35,
                 from C:\Users\ihb\Desktop\912FILES\build\scilab\XXXXXXXXXXXXSCILAB_wrap.cxx:750:
C:/PROGRA~1/scilab-5.5.1/modules/core/includes/malloc.h:24:40: fatal error: sci_mem_alloc.h: No such file or directory
 #include "sci_mem_alloc.h" /* MALLOC */
```

Seems scilab on windows is missing this header, I searched and it is not included in the version 5.5.1 release.

**Comment by ibell** [comment] 2015-02-09 22:41
I found it here: http://gitweb.scilab.org/?p=scilab.git;a=blob;f=scilab/modules/core/includes/sci_mem_alloc.h;h=e025cc557ef3579dba77da6127ccbf2d499d2b40;hb=master

**Comment by ibell** [comment] 2015-02-09 22:43
When I add that header to ${SCILABROOT}/modules/core/includes, I now get different compiler error:

```
C:\Users\ihb\Desktop\912FILES\build\scilab\REFPROPSCILAB_wrap.cxx: In function 'int SWIG_this(char*, long unsigned int)':
C:\Users\ihb\Desktop\912FILES\build\scilab\REFPROPSCILAB_wrap.cxx:1016:34: error: cast from 'void*' to 'long unsigned int' loses precision [-fpermissive]
         (double) (unsigned long) ptrValue));
                                  ^
C:\Users\ihb\Desktop\XXXFILES\build\scilab\XXXXXXXXXSCILAB_wrap.cxx: In function 'int SWIG_ptr(char*, long unsigned int)':
C:\Users\ihb\Desktop\XXXFILES\build\scilab\XXXXXXXXXSCILAB_wrap.cxx:1046:69: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       SwigScilabPtrFromObject(pvApiCtx, 1, (void *) (unsigned long) dValue, NULL, 0));
                                                                     ^
```

**Comment by ojwb** [comment] 2015-02-10 00:38
If you look carefully at the stack of inclusions in your original report they show that scilab has a header named `malloc.h` which is getting included from the system `stdlib.h` instead of the system `malloc.h`.

It would be safer for scilab not to use a header name which collides with a system header on one platform, though I'd expect with a suitably set compiler include path it would work.  Either way, that's not a problem caused by SWIG AFAICS.

The error and warning in your most recent comment look to be due to an incorrect assumption in SWIG's scilab backend that `sizeof(unsigned long) >= sizeof(void*)` - that's true on most platforms, but isn't true on 64-bit Windows:

 http://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

**Comment by ibell** [comment] 2015-02-10 00:58
Yes, this seems like a bug in the swig+scilab implementation.

When I set the ``-fpermissive`` compiler flag, compilation is successful, but I have pages of linker errors.  It's like I need to link with a scilab library, but I have no idea which one.

**Comment by ibell** [comment] 2015-02-10 00:59
Should it just be a ``std::size_t`` cast?

**Comment by ojwb** [comment] 2015-02-10 01:28
`size_t` can be smaller than the size of a pointer (e.g. with a segmented memory model like MSDOS used to have), though I suspect in practice it's the right size on modern systems.

The correct standard unsigned integer type capable of holding a pointer value is `uintptr_t`, but that requires C99 or C++11.

I'm not sure if we have a generic solution for what type to use for such situations in SWIG.

**Comment by ibell** [comment] 2015-02-10 01:34
A pity that the scilab folks have not done any testing on platforms aside from linux.  These windows problems are pretty obvious.

**Comment by ojwb** [comment] 2015-02-10 04:15
I don't think it's reasonable to expect people to test on proprietary platforms.  If I was expected to give money to Microsoft in order to contribute to SWIG development, then I wouldn't contribute to SWIG development.  People who care about such platforms can contribute compatibility patches.

While I don't know what platforms the scilab support was tested on, the current code should actually be OK almost everywhere except 64-bit Windows - notably 32-bit Windows has `sizeof(long) == sizeof(void*)`.

**Comment by ibell** [comment] 2015-02-10 06:46
OSX doesn't work either (or rather, didn't): #273.  I haven't tested it recently, but I certainly can try again.

For me, the vast majority of my users are windows, so if I want them to be able to use my code, windows it is.

**Comment by wsfulton** [comment] 2015-02-12 21:55
Yesterday I merged in a whole lot of C90 fixes for many languages which will help ensuring compilation on other platforms, notably Visual Studio C code. For Scilab I fixed a few problems, but there are a number of compile problems remaining when wrapping STL containers which I'd like @smarchetto to look at. @ibell,  you may find that it is a whole lot better now. Support for Windows will only come about if someone like you is prepared to test it and provide patches.

**Comment by ibell** [comment] 2015-02-12 21:57
Testing I can do, patching might be a bit trickier.  My free time is booked
pretty solid right now.

**Comment by smarchetto** [comment] 2015-02-13 16:22
Pushed a first patch (unsigned long compilation issue). I decided to not support half Windows. For me it needs all the tests (and also a few business case applications) to run before we can say it works on Windows. It will need some work, but I am on it very soon.

**Comment by ibell** [comment] 2015-02-13 16:26
While you are fixing things on windows, can you please fix the include
directory?  On linux and OSX there is a single include folder in scilab,
and on windows, you have to manually and painfully add include directories
to the compilation since all the headers are hiding in subfolders of
modules/core/includes, modules/api_scilab/includes, etc.  I had to add
something like 12 include directories, and this is clearly something that
is not ideal

**Comment by smarchetto** [comment] 2015-02-13 16:28
I totally agree with you on this point and I will fix that first.

**Comment by wsfulton** [comment] 2015-02-14 00:58
I'm afraid that 4b2ccd2892b63b63e3ed1f3dda82f851f29bc41d will actually make things worse on windows as stdint.h is not available prior to Visual Studio 2012. SWIG aims to generate C90 compatible code and stdint.h is C99.

**Comment by ojwb** [comment] 2015-02-14 03:58
Looking at 4b2ccd2, we could just use `unsigned long long` - the main downside is it is excessively wide on some platforms.  It's not actually standardised in C90, but seems to be supported pretty much universally - e.g. "Visual Studio .NET 2003" had it:

https://msdn.microsoft.com/en-us/library/s3f49ktz%28v=vs.71%29.aspx

The compiler should be able to see that the extra width of the intermediate type wasn't needed in the uses here and generate the same code whether `unsigned long long` or `uintptr_t` is used.  
Testing pointer -> double, I find clang 3.5 does, but GCC 4.9 doesn't.

Testing double -> pointer, GCC again doesn't seem to do well, while clang produces different code in each case, but I can't easily tell if either is better.

The main downside I can see is compiler warnings on architectures where `unsigned long long` is unnecessarily wide, such as:

```
warning: cast to pointer from integer of different size
```

**Comment by ojwb** [comment] 2022-01-25 01:41
4b2ccd2892b63b63e3ed1f3dda82f851f29bc41d fixed the case to use `uintptr_t`.  The other issues discussed here don't seem to be related to SWIG.  Hopefully they've been fixed in scilab since, but if they haven't that's an issue to open with scilab rather than for us to track.

**Closed by ojwb** 2022-01-25 01:41 UTC
Labels: Scilab
