### ISSUE TITLE
Issue with "%typemap(in) const char *const *" not being detected in one place

### ISSUE THREAD

**Issue by cminyard** [swig/swig#2655] opened 2023-07-18 22:08 UTC
I'm having an issue with a typemap not being seen where it should be.  I've been trying to get a small reproducer, but I haven't been able to make something small. have the following code, which sort of reproduces it:
```
%module(directors="1") test1

%{

#define PI_StringCheck PyUnicode_Check
#define PI_AsString PyUnicode_AsUTF8
static int
PI_TupleToStringArray(char ***out, PyObject *so)
{
    unsigned int i;
    unsigned int len;
    char **temp = NULL;

    if (so == Py_None)
	goto null_auxdata;

    if (!PySequence_Check(so)) {
	PyErr_SetString(PyExc_TypeError, "Expecting a sequence");
	return -1;
    }
    len = PyObject_Length(so);
    if (len == 0)
	goto null_auxdata;

    temp = (char **) malloc(sizeof(char *) * (len + 1));
    if (!temp) {
	PyErr_SetString(PyExc_ValueError, "Out of memory");
	return -1;
    }
    memset(temp, 0, sizeof(char *) * (len + 1));
    for (i = 0; i < len; i++) {
	PyObject *o = PySequence_GetItem(so, i);

	if (!PI_StringCheck(o)) {
	    Py_XDECREF(o);
	    PyErr_SetString(PyExc_ValueError,
			    "Expecting a sequence of strings");
	    for (; i > 0; i--)
		Py_XDECREF(temp[i - 1]);
	    free(temp);
	    return -1;
	}
	temp[i] = (char *) PI_AsString(o);
	Py_DECREF(o);
    }
 null_auxdata:
    *out = temp;
    return 0;
}


class MDNS_Service {
};

MDNS_Service *test1(int interfacenum, const char *const *txt)
{
    return new MDNS_Service();
}
    
const char *prog1(const char *const *txt)
{
    return txt[0];
}

%}
    
class MDNS_Service {
};

%typemap(in) const char *const * {
    if (PI_TupleToStringArray(&$1, $input) == -1)
	SWIG_fail;
}

const char *prog1(const char *const *txt);

%extend MDNS_Service {
    MDNS_Service(int interfacenum, int ipdomain,
		 char *name, char *type, char *domain, char *host,
		 int port, const char *const *txt) {
	MDNS_Service *s = test1(interfacenum, txt);
	return s;
    }
}
```
with the following program to use it:
```
import test1

print(test1.prog1(("one", "two")))
a = test1.MDNS_Service(0, 0, "Hello", "There", "Swig", "Generator", 10,
                       ("one", "two"))
```
Compile with:
```
swig -python -o test1_wrap.cc -c++ test1.i
g++ -g -fPIC --share -o _test1.so -I /usr/include/python3.10 test1_wrap.cc
```
and if I run it:
```
~/t1/swig$ python3 run.py 
one
Traceback (most recent call last):
  File "/home/cminyard/t1/swig/run.py", line 4, in <module>
    a = test1.MDNS_Service(0, 0, "Hello", "There", "Swig", "Generator", 10,
  File "/home/cminyard/t1/swig/test1.py", line 68, in __init__
    _test1.MDNS_Service_swiginit(self, _test1.new_MDNS_Service(interfacenum, ipdomain, name, type, domain, host, port, txt))
TypeError: in method 'new_MDNS_Service', argument 8 of type 'char const *const *'
```
swig properly handles the "prog1" function, but for some reason doesn't see the "const char *const *" in the MDNS_Service method and just uses the standard type for it.  That's the error I'm seeing in the program I'm using, but it doesn't seem to be quite the same issue.

If I move the class definition of MDNS_Service seen by swig to below the typemap, the above works ok.  So the class definition needs to be after all the typemaps?  I'd be ok with that, though it's a little confusing.  However, in the program that I'm working on, I have verified (with the -E option) that there is no reference to MDNS_Service before type typemap.  In fact, I moved the typemap to the first thing right after the %module directive and it still has the issue.

I can't see what I am doing wrong here.

Oh, I am using the end of the git tree (I started with something around 4.1, I think, same issue).

-corey

**Comment by ojwb** [comment] 2023-07-21 00:01
> So the class definition needs to be after all the typemaps?

See "14.2.2 Typemap scope" in the manual which even includes an explicit example of the situation with `%extend` you've observed:

_Once defined, a typemap remains in effect for all of the declarations that follow.  A typemap may be redefined for different sections of an input file.  For example:_

```
// typemap1
%typemap(in) int {                                                              
...  
}                                                                               
                                                                                
int fact(int);                    // typemap1                                   
int gcd(int x, int y);            // typemap1                                   
                                                                                
// typemap2                                                                     
%typemap(in) int {                                                              
...                                                                             
}
 
int isprime(int);                 // typemap2
```

_One exception to the typemap scoping rules pertains to the <tt>%extend</tt> declaration.  <tt>%extend</tt> is used to attach new declarations to a class or structure definition.  Because of this, all of the declarations in an <tt>%extend</tt> block are subject to the typemap rules that are in effect at the point where the class itself is defined.  For example:_ 

```
class Foo {                                                                     
  ...                                                                           
};

%typemap(in) int {
 ...
}

%extend Foo {
  int blah(int x);    // typemap has no effect.  Declaration is attached to Foo which
                      // appears before the %typemap declaration.
};
```

As a rule of thumb, just define all your typemaps first unless you are wanting to control what they're applied the first example in the manual.

I think we really need a way to reproduce the original issue.  There are some tips on debugging typemap matching in the manual which may help.

**Comment by ojwb** [comment] 2024-01-09 03:37
There's no bug here and no updates for ~6 months so closing.  Please open a new ticket if you find a reproducer for your problem.

**Closed by ojwb** 2024-01-09 03:37 UTC
