### ISSUE TITLE
(JS/Node/V8) C++ exceptions are not propagated within functions that support multiple arguments

### ISSUE THREAD

**Issue by dwhitney67** [swig/swig#2451] opened 2022-11-26 17:14 UTC
I am using SWIG 4.0.2 to generate a JavaScript binding from a C++ API. The code that is generated does not propagate a C++ exception, in particular when a function supports multiple arguments. For example, examine this generated code:

```c++
static SwigV8ReturnValue _wrap_Config__wrap_Config_getBooleanValue(const SwigV8Arguments &args) {
  SWIGV8_HANDLESCOPE();

  v8::Handle<v8::Value> jsresult;
  OverloadErrorHandler errorHandler;

  if(args.Length() == 1) {
    errorHandler.err.Clear();
#if (V8_MAJOR_VERSION-0) < 4 && (SWIG_V8_VERSION < 0x031903)
    jsresult = _wrap_Config_getBooleanValue__SWIG_0(args, errorHandler);
    if(errorHandler.err.IsEmpty()) {
      SWIGV8_ESCAPE(jsresult);
    }
#else
    _wrap_Config_getBooleanValue__SWIG_0(args, errorHandler);
    if(errorHandler.err.IsEmpty()) {
      return;
    }
#endif
  }

  if(args.Length() == 2) {
...
```

If only one argument is provided to the function, and an error (exception) occurs, then the code attempts to check if two arguments have been provided, and if not, then an error is thrown indicating "Illegal arguments for the function getBooleanValue".

This is **not** the desired behavior. Ideally if an error occurs, then a SWIG exception should be thrown. For example:

`
   _wrap_Config_getBooleanValue__SWIG_0(args, errorHandler);
    if(errorHandler.err.IsEmpty()) {
      return;
    }
    **else {
      SWIG_exception_fail(SWIG_ERROR, "This is not good");   // Ideally the error message should come from errorHandler.err
    }**
    ...
`

**Comment by wsfulton** [comment] 2022-11-26 18:14
Are you not using %exception? Not really related to this issue, but note that swig-4.1.0 has a LOT of fixes for Javascript.

**Comment by ojwb** [comment] 2022-11-28 04:06
This looks like a duplicate of #772 to me.

**Comment by dwhitney67** [comment] 2022-11-28 11:38
I upgraded to SWIG 4.1.0 and the newly generated code still contains the same poor assumptions as before (albeit the legacy code has been removed).

My function should be able to handle 1 or 2 arguments. Anything less or more should return an error such as "Illegal arguments for function XYZ".

In the case where a valid number of arguments (say 1) is provided, if the function being called returns an error, that should be the end of it. The SWIG generated code should *not* dismiss the error and try the next case where 2 arguments are expected. 

```
  if(args.Length() == 1) {
    errorHandler.err.Clear();
    _wrap_Config_getIntegerValue__SWIG_0(args, errorHandler);
    if(errorHandler.err.IsEmpty()) {
      return;
    }
    else {
      // propagate the error!
    }
  }

```

**Comment by ojwb** [comment] 2022-11-28 17:28
>>This looks like a duplicate of https://github.com/swig/swig/issues/772 to me.
>
>It pretty much is.

Closing this as a duplicate then - please continue discussion in the existing ticket.

> A problem that was identified 5 years ago seems to have been summarily dismissed, and yet still exists in SWIG 4.0.2.

I'm not sure why you think it was "summarily dismissed" - e.g. I explicitly say "The dispatch here looks wrong to me.

I did close a related much older PR as the proposed changes broke the testsuite and the submitter hadn't responded to review comments for 5 years even back then.  A key point there was that the proposed change was clearly not right (the branch is called `patch-1` which suggests it was created via the github editor rather than by actually checking out the code, so likely the submitter never even tried to build SWIG with their proposed change).

Nobody has attempted to fix this since, but I'm afraid those are simply the development realities of a volunteer project.  SWIG sadly has a lot of bugs which were reported multiple years ago and are still present (and we're certainly not unique - look at the bug tracker for any volunteer project with a substantial userbase and you're likely to see such bugs unless they auto-close unfixed bugs over a certain age).

We try to do our best but if you really need something doing to any particular timescale, you may need to either do it yourself or try to find someone to fund to do the work (to be clear: not an attempt to by me to get paid to do this - if I had the right skills for this I'd likely have done it by now).

**Closed by ojwb** 2022-11-28 17:28 UTC
Labels: Javascript
