### ISSUE TITLE
Perl test director_classes fails

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1167] opened 2017-11-30 11:58 UTC
I tried to build the latest version of SWIG from git (069ce1f6e), but the one of Perl tests failed. The error is below.
I used Fedora Rawhide (devel version) which contains Perl 5.26.1.

Complete build logs can be found here:
https://koji.fedoraproject.org/koji/taskinfo?taskID=23467767

```
checking perl5 testcase director_classes (with run test)
director_classes_wrap.cxx: In member function 'virtual DoubleHolder* const& SwigDirector_Derived::ConstPtrRef(DoubleHolder* const&)':
director_classes_wrap.cxx:2955:35: warning: function may return address of local variable [-Wreturn-local-addr]
   return (DoubleHolder *const &) *c_result;
                                   ^~~~~~~~
director_classes_wrap.cxx:2923:9: note: declared here
   void *swig_argp ;
         ^~~~~~~~~
director_classes_wrap.cxx: In member function 'virtual DoubleHolder* const& SwigDirector_Base::ConstPtrRef(DoubleHolder* const&)':
director_classes_wrap.cxx:2569:35: warning: function may return address of local variable [-Wreturn-local-addr]
   return (DoubleHolder *const &) *c_result;
                                   ^~~~~~~~
director_classes_wrap.cxx:2537:9: note: declared here
   void *swig_argp ;
         ^~~~~~~~~
SWIG Perl test failed: 
1..32
ok 1 - use director_classes;
ok 2 - require director_classes;
ok 3 - Base.Val
ok 4 - Base.Ref
ok 5 - Base.Ptr
ok 6 - Base.ConstPtrRef
ok 7 - Base.FullyOverloaded(int)
ok 8 - Base.FullyOverloaded(bool)
ok 9 - Base.SemiOverloaded(int)
ok 10 - Base.SemiOverloaded(bool)
ok 11 - Base.DefaultParms(int, double)
ok 12 - Base.DefaultParms(int)
ok 13 - Derived.Val
ok 14 - Derived.Ref
ok 15 - Derived.Ptr
ok 16 - Derived.ConstPtrRef
ok 17 - Derived.FullyOverloaded(int)
ok 18 - Derived.FullyOverloaded(bool)
ok 19 - Derived.SemiOverloaded(int)
ok 20 - Derived.SemiOverloaded(bool)
ok 21 - Derived.DefaultParms(int, double)
ok 22 - Derived.DefaultParms(int)
ok 23 - PerlDerived.Val
ok 24 - PerlDerived.Ref
ok 25 - PerlDerived.Ptr
make[1]: *** [Makefile:37: director_classes.cpptest] Error 255
checking perl5 testcase director_classic (with run test)
```

**Comment by wsfulton** [comment] 2017-12-01 07:56
@tlby would you be able to investigate this please?

**Comment by tlby** [comment] 2017-12-01 21:00
Thanks.  Yes, I will look into it.

**Comment by tlby** [comment] 2017-12-02 19:26
I can reproduce a segfault in the runtime tests on `Fedora release 27` using `gcc version 7.2.1 20170915 (RedHat 7.2.1-2) (GCC)`.  What I know so far is that the wrappers generated for Perl in this case are in close alignment with the Python wrappers for this code, however director_classes.i does not have runtime tests in Python.  I haven't tested this, but I'm fairly certain Python would experience this problem as well.  The runtime tests were adapted from Java, but its runtime test is passing.  The hunt continues.

**Comment by tlby** [comment] 2017-12-05 00:05
For building the examples and test cases, we borrow compiler flags from the build of perl itself (shared via the Config module).  While trying to get saner traces out of gdb I stumbled across the fact that without `-O2` this code runs correctly in `Fedora release 27`.

I think the reason we're asking for perl's CCFLAGS is to pick up `-I` and `-D` flags.  I don't think there's a compelling reason to borrow it's optimization and warning levels.  It's not _supposed_ to matter, but here we are.  @wsfulton does this make sense?

**Comment by ojwb** [comment] 2017-12-05 03:38
It's problematic to be generating code that can't be safely compiled with `-O2` as that's the optimisation level generally used with GCC, and without any optimisation the generated code quality is rather poor.  Avoiding picking up `-O2` from Perl in our configure will avoid the problem in our test suite, but doesn't actually solve the underlying issue.

Optimisation breaking something makes me suspect that the code is invoking undefined behaviour currently (because compiler optimisers generally optimise on the basis that it's fine to change what code invoking undefined behaviour does).

The warning sound worrying, so I added this code to the `DoubleHolder *const &SwigDirector_Base::ConstPtrRef(DoubleHolder *const &cprx) {` function:

```
  fprintf(stderr, "\n%p\n", (*c_result));
  fprintf(stderr, "%p\n", (swig_argp));
  fprintf(stderr, "%p\n", (&swig_argp));
```

The output from this is:

```
0x5641014f37b0
0x5641014f37b0
0x7ffd63d9cf48
```

We're returning `*c_result` (cast to a different type, but that won't change the pointer value on Linux at least) which the output above shows is the same as `swig_argp`.  So it looks to me like the warning is wrong (we're returning the value of `swig_argp`, not a pointer to it) or I'm misunderstanding what it's trying to tell us.

Neither valgrind nor ubsan picked up anything though.  And adding `-fno-strict-aliasing` doesn't make the tests pass, which suggests it's not an aliasing violation.

**Comment by wsfulton** [comment] 2017-12-05 08:00
Removing -O2 is a just a workaround and not really an acceptable solution unless we can show the assembly code that the compiler is generating is wrong. Probably the new environment is exposing a bug in the generated code and so unfortunately it means more digging to find it.

But I think it is clear what the problem is from the warnings generated. The generated code in Java deals with this correctly by using a static variable:
```c++
DoubleHolder *const &SwigDirector_Base::ConstPtrRef(DoubleHolder *const &cprx) {
  static DoubleHolder * result_default ;
  DoubleHolder ** c_result ;
  ...
  result_default = SwigValueInit< DoubleHolder * >();
  c_result = &result_default;
  ...
  return (DoubleHolder *const &)*c_result;
}
```
whereas in Perl and the other languages, the pattern does return a reference to a local variable:
```c++
DoubleHolder *const &SwigDirector_Base::ConstPtrRef(DoubleHolder *const &cprx) {
  DoubleHolder **c_result = 0 ;
  void *swig_argp ;
  ... swig_argp is assigned ...
  c_result = reinterpret_cast< DoubleHolder ** >(&swig_argp);
  ...
  return (DoubleHolder *const &) *c_result;
}
```
Could you try manually patching the source code with the same approach of using a static variable and see if that fixes it? If so, I can extend this Java approach to all languages.

**Comment by tlby** [comment] 2017-12-05 18:33
Thanks for looking a bit deeper at this, making `c_result` static does fix crash in that environment.  My understanding of c++ references is pretty shallow, however are you sure it's not `swig_argp` that needs to survive the function call?  Making that variable static instead of `c_result` _also_ fixes the crash.  Either one being static suppresses the "function may return address of local variable" warning, which I find confusing.

**Comment by ojwb** [comment] 2017-12-05 20:32
Oh, I'd missed the `&` at the end of the return type, so we are indeed returning a reference to an object which goes out of scope.

@tlby William doesn't explicitly say which variable to make static AFAICS, but comparing the code with the Java code he quoted it looks to me like Perl's `swig_argp` corresponds to Java's `result_default` (`c_result` is equivalent in each) so I think it's `swig_argp` he's proposing to make `static`.

**Comment by tlby** [comment] 2017-12-05 21:35
@ojwb thanks!  Hmm, it appears to be more complicated than:
```diff
diff --git a/Lib/typemaps/swigtype.swg b/Lib/typemaps/swigtype.swg
index be68421..0f50d6f 100644
--- a/Lib/typemaps/swigtype.swg
+++ b/Lib/typemaps/swigtype.swg
@@ -466,7 +466,7 @@
 }
 
 %typemap(directorout,noblock=1,warning=SWIGWARN_TYPEMAP_DIRECTOROUT_PTR_MSG) 
-  SWIGTYPE *const&(void *swig_argp, int swig_res, swig_owntype own) {
+  SWIGTYPE *const&(static void *swig_argp, int swig_res, swig_owntype own) {
   swig_res = SWIG_ConvertPtrAndOwn($input, &swig_argp, $*descriptor, %convertpt
   if (!SWIG_IsOK(swig_res)) {
     %dirout_fail(swig_res,"$type");
```
but that typemap appears to be where this pattern is coming from.

**Comment by wsfulton** [comment] 2017-12-07 08:08
I can replicate the warnings and the test failure on my box which uses older versions of everything by adding -O2:
```bash
~/swig/github/swig/Examples/test-suite/perl5 (master=)$ make CXXFLAGS="-Wall -Wextra -Wno-unused-parameter -O2" CXX=g++ director_classes.cpptest
```
I'll port the changes from Java to fix.

**Comment by tlby** [comment] 2017-12-07 20:52
@wsfulton, Great, thank you.  I stumbled across a different problem porting the debug statements from the Java run test.  Director methods see a $self object exposed without a proxy, which is wrong.  I'll try to nail that one down.

**Closed** 2017-12-14 07:56 UTC
Labels: Perl

**Comment by wsfulton** [comment] 2017-12-14 08:06
@tlby, I suggest you raise another issue for the $self problem.

I've fixed this now, see the two commits above. It is actually a problem in all the languages supporting directors. The setting of a default is only peculiar to the statically typed languages like Java so was a red herring. The solution is to create a copy of the pointer on the heap as follows:
```c++
DoubleHolder *const &SwigDirector_Derived::ConstPtrRef(DoubleHolder *const &cprx) {
  DoubleHolder **c_result = 0 ;
  void *swig_argp ;
  ... swig_argp is assigned ...
  DoubleHolder ** swig_temp = new DoubleHolder *((DoubleHolder *)swig_argp);
  swig_acquire_ownership(swig_temp);
  c_result = swig_temp;
  ...
  return (DoubleHolder *const &) *c_result;
}
```
instead of:
```c++
DoubleHolder *const &SwigDirector_Base::ConstPtrRef(DoubleHolder *const &cprx) {
  DoubleHolder **c_result = 0 ;
  void *swig_argp ;
  ... swig_argp is assigned ...
  c_result = reinterpret_cast< DoubleHolder ** >(&swig_argp);
  swig_acquire_ownership_obj(SWIG_as_voidptr(c_result), own /* & TODO: SWIG_POINTER_OWN */);
  ...
  return (DoubleHolder *const &) *c_result;
}
```
There is some code which deletes the pointer created on the heap when `swig_release_ownership` is called. @tlby, I added in support for the missing 'directorfree' typemap in Perl for this, but was not sure how to implement `SWIG_AcquirePtr`. Perhaps you could look at that when you have some time? It only seems to be called from 'directorfree' when returning objects by reference, not primitive types by reference and it didn't seem right for this case of pointers by reference either.

The statically typed languages take a different approach to the `swig_acquire_ownership` and `swig_release_ownership` which creates objects on the heap and instead it uses a thread-unsafe static to hold the type being returned by reference.

**Comment by tlby** [comment] 2017-12-14 17:25
@wsfulton, nice work!  I will investigate `SWIG_Perl_AcquirePtr`.  Thanks for the help here.
