### ISSUE TITLE
Support new/current v8 api

### ISSUE THREAD

**Issue by hmic** [swig/swig#804] opened 2016-10-01 20:41 UTC
Using the windows precompiled swig-3.0.10 I'm seeing multiple errors like
"error C2039: 'WeakCallbackData': is not a member of 'v8'"
or
"error C2660: 'v8::PersistentBasev8::Object::SetWeak': function does not take 2 arguments"
and 
"error C2039: 'GetHiddenValue': is not a member of 'v8::Object'"
when compiling a "swig -c++ -javascript -node" generated wrapper.
Looks like the v8 implementation support of swig stops somewhere before 5.0, because these functions got deprecated and removed back then...

Is nobody using the node and v8 support or am I doing something wrong here?

If so/not, would somebody be interested in upgrading/implementing support for (up to) the current v8 5.3 api? I'm considering me quite novice in C++, but I'd try to help if guided...

**Comment by ojwb** [comment] 2016-10-02 21:19
We don't seem to have a very active maintainer for SWIG's Javascript support, but people are clearly at least trying to use it, as we're getting issues and PRs filed:

https://github.com/swig/swig/labels/Javascript

Generally clean patches with regression tests get applied, patches with unclear intent or implementation and/or without any test coverage don't because maintainers without Javascript expertise don't feel comfortable that merging them does more good than harm.

**Comment by hmic** [comment] 2016-10-06 16:06
What about dropping the custom v8 versions support code and use/require NaN instead? This would provice a much broader support for current and upcoming v8 and node.js versions...

https://github.com/nodejs/nan

**Comment by ojwb** [comment] 2016-10-06 16:30
I know next to nothing about all this, but if someone's prepared to step in as SWIG's javascript backend maintainer and thinks that's the way to go, I've no objection personally.

**Comment by ojwb** [comment] 2016-12-07 23:12
From #825:
> Swig wrapper code makes use of WeakCallbackData which has been deprecated and is now removed in node v7.0.0. I think we have to move to WeakCallbackInfo instead, but I didn't look into it further.

**Comment by SlickWish** [comment] 2017-01-12 19:42
I used the branch here : https://github.com/arfoll/swig/tree/node7 as a guide and created my own patch. I haven't tested it extensively, but it seems to work. A long term solution would be to switch NaN.

Unfortunately, I also did the shared_ptr patch for 2014 within the same branch fixing the conflicts to bring it to 3.0.12 and the changes are mixed together.

**Comment by arfoll** [comment] 2017-04-04 06:40
@SlickWish you say you have your own patch based on my branch/fork? Would you mind submitting it to the fork as a PR so I could take a look?

**Comment by SlickWish** [comment] 2017-04-05 18:40
I will try to have it up soon.

**Comment by tomleavy** [comment] 2017-04-07 02:11
@SlickWish I noticed your commit and cherry picked it into my fork. I found one issue by checking IsEmpty and not also IsNull and IsUndefined in the GetModule function. I patched that and it seems to be working properly now on Node 7.8.0

**Comment by p2k** [comment] 2017-04-13 13:13
I'd like to chip in as well. I've adopted your changes and resolved the remaining issues. Works fine now on Node 7.9.0 without leaks.

**Comment by SlickWish** [comment] 2017-04-13 15:03
I notice that your code targets 5.4 v8 and perhaps it should be 5.2 v8.

**Comment by p2k** [comment] 2017-04-13 15:35
My bad, it's hard to keep proper track of V8 changes. I'm going to double check which parts are 5.4 specific.

**Comment by SlickWish** [comment] 2017-04-13 15:43
Well, 5.2 is only applicable to Electron. 6.x is 5.1 and 7.x is 5.4+

Electron is node 6.5

**Comment by tomleavy** [comment] 2017-04-13 16:07
@SlickWish for sure it sounds like @p2k knows more than me about this topic, so feel free to close my PR and take his. Glad this is getting resolved

**Comment by p2k** [comment] 2017-04-13 16:48
I'm doing a few more tests with your information @SlickWish and see if everything compiles fine. In case I see something amiss, I'll amend changes to my pull request. Hold on.

**Comment by ojwb** [comment] 2017-06-28 04:53
Closing in favour of PR #968 which is where all the recent action is.

**Comment by halton** [comment] 2017-08-25 08:11
Please be noted, NaN will be deprecated and being replaced by N-API (https://nodejs.org/api/n-api.html#n_api_n_api).

**Comment by p2k** [comment] 2017-08-25 08:20
Future note: At the time of writing, the N-API is in experimental stage and also does not mention the words "deprecated", "discontinued" or "obsolete" while describing the relationship with NaN. The wish was father to the thought, I guess.

**Comment by halton** [comment] 2017-08-25 08:53
Yes, it is true that N-API is under experimental, mostly because it is not compatible with NaN modules, time and effort are required for most NaN modules be migrated, but N-API is the future. 

What I meant is if SWIG decide to use a way to avoid the v8 version differences, N-API is the right choice.

**Comment by p2k** [comment] 2017-08-25 08:58
That would be my opinion too, I just wanted to say that NaN is probably not going to be deprecated soon and might even co-exist to support existing projects. In all cases, this discussion would better fit in #971 since this ticket here is just about getting SWIG to run as it is, short-term, with the current v8 and not about a long-term major rewrite of the entire Node.js wrapper.

**Comment by ojwb** [comment] 2017-08-28 00:39
> Closing in favour of PR #968 which is where all the recent action is.

Looks like I failed to actually close this - doing so now.

**Closed by ojwb** 2017-08-28 00:39 UTC
Labels: Javascript
