### ISSUE TITLE
Build warnings on Windows when using Bison <3

### ISSUE THREAD

**Issue by geographika** [swig/swig#2001] opened 2021-04-23 09:19 UTC
For info - the following warnings are logged when building with Bison 2.4.1.1 on Windows (the current version available on [nuget](https://www.nuget.org/packages/bison-win32/):

```
D:/GitHub/swig/Source/CParse/parser.c(1972): error C2220: warning treated as error - no 'object' file generated [D:\GitHub\swig\swig.vcxproj]
D:/GitHub/swig/Source/CParse/parser.c(1972): warning C4273: 'malloc': inconsistent dll linkage [D:\GitHub\swig\swig.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt_malloc.h(97): note: see previous definition of 'malloc'
D:/GitHub/swig/Source/CParse/parser.c(1979): warning C4273: 'free': inconsistent dll linkage [D:\GitHub\swig\swig.vcxproj]
  C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt_malloc.h(85): note: see previous definition of 'free'
```

Removing warnings as errors (by removing `/WX` from `"-DCMAKE_CXX_FLAGS="/WX /DPCRE_STATIC"`) still allows swig.exe to be built. 

There are no warnings when building with Bison 3.7.4 (from https://community.chocolatey.org/packages/winflexbison3). 

I'll see how easy it may be to update the nuget package, and can update the CMake build notes.

**Comment by ojwb** [comment] 2022-01-26 01:06
@geographika Does adding `#include <stdlib.h>` just after `#include <ctype.h> ` in `Source/CParse/parser.y` fix this?

**Comment by geographika** [comment] 2022-01-26 12:22
@ojwb - I just tried with the latest code and added in the include - unfortunately doesn't appear to resolve the warnings:

```
C:/swig/build/Source/CParse/parser.c(1973,24): warning C4273: 'malloc': inconsistent dll linkage [C:\swig\build\swig.vc
xproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_malloc.h(101,15): message : see previous defin
ition of 'malloc' [C:\swig\build\swig.vcxproj]
C:/swig/build/Source/CParse/parser.c(1980,19): warning C4273: 'free': inconsistent dll linkage [C:\swig\build\swig.vcxp
roj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\corecrt_malloc.h(89,14): message : see previous defini
tion of 'free' [C:\swig\build\swig.vcxproj]
```

Still no updates to the Bison Nuget packages (or any PCRE2 package). I'm looking at how easy (or not) they may be to create..

**Comment by ojwb** [comment] 2022-01-27 20:12
Thanks for checking, and getting newer Bison into Nuget sounds a great plan.

So to summarise, this is a problem building SWIG rather than in the generated code and we provide a binary build for this platform, it's a warning rather than an error and the resultant build works, it seems to be caused by what bison generates, it manifests with a version of bison which is more than 13 years old (2.4.1 released 2008-12-11) and is solved with current bison releases, and we don't know of a way to avoid it by changing our code.

It seems really unlikely this is going to get fixed at this point by changes to SWIG so I think it makes most sense to close this as "wontfix".

**Closed by ojwb** 2022-01-27 20:12 UTC
