### ISSUE TITLE
Some PHP test segfaults with PHP 7.2

### ISSUE THREAD

**Issue by jplesnik** [swig/swig#1170] opened 2017-12-12 13:44 UTC
I ran build of SWIG 3.0.12 and the latest SWIG from git and some of PHP tests segfault.
I used Fedora rawhide which contains PHP 7.2.0.

Examples of errors from  x86_64,  ppc64 and  ppc64le:
```
checking php testcase kind
make[2]: *** [../../../Examples/Makefile:1200: php_run] Aborted (core dumped)
make[1]: *** [Makefile:39: kind.cpptest] Error 2

checking php testcase constant_pointers
make[2]: *** [../../../Examples/Makefile:1156: php_run] Segmentation fault (core dumped)
make[1]: *** [Makefile:40: constant_pointers.cpptest] Error 2

checking php testcase kind
make[2]: *** [../../../Examples/Makefile:1156: php_run] Bus error (core dumped)
make[1]: *** [Makefile:40: kind.cpptest] Error 2
```
Example of errors from architecture s390x:
```
checking Examples/php/enum
/bin/sh: line 1:  9700 Segmentation fault      (core dumped) /usr/bin/php -n -q -d extension_dir=. -d safe_mode=Off -d display_errors=stderr runme.php > /dev/null
make[3]: *** [../../Makefile:1200: php_run] Error 139
make[2]: *** [Makefile:11: check] Error 2
make[1]: *** [Makefile:257: enum.actionexample] Error 2
```
More information about builds and errors can be found here:
swig-3.0.12 - https://koji.fedoraproject.org/koji/taskinfo?taskID=23653136
swig-4.0.0 - https://koji.fedoraproject.org/koji/taskinfo?taskID=23653792

The tests pass only on architectures i686, aarch64 and armv7hl.

**Comment by ojwb** [comment] 2017-12-12 21:10
At this point I'm afraid you'll probably need to debug PHP 7.2 issues for yourself - it's not yet packaged for Debian unstable, and I'm severely lacking in spare time currently.

I'm surprised to hear that SWIG 3.0.12 gets that far though - based on a report of build failures of the generated code with PHP 7.2 I committed 224bb9e0232a219b7cefd23472b592b39e277f46, though I didn't test that change with PHP 7.2 (I just confirmed it didn't break PHP 7.1).

**Comment by ojwb** [comment] 2019-02-08 04:28
I've just pushed some fixes for PHP 7.3 (generated code wasn't compiling in many case) and have hooked up CI for PHP 7.2 and 7.3, and both are now passing.

I'm not convinced that everything is right though as there are some suspicious errors reported if run under valgrind.

Do you still see segfaults with git master and either PHP 7.2 or 7.3?

**Comment by jplesnik** [comment] 2019-02-08 11:40
I ran rebuild of SWIG against PHP 7.2 and 7.3 and I can see the segfaults only for architecture ppc64le.
```
BUILDSTDERR: make[2]: *** [../../../Examples/Makefile:1066: php_run] Aborted (core dumped)
BUILDSTDERR: make[1]: *** [Makefile:40: allprotected.cpptest] Error 2
```
The following tests failed with error above
* allprotected
* array_member
* autodoc
* bools
* constant_pointers
* li_stdint
* li_windows
* nested_class
* template_default_class_parms_typedef
* arrays
* union_parameter
```
BUILDSTDERR: make[2]: *** [../../../Examples/Makefile:1066: php_run] Segmentation fault (core dumped)
BUILDSTDERR: make[1]: *** [Makefile:40: li_boost_shared_ptr.cpptest] Error 2

BUILDSTDERR: make[2]: *** [../../../Examples/Makefile:1066: php_run] Segmentation fault (core dumped)
BUILDSTDERR: make[1]: *** [Makefile:45: sizeof_pointer.ctest] Error 2
```                                         
The build logs can be found here:                                                
* [build with PHP 7.3.2-RC1- Fedora 30](https://koji.fedoraproject.org/koji/taskinfo?taskID=32645518)
* [build with PHP 7.2.14 - Fedora 29](https://koji.fedoraproject.org/koji/taskinfo?taskID=32647779)

**Closed** 2019-02-09 04:09 UTC
Labels: PHP

**Comment by ojwb** [comment] 2019-02-09 04:19
Thanks for rechecking.

After way too much time poking around the inside of PHP, it seems the answer is to register the constant we use to allowing sharing SWIG type information between modules with the module number instead of as a "MAIN" constant (I've no clear idea what the difference really is - so little of this stuff in PHP seems to be usefully documented - but a constant registered with a module number is still globally visible so the changed code should work for what's needed here.  I think it was only registered like that to avoid having to pass the module number through).

Interestingly the code SWIG generates has been doing essentially the same thing since February 2005, so just over 14 years (c3338b1a1686503721583a9e53a2f78a7a88731f).

With this change, the only valgrind errors I see are in some hand-crafted assembler in PHP (which seems to be conditionally avoided if you build PHP with `HAVE_VALGRIND` defined which strongly suggests these errors are expected).  With this valgrind suppression, I get a clean run:

```
{
    php_zend_string_equal_val
    Memcheck:Cond
    fun:zend_string_equal_val
}
```

Please recheck and let me know if you see any further problems.

**Comment by ojwb** [comment] 2019-02-11 21:45
FWIW, I'm now seeing a different segfault on shutdown with Xapian's PHP bindings, but only with PHP 7.3.  I'm not sure when this started as until recently configure was only checking for PHP 7.0 and 7.1.

Poking with the debugger, this happens when it's trying to destroy properties of a `XapianDocument` object, and the second (of two) properties seems to have been overwritten by error message text.

I've failed to cut down the reproducer usefully (after trimming very little any further change seems to make it pass), and SWIG's test suite is clean.

It's quite possible this is a buggy custom typemap and not a SWIG bug - I'd be very interested in any other reproducers as that would help narrow down where to look.

**Comment by jplesnik** [comment] 2019-02-14 08:18
I was able to successfully build SWIG with PHP tests on all architectures supported by Fedora.
