### ISSUE TITLE
%ignore for preprocessor or command line arg to ignore unknown preprocessor directive?

### ISSUE THREAD

**Issue by danomatika** [swig/swig#394] opened 2015-04-24 16:24 UTC
EDIT: I'm using SWIG 3.0.5.

I'm wrapping a C++ library that includes conditional Obj-C++ preprocessor file #imports (aka Obj-C specific "#include") in a C++ header. As of SWIG 3.0.3 & the fix for #217, generating wrappers with SWIG now fails due to:

    ../../../libs/openFrameworks/utils/ofConstants.h:199: Error: Unknown SWIG preprocessor directive: import (if this is a block of target language code, delimit it with %{ and %})
    ../../../libs/openFrameworks/utils/ofConstants.h:200: Error: Unknown SWIG preprocessor directive: import (if this is a block of target language code, delimit it with %{ and %})
    ../../../libs/openFrameworks/utils/ofConstants.h:202: Error: Unknown SWIG preprocessor directive: import (if this is a block of target language code, delimit it with %{ and %})
    ../../../libs/openFrameworks/utils/ofConstants.h:203: Error: Unknown SWIG preprocessor directive: import (if this is a block of target language code, delimit it with %{ and %})

in the following file: [ofConstants.h](https://github.com/openframeworks/openFrameworks/blob/master/libs/openFrameworks/utils/ofConstants.h#L209).

Is there some way to tell the SWIG preprocessor to ignore "#import"? I've been looking through the documentation but haven't found anything yet. Also, is there a command line argument to reenable the "silently ignore unknown preprocessor directives" behavior? The generated wrappers are working fine from versions of SWIG before 3.0.3.

Thanks!

**Comment by danomatika** [comment] 2015-04-24 16:33
I built & installed 3.0.2 and can confirm it can generate my bindings.

**Comment by wsfulton** [comment] 2015-04-25 16:49
Agreed, this is a regression since 3.0.3. A reduced test case is:

```
#ifdef AAA
#import <OpenGLES/ES1/gl.h>
#endif
```

Assuming AAA is not defined, a C preprocessor/compiler will process this (and ignore the #import) correctly, whereas SWIG does not.

**Comment by ojwb** [comment] 2015-04-30 01:41
Fixed in d26a505dad5fce497364a1d04ee3fb9bc9f122a8.

**Closed by ojwb** 2015-04-30 01:41 UTC

**Comment by danomatika** [comment] 2015-04-30 02:10
Thanks!

**Comment by ojwb** [comment] 2015-04-30 03:20
Hmm, this change means we no longer complain about this (because the bogus `#elsif` is in an inactive branch since `FOO` isn't defined:

```
#ifdef FOO
long long i;
/* Check we get an error for an unknown directive (this should be #elif).
 * Unknown directives were silently ignored by SWIG < 3.0.3. */
#elsif defined(BAR)
long i;
#endif
```

Neither GCC and clang disagnoses this either though, so it doesn't seem too terrible that SWIG now doesn't either.  But we could issue a warning if we see `#elsif` such as "#elsif isn't a valid preprocessor directive - did you mean #elif?"

The `pp_unknowndirective2.i` testcase has something like this, so I'll adjust that so the `#elsif` is in an actrive branch.

**Comment by wsfulton** [comment] 2015-04-30 21:38
Replicating the c pre-processor is the right thing to do.
