### ISSUE TITLE
parameter pack as template or function argument fails to parse

### ISSUE THREAD

**Issue by sandodo** [swig/swig#1863] opened 2020-08-27 09:05 UTC
when I use swig 4.0.2 to generate JNI files with a C++ which is in C++17, following lines give me errors:
Not sure if they are already reported:
1.    void emplace(Args &&... args) noexcept(
                   std::is_nothrow_constructible<T, Args &&...>::value) {

swig reports: Error: Macro 'noexcept' expects 1 argument
and I need to change it: make it one line and wrap it with an extra ()
        void emplace(Args &&... args) noexcept((std::is_nothrow_constructible<T, Args &&...>::value)) {

As this is a 3rd party source code, and it is a valid C++17 syntax, it is better not to change it for SWIG, otherwise maintenance issue will arise.

2.   template <typename P, typename = typename std::enable_if<
                            std::is_constructible<T, P &&>::value>::type>

I need to change to 
  template <typename P, typename std::enable_if<
                            std::is_constructible<T, P &&>::value>::type>

3. and it does not support 10'000  as well for integer values.

Could you please help to look into these syntax support issues?

Thanks,
Xiong Zou

**Comment by ojwb** [comment] 2020-09-02 03:05
SWIG's support for C++17 is currently incomplete I'm afraid.

I don't know of anyone actively working on this, but providing **complete and self-contained** test cases is probably the best way to encourage someone to.

**Comment by sandodo** [comment] 2020-09-03 03:02
Here is the source code of the SPSCQueue header which SWIG failed to parse: https://github.com/rigtorp/SPSCQueue/blob/master/include/rigtorp/SPSCQueue.h

**Comment by gavol** [comment] 2020-12-11 10:50
I have observed an issue also with inline static strings in C++17. There is no error from SWIG but the Java code does not compile.
A C++ code like that:

`inline static std::string s = "something"`

is translated in:

`static String s = something`

basically only the quotes are missing.

**Comment by wsfulton** [comment] 2020-12-12 11:24
@gavol I can't replicate your problem. Please raise a separate issue for each distinct C++17 problem.

**Comment by wsfulton** [comment] 2020-12-12 11:28
@sandodo, please provide small standalone testcases for each of your 3 issues that compile with a c++ compiler and move them to 3 separate new issues.

**Comment by ojwb** [comment] 2022-03-11 02:13
> when I use swig 4.0.2 to generate JNI files with a C++ which is in C++17, following lines give me errors: Not sure if they are already reported:
> 
>     1. void emplace(Args &&... args) noexcept(
>        std::is_nothrow_constructible<T, Args &&...>::value) {
> 
> 
> swig reports: Error: Macro 'noexcept' expects 1 argument and I need to change it: make it one line and wrap it with an extra () void emplace(Args &&... args) noexcept((std::is_nothrow_constructible<T, Args &&...>::value)) {

SWIG actually seems to fail to parse this though, e.g

```
%module test1
#include <type_traits>
class Container {
public:
template<typename T, typename... Args>
void emplace(Args &&... args) noexcept(
    std::is_nothrow_constructible<T, Args &&...>::value) {}
};
```

gives:

```
test1.i:6: Error: Syntax error in input(3).
```

I suspect implementing that in SWIG would still leave your example failing, because it seems the header being wrapped actually defines  `noexcept` as a macro from looking at the error message you get.  However I don't see such a macro defined in the header you link to.

> As this is a 3rd party source code, and it is a valid C++17 syntax, it is better not to change it for SWIG, otherwise maintenance issue will arise.
> 
>     2. template <typename P, typename = typename std::enable_if<
>        std::is_constructible<T, P &&>::value>::type>
>
> I need to change to template <typename P, typename std::enable_if< std::is_constructible<T, P &&>::value>::type>

Seems it's omitting the template parameter name when there's a default value that's the problem, as this also works:

```
template <typename P, typename X = typename std::enable_if< std::is_constructible<T, P &&>::value>::type> class A {};
```

>     3. and it does not support 10'000  as well for integer values.

That's already #1094.

**Comment by ojwb** [comment] 2022-03-11 21:36
Case 2 is already #961.

The totally unrelated gavol example isn't reproducible, so that leaves only case 1 here.

**Comment by ojwb** [comment] 2022-03-11 21:43
It seems to be the parameter pack use as a template argument which SWIG (in the `std::is_nothrow_constructible<>`) which SWIG is failing to parse so retitling.  Parameter packs are C++11 so relabelling.

**Comment by gavol** [comment] 2022-03-12 08:53
> The totally unrelated gavol example isn't reproducible, so that leaves only case 1 here.

At the time the issue was created, I did actually identify the conditions of the failure and created #1907. And you were able to reproduce it :-)

**Comment by ojwb** [comment] 2022-03-12 19:59
Thanks for the link, so we're definitely down to just the parameter pack issue here.

**Comment by ojwb** [comment] 2022-04-03 21:19
Here's a simpler parameter pack reproducer based on #2232:

```
#include <type_traits>
class Container {
public:
template<typename... Args>
static void notifyMyTypes(void (fn)(Args...));
};
```

**Comment by wsfulton** [comment] 2022-11-25 08:49
```c++
template<typename... Args> // does not cause syntax error
static void notifyMyTypes(void (fn)(Args...)); // syntax error is here
```

Incidently, problem 2. covered by #961 is now fixed.

**Comment by wsfulton** [comment] 2022-12-30 23:13
* Problem 1. (parameter pack) is fixed in master with commits up to and including 004af63f3cef63fbe91389cec1ad0c84498915e2.

* https://github.com/rigtorp/SPSCQueue/blob/master/include/rigtorp/SPSCQueue.h now parses without error by adding in the following simple workarounds before including the header:
```swig
#define __has_cpp_attribute(x) 0
#define alignas(x)
%include "SPSCQueue.h"
```

* Regarding:

> Here's a simpler parameter pack reproducer based on #2232:
> 
> ```
> #include <type_traits>
> class Container {
> public:
> template<typename... Args>
> static void notifyMyTypes(void (fn)(Args...));
> };
> ```
This parses fine now too. See 041ec797478ec1a3dc0da6f05784f1db11fc11ce wrt instantiating such templates, but in summary `notifyMyType` syntax is not supported and won't be supported for instantiation (see https://swig.org/Doc4.1/Extending.html#Extending_nn7), but `notifyMyTypesA` and `notifyMyTypesB` is:
```swig
template<typename... Args>
  static void notifyMyTypes(void (fn)(Args...)); // unconventional function (ptr)
template<typename... Args>
  static void notifyMyTypesA(void (*fn)(Args...)) {} // conventional function ptr
template<typename... Args>
  static void notifyMyTypesB(void fn(Args...)) {}; // unconventional function (ptr)
```

**Closed by wsfulton** 2022-12-30 23:13 UTC
Labels: C++11, parser
