### ISSUE TITLE
C Third party library cannot load the configuration(.ini) file from JAVA 

### ISSUE THREAD

**Issue by abuSayedMohammad** [swig/swig#760] opened 2016-08-01 05:08 UTC
I have a third party C library. I have only got the header files and .dll files and configuration files(.ini)

Using SWIG, I can connect with the library from JAVA. Internally the library is loading some .ini file.
From Java, when it tries to load the .ini file, it fails. But if I write a C program to load the library dynamically, then the library can load the .ini file successfully.

**Could anybody of you please give me any indication why JAVA cannot load the ini file using SWIG?**

I am totally stuck. To be mentioned, I am using cygwin , build the file in windows.

**Comment by vadz** [comment] 2016-08-02 11:58
You don't even explain how does it fail, so it's really impossible to even make any guesses about what happens. I think it's useless to keep this ticket opened unless a simple example reproducing the problem can be provided, nobody will be able to do anything about it anyhow.

**Comment by abuSayedMohammad** [comment] 2016-08-03 01:08
Ok. Let me explain the issue
I have the swig interface file named example.i
/* File : example.i */
```
_%module example
%{
#include "example.h"
#include "GRGCDMDef.h" //Third party header file
#include "CashDevCommon.h" //Third party header file
#include "GRGCDMStruct.h" //Third party header file
#include "CashDevStruct.h" //Third party header file
#include "GRGOcrCommonDevStruct.h" //Third party header file
#include "GRGCDMDev.h" //Third party header file
%}
%include <windows.i>
%include "example.h"
%include "GRGCDMDef.h"
%include "CashDevCommon.h"
%include "GRGCDMStruct.h"
%include "CashDevStruct.h"
%include "GRGOcrCommonDevStruct.h"
%include "GRGCDMDev.h"_
```
I am creating the wrapper DLL by following command

1. swig -c++ -java example.i
2. g++ -c example.cxx example_wrap.cxx
3. g++ -shared example.o example_wrap.o -o example.dll -L. GRGCDMDev.dll

Here GRGCDMDev.dll is the third party library. Which call some other DLL (GRGCDMDevDll.dll and OStackerDevDll.dll) internally. All the dll are in the same directory with example.i file. From the Java program if I call the function like below, the library internally cannot load the ini files(GRGDTATM_CommCfg.ini), which is located in the same directory.

```
tDevReturn returnObj = new tDevReturn(); // one of the sturcture of the header file
example.iSetCommPara(returnObj); // one of the function of the header file
```

But If I use a C++ program and load the library dynamically, it can load the ini file and work properly.
As I do not have the library code, I cannot tell you how they wrote the code. But from the return code in Java, I can understand that library cannot load the ini files internally. Do I need to add anything in the interface file, for loading the ini file by the library?

**Comment by vadz** [comment] 2016-08-03 09:29
I don't think it's a problem with SWIG or the wrappers more generally. More likely the global state of the program is just different. Two things that come to mind are

1. The current working directory: it could be changed by Java program but not by C++ version and could mean that the DLL doesn't find the file at all.
1. The current C locale: this could explain why DLL fails to load the file even if it does find it if it contains any numbers.

But you really need to debug it yourself, sorry but I (nor anybody else here, I would think) can't do it in your place.

Good luck!

**Comment by abuSayedMohammad** [comment] 2016-08-03 12:51
Ok... I am giving an simple example below to recreate the issue. I have tried all the ways, but I failed.

test.cxx file

```
 #include <stdio.h>
 #include "test.h"
 int __declspec(dllexport) openFile() {
 FILE * fp;
 fp = fopen ("file.txt", "r");
 if(fp == NULL) 
   return 0;
 fclose(fp);
return 1;
}
```

test.h file:

```
 #ifndef __TEST_H__
 #define __TEST_H__
 #ifdef __cplusplus
  extern "C" {
 #endif
 int __declspec(dllexport) openFile();

 #ifdef __cplusplus
 }
 #endif // __cplusplus
 #endif
```
Now if I create a dll(test.dll), using the following command

**g++ -c test.cxx
g++ -shared test.o -o test.dll**

Now I will access the dll from Java. So I am using SWIG to create a wrapper dll and acess the dll function.

My SWIG interface file (example.i)

```
%module example
%{
#include "example.h"
#include "test.h"
%}

%include "windows.i"
%include "example.h"
%include "test.h"
```

example.cxx file:

  `#include "example.h"`

example.h file:

 ` #include "test.h"`

Now I create the wrapper dll, using following command

**swig -c++ -java example.i
g++ -c example.cxx example_wrap.cxx
g++ -shared example.o example_wrap.o -o example.dll -L. test.dll**

My Java class:

 ```
 public class main {
  static {
     System.loadLibrary("example");
  }

  public static void main(String argv[]) {
       System.out.println(example.openFile());
  }
  }
```
When I run the Java code by following command

**javac main.java
java main**

Then jvm crash.. What can be the issue ? It seems like when C tries to open the file, JVM crash.

**Comment by vadz** [comment] 2016-08-04 12:25
What is `windows.i`? Anyhow, if the JVM crashes, it definitely looks like some problem with your JVM or its installation, it's absolutely not supposed to happen and I don't think it's a SWIG problem at all.

**Comment by ojwb** [comment] 2016-08-04 23:57
`windows.i` is shipped with SWIG and documented here: http://swig.org/Doc3.0/Windows.html#Windows_interface_file

**Comment by vadz** [comment] 2016-08-05 11:43
Oops, sorry, I didn't know about this one.

Anyhow, I've just tested using exactly the code given here and everything works correctly for me (the example Java code outputs 0 if the file can't be found or 1 if it exists), so I really think it's not a SWIG problem at all but something specific to the OP system -- even though I have no idea what could it be.

**Comment by abuSayedMohammad** [comment] 2016-08-05 13:20
I have tested in two windows machine.. Still not working... By the way , I am using cygwin terminal in windows..can it be an issue? what do you reckon?

**Comment by vadz** [comment] 2016-08-05 13:42
I don't really see how/why would this change anything, but, from general principles, I'd recommend not using Cygwin compiler -- the best is to use Cygwin shell (all the convenience of Unix) with MinGW (cross) compiler (creating 100% native modules) which is available as Cygwin package. At the very least, you could easily try it to check if it helps.

**Comment by ojwb** [comment] 2016-09-17 02:55
This appears to be a platform and/or target language issue, rather than anything really related to SWIG.  Especially as we can't reproduce, there doesn't seem any point keeping this open indefinitely, so closing.

**Closed by ojwb** 2016-09-17 02:55 UTC
Labels: Java, question
