### ISSUE TITLE
Custom __new__ for shadow class

### ISSUE THREAD

**Issue by fflexo** [swig/swig#1024] opened 2017-07-18 08:10 UTC
```
%module shadow_new

%inline %{
class _bar {};
typedef _bar *bar;

bar get_bar() { return new _bar(); }
%}

%extend _bar {
  %pythoncode %{
    def __new__(cls,*args,**kwargs):
      print('In new for class: %s' % str(cls))
      return super().__new__(cls)
  %}
}
```

And a quick test of that:

```
import shadow_new
shadow_new.get_bar()
```

Built with:
```
swig3.0 -python -py3 -c++ -Wall shadow_new.i
g++ -Wall shadow_new_wrap.cxx -o_shadow_new.so \
 -I/usr/include/python3.4 -shared -fPIC
python3 run.py
```
Gives the following with SWIG 3.0.10:
```
Segmentation fault (core dumped)
```
I was expecting that if I'd done something wrong then it would at least give me a cryptic error message instead of segfault, although what I actually want to do is influence the creation of the shadow class.

Some poking in a debugger suggests that the last code not from libpython was this line, from `SWIG_Python_NewShadowInstance`:
```
    inst = ((PyTypeObject*) data->newargs)->tp_new((PyTypeObject*) data->newargs, Py_None, Py_None);
```

Behaviour seems the same with a relatively recent build of the trunk. With SWIG 2.x it gives the following output instead:
```
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    shadow_new.get_bar()
TypeError: object() takes no parameters
```
although I'm none the wiser still.

**Comment by wsfulton** [comment] 2018-09-28 20:52
I can't reproduce your swig 2.x output using swig2.0.12. `object()` is valid python3 code despite the error message you show. Probably this is the result of undefined behaviour in that version, which manifests as a seg fault with swig-3.0.10.

This issue is fixed now though for swig 4, see #1321. The output of your test case is no longer a seg fault, but:
```
In new for class: <class 'example._bar'>
```
which looks like correct to me.

**Closed by wsfulton** 2018-09-28 20:52 UTC
Labels: Python
