### ISSUE TITLE
Python docstring: some default arguments values are missing

### ISSUE THREAD

**Issue by aundro** [swig/swig#1271] opened 2018-06-07 09:34 UTC
Hi,

we're thinking of moving from 2.0.12 to 3.0.12 (it's about time), but one thing holding us back at the moment is that some documentation attached to wrapper functions, has worsened (without a good reason, AFAICT.)

Assuming the following interface:

    %module test
    %feature(autodoc,0);
    %feature("compactdefaultargs");
    %inline %{
      const int MY_CONST_INT_VALUE = 1;
      int do_something(int foo, int bar=MY_CONST_INT_VALUE);
      #define MY_DEFINED_VALUE 2
      int do_something_else(int foo, int bar=MY_DEFINED_VALUE);
    %}

Using SWiG 2.0.12 and grepping for the docstring, would yield:

    aundro@flatiron:/tmp$ ${SWIG2_HOME}/bin/swig -I${SWIG2_HOME}/share/swig/2.0.12/python -I${SWIG2_HOME}/share/swig/2.0.12 -c++ -python -o test-swig2.cpp test.i
    aundro@flatiron:/tmp$ grep do_something test.py | grep "\->"
      """do_something(foo, bar=MY_CONST_INT_VALUE) -> int"""
      """do_something_else(foo, bar=2) -> int"""
    aundro@flatiron:/tmp$

Using 3.0.12, on the other hand:

    aundro@flatiron:/tmp$ /tmp/swig-3.0.12-install/bin/swig -c++ -python -o test-swig3.cpp test.i
    aundro@flatiron:/tmp$ grep do_something test.py | grep "\->"
        """do_something(foo, bar) -> int"""
        """do_something_else(foo, bar=2) -> int"""
    aundro@flatiron:/tmp$

As you can see, the default value for `bar` is gone. I fiddled with the `-keyword` argument, but it doesn't change anything to the docstrings.

Am I missing something, or is this indeed a regression?

Thanks!

**Comment by ojwb** [comment] 2018-06-08 02:20
There were some changes to default argument handling for Python in the early 3.0.x releases, which resulted in quite a lot of problems which were fixed in various subsequent releases.  I think this is probably another consequence of them.

Still happens with current git master.

**Comment by aundro** [comment] 2018-06-08 08:14
I'm not quite familiar with SWiG's internals, so what follows will probably look like amateur hour to most of you guys, but I had a quick look at what's going on, and I could pinpoint the cause of the issue to this, in python.cxx:

        else if (!Strchr(s, ':')) {
          Node *lookup = Swig_symbol_clookup(v, 0);
          if (lookup) {
            if (Cmp(Getattr(lookup, "nodeType"), "enumitem") == 0)  // <--------------- this
              result = Getattr(lookup, "sym:name");
          }
        }

The branch doesn't get taken because the "nodeType" of the symbol named "MY_CONST_INT_VALUE", isn't an enumerator: it's "cdecl".

Wondering what is available on the "lookup" object, I dumped the (string) key-value pairs it holds, and ended up with the following:

    "value" = "1"
    "feature:except" = "0"
    "name" = "MY_CONST_INT_VALUE"
    "tmap:varout:fragment" = "SWIG_From_int"
    "tmap:varout" = "pyobj = SWIG_From_int(static_cast< int >(MY_CONST_INT_VALUE));"
    "sym:symtab" = ""
    "hasvalue" = "1"
    "nodeType" = "cdecl"
    "kind" = "variable"
    "feature:immutable" = "1"
    "sym:name" = "MY_CONST_INT_VALUE"
    "previousSibling" = ""
    "nextSibling" = ""
    "feature:compactdefaultargs" = "1"
    "parentNode" = ""
    "decl" = ""
    "type" = "q(const).int"
    "wrap:name" = "Swig_var_MY_CONST_INT_VALUE_get"
    "feature:autodoc" = "0"
    "tmap:varout:noblock" = "1"
    "hasconsttype" = "1"
    "sym:overname" = "__SWIG_0"
    "valuetype" = "int"
    "value" = "1"
    "feature:except" = "0"
    "name" = "MY_CONST_INT_VALUE"
    "tmap:varout:fragment" = "SWIG_From_int"
    "tmap:varout" = "pyobj = SWIG_From_int(static_cast< int >(MY_CONST_INT_VALUE));"
    "sym:symtab" = ""
    "hasvalue" = "1"
    "nodeType" = "cdecl"
    "kind" = "variable"
    "feature:immutable" = "1"
    "sym:name" = "MY_CONST_INT_VALUE"
    "previousSibling" = ""
    "nextSibling" = ""
    "feature:compactdefaultargs" = "1"
    "parentNode" = ""
    "decl" = ""
    "type" = "q(const).int"
    "wrap:name" = "Swig_var_MY_CONST_INT_VALUE_get"
    "feature:autodoc" = "0"
    "tmap:varout:noblock" = "1"
    "hasconsttype" = "1"
    "sym:overname" = "__SWIG_0"
    "valuetype" = "int"

At this point, I am not certain how to proceed… should a check also be added for "valuetype" == "int"?

Thanks!

**Comment by aundro** [comment] 2018-06-08 09:08
For the record, I could trace this change in behavior down to commit:

    commit 15b369028fbfcee559d9f4a8e37e2d71428add29
    Author: Vadim Zeitlin <vz-swig@zeitlins.org>
    Date:   Sun Aug 10 03:56:04 2014 +0200

which states:

    Allow using enum elements as default values for Python functions.
    
    Enum values are just (integer) constants in Python and so can be used as the
    function default values just as well as literal numbers, account for this when
    checking whether function parameters can be represented in Python.

Is the idea here to have prototypes in documentation, that can be parsed and bits of the result used as valid Python code?

Thanks!

**Comment by aundro** [comment] 2018-06-08 09:29
More on this issue: SWiG 2.0.12 used to be very permissive with docstrings, and assuming an interface file such as:

    %module test
    %feature(autodoc,0);
    %feature("compactdefaultargs");
    %inline %{
    typedef unsigned int ea_t;
    int do_ea(ea_t arg=ea_t(-1));
    %}

we would end up with a docstring like this:

    """do_ea(arg=ea_t(-1)) -> int"""

which, depending on what you intend to do with it (such as parsing and extracting Python expressions), might not be too great since the `ea_t` type doesn't even exist in the Python wrappers, making it invalid Python code.

However, in our use case ( https://github.com/idapython/src ), it is more important to us that the docstring, while not necessarily consisting of valid Python code, provides hints to the user as to what parameter has what default value/expression associated to it.

In light of this, do you think it would be reasonable to add a minor knob to SWiG (or perhaps just the python module), asking it to keep the parameter's default expression in case `PYTHON::convertValue` doesn't return something useful? 
If so, I will work on that and come up with a proposal.

Thanks!

**Comment by ojwb** [comment] 2018-06-08 17:22
Thanks for narrowing down to the commit which introduced this regression.  Looking at 15b369028fbfcee559d9f4a8e37e2d71428add29 it looks like reverting the first hunk of the changes to `Source/Modules/python.cxx` (doesn't reverse apply cleanly, but it's obvious how to apply by hand) fixes your problem - the output is then:

```
    r"""do_something(foo, bar=MY_CONST_INT_VALUE) -> int"""
    r"""do_something_else(foo, bar=2) -> int"""
```

I'm not sure if there are any unwanted repercussions, though they would at least be localised to autodoc docstrings rather than affecting the generated code.  @vadz - any idea why you made that part of the change?

Extending the enum check with something like `|| (Cmp(Getattr(lookup, "kind"), "variable") == 0 && Cmp(Getattr(lookup, "feature:immutable"), "1") == 0)` seems plausible as an idea, but it's hard to know how well it would actually work without thorough testing.

Whatever we do, it'd be good to have more test coverage in this area - looking at `Examples/test-suite/autodoc.i` I only see one test with a default argument value, and that's a simple integer constant.

**Comment by aundro** [comment] 2018-06-09 11:47
I'm indeed wary of unwanted repercussions which, as you said, would be limited to autodoc docstrings (but I think docstrings (and documentation in general), although not mandatory for well-functioning code, do matter (after all I opened this issue precisely because of regressions to docstrings, so it would be a bit hypocritical on my part to pretend it's fine to reverse-apply the hunk in question regardless of what it might break.))

It's probably a good idea to wait for @vadz 's input; I suspect the idea here was to have autodoc docstring prototypes that contain Python code that SWiG can ensure is valid.

As for extending the check, I'm afraid that's not going to be enough: something like this

    %module test
    %feature(autodoc,0);
    %feature("compactdefaultargs");
    %inline %{
    typedef unsigned int ea_t;
    int do_ea(ea_t arg=ea_t(-1));
    %}

would still yield the docstring:

    """do_ea(arg) -> int"""

and not:

    """do_ea(arg=ea_t(-1)) -> int"""

as expected (and as 2.0.12 used to.)

**Comment by vadz** [comment] 2018-06-09 22:39
The first hunk of `python.cxx` change was motivated by moving `Swig_symbol_clookup()` call inside `convertValue()` itself and it was intentional because I didn't want to generate invalid expressions in Python docstrings.

However it was definitely wrong because it didn't account for other (non-enum) constants, as already mentioned by @ojwb in [this comment](https://github.com/swig/swig/issues/1271#issuecomment-395829474). And it looks like you also think it was completely wrong because you'd like to have arbitrary C++ expressions in docstrings, even if they're not valid in Python.

I'm not sure whether it's really a good idea though... Do we really want to do it? If we do, then the fix is as simple as removing the `"nodetype"` check completely. If we don't, then we need to improve this check to take constants into account.

What do people think should we do?

**Comment by ojwb** [comment] 2018-06-10 22:29
An arbitrary C++ default argument initialiser isn't in general valid Python code, but it does at least serve to indicate that there is a default value and will usually give a decent idea of what it is.  Hiding the fact that there's a default value when one is supported seems particularly unhelpful.

So my thought would be to revert that hunk, and think about better conversion for common cases of default C++ values into Python values for the purposes of docstrings (it'd be great if we could convert them for the code too, but as fallout from this patch shows that's a harder problem than it seems).

**Comment by aundro** [comment] 2018-06-11 09:13
> Hiding the fact that there's a default value when one is supported seems particularly unhelpful.

Absolutely. 

In addition, having default values mentioned for some arguments but not others, is particularly tricky.

**Comment by wsfulton** [comment] 2019-01-20 22:11
I agree with these last two comments and  have marked as a regression. The parameter list should remain switching to *args if SWIG can't convert the default value to valid Python code, but the docstring should show the default value C++ expression.

**Comment by vadz** [comment] 2019-01-20 23:51
OK, I'm going to create a PR reverting the hunk discussed above, AFAICS this should fix the most immediate problem.

**Closed** 2019-01-22 08:15 UTC
Labels: Python, regression
