### ISSUE TITLE
C++ template parse error

### ISSUE THREAD

**Issue by jcowles** [swig/swig#1845] opened 2020-07-19 20:50 UTC
Swig 4.0.2
Windows 10

The following fails to parse, but compiles fine outside of swig:

```
struct Sdf_PathIdentity {
    inline SdfPath const &operator()(SdfPath const &arg) const {
        return arg;
    }
};

template <class RandomAccessIterator, class GetPathFn = Sdf_PathIdentity,
          class = typename std::enable_if<
              std::is_base_of<
                  std::random_access_iterator_tag,
                  typename std::iterator_traits<
                      RandomAccessIterator>::iterator_category
                  >::value
              >::type
          >
RandomAccessIterator
SdfPathFindLongestPrefix(RandomAccessIterator begin,
                         RandomAccessIterator end,
                         SdfPath const &path,
                         GetPathFn const &getPath = GetPathFn())
{
    return Sdf_PathFindLongestPrefixImpl(
        begin, end, path, /*strictPrefix=*/false, getPath);
}
```

Error: Syntax error in input(1).
swig exited with non-zero error code 1

**Comment by romintomasetti** [comment] 2021-02-20 17:21
I also encountered issues with SWIG failing to parse some complicated template statements.

**Comment by ojwb** [comment] 2022-03-04 03:08
I think it's actually the same as #961.

**Comment by wsfulton** [comment] 2022-11-25 08:39
Yes, duplicate of #961 - syntax error parsing unnamed template parameter which is now fixed. Technique often used with `std::enable_if`.

**Closed by wsfulton** 2022-11-25 08:39 UTC
Labels: C++14
