### ISSUE TITLE
SWIG >= 3.0.0 hangs on using enums::...

### ISSUE THREAD

**Issue by towski** [swig/swig#223] opened 2014-09-05 20:04 UTC
Here is the header I am using for SWIG

```c++
namespace df {
  namespace enums {
    namespace profession {
      enum profession { ... }

  using enums::profession::profession;
}
```

The using enums::profession::profession causes swig to hang indefinitely after showing some normal output, and the output files are 0 length

**Comment by ojwb** [comment] 2015-01-09 01:36
I can't reproduce this with current git master.

The example provided was incomplete, so I amended it so it was actually syntactically valid C++ thus:

```
%module xxx
namespace df {
  namespace enums {
    namespace profession {
      enum profession { FOO };
    }
  }
  using enums::profession::profession;
}
```

I processed this with:

```
swig -c++ -python issue223.i
```

Hence closing.  If you can reproduce this with a current version, please provide a complete example including the command used to process it, and tell us what version you are using.

**Closed by ojwb** 2015-01-09 01:36 UTC
