### ISSUE TITLE
stdint.i should probably alias types in std namespace for C++

### ISSUE THREAD

**Issue by ErezRazor** [swig/swig#2532] opened 2023-04-16 22:17 UTC
Or at least that's what I believe is happening. 
When compiling a very large generated CXX file for Python, I'm getting the following error:

> file_wrap.cxx:5641:22: error: redefinition of ‘struct swig::traits<unsigned char>’
>  5641 |   template <> struct traits< unsigned char > {
>       |                      ^~~~~~~~~~~~~~~~~~~~~~~
> file_wrap.cxx:3672:25: note: previous definition of ‘struct swig::traits<unsigned char>’
>  3672 |     template <>  struct traits< std::uint8_t > {
>       |                         ^~~~~~~~~~~~~~~~~~~~~~

Looking at the generated file at the above positions, I see both code examples:

```cpp

namespace swig {
  template <> struct traits< unsigned char > {
    typedef value_category category;
    static const char* type_name() { return"unsigned char"; }
  };
  template <>  struct traits_asval< unsigned char > {
    typedef unsigned char value_type;
    static int asval(PyObject *obj, value_type *val) {
      return SWIG_AsVal_unsigned_SS_char (obj, val);
    }
  };
  template <>  struct traits_from< traits_asval > {
    typedef unsigned char value_type;
    static PyObject *from(const value_type& val) {
      return SWIG_From_unsigned_SS_char  (val);
    }
  };
}
```
and

```cpp
  namespace swig {
    template <>  struct traits< std::uint8_t > {
      typedef pointer_category category;
      static const char* type_name() { return"std::uint8_t"; }
    };
  }

```

After deleting the first code block from the file (as a whole - including all these `< unsigned char >` templates), the code compiles to an `.o` file.

**Comment by ojwb** [comment] 2023-04-23 21:16
Please can you provide a small, self-contained reproducer?

**Comment by erezinman** [comment] 2023-04-24 06:36
Unfortunately it only happened when I was trying to wrap an entire library that I received and that uses SWIG to wrap that company's C# API. I could send it to you in private, but other methods to reproduce it failed (probably because I have very little knowledge in C++).

**Comment by ojwb** [comment] 2023-04-26 22:55
We have a lot of open bugs needing attention so sadly I don't really have the time to reduce large testcases for people.

If you can't construct an example from scratch, taking the full version and cutting it back can be surprisingly quick.  I'd do it in a temporary git repo (or branch if it's in git already) and hack out about half of the code at a time, so it's like a binary chop.  If the bug still reproduces, commit.  That way if you realise you are now chasing a different failure you can back up easily.

Looks like that template is from the `%traits_ptypen` macro in `Lib/python/std_common.i` but I'm not sure that's going to be a productive direction to attack this from unless your interface file is directly invoking it.

**Comment by ErezRazor** [comment] 2023-05-05 23:30
@ojwb I finally did manage to reproduce it in an MWE: 
In a single SWIG file:
```c++
%module module

%include <std_pair.i>
%include <std_vector.i>
%include "stdint.i"


%rename(PairIntUint8) std::pair<int, std::uint8_t>;
%template(PairIntUint8) std::pair<int, std::uint8_t>;

%template(Uint8Vector) std::vector<uint8_t>;

```

I do not know if it makes sense, or should it even compile, but the error that I was getting reproduces:

>file.cxx:4627:22: error: redefinition of ‘struct swig::traits<unsigned char>’
 4627 |   template <> struct traits< unsigned char > {
      |                      ^~~~~~~~~~~~~~~~~~~~~~~
/file.cxx:3631:25: note: previous definition of ‘struct swig::traits<unsigned char>’
 3631 |     template <>  struct traits< std::uint8_t > {
      |                         ^~~~~~~~~~~~~~~~~~~~~~

**Comment by ojwb** [comment] 2023-05-09 00:11
Ah, your problem is that SWIG doesn't know what `std::uint8_t` is (since `stdint.i` only defines `uint8_t` not in the `std` namespace) so it has no idea that it's the same as `unsigned char`.

If you tell SWIG you don't get the `template <> struct traits< std::uint8_t > {` generated:

```
%module module

%include <std_pair.i>
%include <std_vector.i>
%include "stdint.i"

namespace std {
typedef ::uint8_t uint8_t;
}

%rename(PairIntUint8) std::pair<int, std::uint8_t>;
%template(PairIntUint8) std::pair<int, std::uint8_t>;

%template(Uint8Vector) std::vector<uint8_t>;
```

Maybe `stdint.i` should do this automatically if `__cplusplus` is defined.

**Comment by erezinman** [comment] 2023-05-09 12:11
@ojwb Thank you for your comment. I think this should be as transparent as possible to the end user, and should be performed automatically as you suggested. I am a Python developer with limited knowledge in C/C++ and every such "Voodoo" issue is a major pain in using SWIG. Also, AFAIK, in a similar conversion to C# THIS error doesn't occur, so this counts as a bug in my book.

**Comment by ojwb** [comment] 2023-05-14 20:55
With the SWIG/C# backend this just happens not to trigger a compilation failure, and you get code that's equivalent because `std::pair` is just wrapped as a largely opaque type anyway.

SWIG/C# is clearly affected by not knowing `std::uint8_t` is the same as `uint8_t`, as if you add a `std::` namespace qualification to  the last line (to get `%template(Uint8Vector) std::vector<std::uint8_t>;`) then you don't get the methods on the wrapped `Uint8Vector` which need to know the type (e.g. `Contains` is gone).

**Comment by ojwb** [comment] 2023-05-23 20:36
We actually have an issue for this already (#973) so closing this as a duplicate.

**Closed by ojwb** 2023-05-23 20:36 UTC
Labels: C++
