### ISSUE TITLE
C# %ignore * not working

### ISSUE THREAD

**Issue by mwpowellhtx** [swig/swig#1136] opened 2017-10-27 14:43 UTC
I have the following interface code:

```SWIG
%ignore *::get_message() const;
```

However, it only seems to impact one of my classes. The other has ``get_message()`` passing through.

I can specify each class and this will ignore the method:

```SWIG
%ignore _Clz1::get_message() const;
%ignore _Clz2::get_message() const;
```

The shorthand is nice to have, but the workaround is acceptable.

**Comment by ojwb** [comment] 2017-10-31 02:39
You don't say what version of SWIG you're using, but I can't reproduce this with current git master.  You didn't provide a complete reproducer, so I used this patch against `class_ignore`:

```
diff --git a/Examples/test-suite/class_ignore.i b/Examples/test-suite/class_ignore.i
index c0b954cd..863fca90 100644
--- a/Examples/test-suite/class_ignore.i
+++ b/Examples/test-suite/class_ignore.i
@@ -1,7 +1,7 @@
 %module class_ignore
 
 %ignore Foo;
-%ignore *::Bar::foo;
+%ignore *::foo() const;
 %ignore Far::away() const;
 
 %inline %{
@@ -17,8 +17,8 @@
     {
       class Bar : public Foo {
       public:
-       void foo(void) {};
-       
+       void foo() const {}
+
        virtual char *blah() { return (char *) "Bar::blah"; }
       };
 
diff --git a/Examples/test-suite/python/class_ignore_runme.py b/Examples/test-suite/python/class_ignore_runme.py
index 782fc07e..4a8ac7aa 100644
--- a/Examples/test-suite/python/class_ignore_runme.py
+++ b/Examples/test-suite/python/class_ignore_runme.py
@@ -4,3 +4,6 @@ a = class_ignore.Bar()
 
 if class_ignore.do_blah(a) != "Bar::blah":
     raise RuntimeError
+
+if 'foo' in dir(class_ignore.Bar):
+    raise RuntimeError
```

Tested with `make -C Examples/test-suite/python class_ignore.cpptest`

I wouldn't expect this to be target language specific, and checking the output files from `make -C Examples/test-suite/csharp class_ignore.cpptest` shows that `Bar::foo()` isn't wrapped for C# either.

**Comment by mwpowellhtx** [comment] 2017-10-31 02:49
@ojwb Sorry, yes, AFAIK, the latest stable version.

**Comment by wsfulton** [comment] 2017-11-02 19:59
The %ignore works for me too with:
```swig
%module example

%ignore *::get_message() const;

%inline %{
struct _Clz1 {
  void get_message() const;
};
struct _Clz2 {
  void get_message() const;
};
%}
```
Closing as user error.

**Closed by wsfulton** 2017-11-02 19:59 UTC
