### ISSUE TITLE
gcc + openmp + swig causes seg fault

### ISSUE THREAD

**Issue by qnzhou** [swig/swig#578] opened 2015-12-31 19:35 UTC
I noticed a weird problem that wrapping C++ code with swig causes OpenMP to change its behavior and crash on Linux.  I am not sure if it is a problem with swig or python or gomp, but the issue is probably more relevant to swig users.  Here is a minimalistic example:

https://gist.github.com/qnzhou/6777910a01ed9fa1eee8

To build the code:

```
swig -c++ -python my_vector.i
g++ -fopenmp -fPIC -c -I${PYTHON_INC} -L${PYTHON_LIB} -lpython3.4  my_vector_wrap.cxx
g++ -fopenmp -fPIC -c my_vector.cpp
g++ -fopenmp -L${PYTHON_LIB} -lpython3.4 -o a my_vector.o my_vector_wrap.o
g++ -fopenmp -L${PYTHON_LIB} -lpython3.4 -shared my_vector.o my_vector_wrap.o -o _my_vector.so
```

and running the following reproduce the seg fault:

```
python -c "import my_vector; my_vector.run_my_vector()"
```

I have tried the following environments on Linux:

gcc: 4.9.2 and 5.1.0
swig: 3.0.5
python: 2.7.6 and 3.4.0

Interestingly, older gcc (4.8.2 and 4.4.7) and icc all seem to work well.  The example also works on Mac OS X with gcc 4.9.3 and python3.4.4.

**Comment by wsfulton** [comment] 2016-01-05 20:14
This is more of an openmp problem interacting with the compilers and Python. I suggest you obtain a stack trace of the crash and post it here or wherever the stack trace points you to... openmp/python???

**Comment by ahnolds** [comment] 2016-01-06 21:44
I can't reproduce this on Ubuntu 14.04:
* gcc 4.9.3/5.3.0 (I don't believe I can get 4.9.2/5.1.0 without building them myself)
* swig 3.0.5
* python 2.7.6 and 3.4.3

I will point out that when generating python3 code, you should give swig the -py3 argument, and generally you should put libraries to link (e.g. -lpython2.7 or -lpython3.4) at the end of your compile commands.  Still, that shouldn't trigger a segfault (at worst you would either fail to compile or fail to load the module).

**Comment by ojwb** [comment] 2016-09-09 04:34
@qnzhou It seems we can't reproduce this, so we're going to need further input from you to make any useful progress...

**Comment by wsfulton** [comment] 2018-10-04 07:20
Closing. Feel free to re-open with requested information to reproduce.

**Closed by wsfulton** 2018-10-04 07:20 UTC
Labels: Python
