### ISSUE TITLE
Memory leak in swig generated code (swig 3.0.2)

### ISSUE THREAD

**Issue by mtrock** [swig/swig#283] opened 2014-12-22 15:43 UTC
SWIG3.0.2 generated code leaks memory when strings are passed from C++ to C# code.
The problem is related to "SWIG_csharp_string_callback". Earlier releases of SWIG also had leak problems related to this function.
However, the problem persists (or a new problem has been introduced) in SWIG3.0.2.

I've attached a small reproducer which shows the leak. The C# program calls a function in C++ ... which then calls a function in the C# program.
The leak can be stopped by manually adding a "delete" statement to the C++ code
generated by SWIG. However, SWIG should automatically add this "delete" to the generated code itself.

In the reproducer, the "missing" delete is in the file: LeakTest_wrap.cxx
SWIG generates the following code in "LeakTest_wrap.cxx" from the interface file (LeakTest.i):

```
void SwigDirector_CallbackHandler::Callback(unsigned int id, std::string message) {
  unsigned int jid  ;
  char * jmessage  ;

  if (!swig_callbackCallback) {
    MemLeak::CallbackHandler::Callback(id,message);
    return;
  } else {
    jid = id;
    jmessage = SWIG_csharp_string_callback((&message)->c_str()); 
    swig_callbackCallback(jid, jmessage);
  }
}
```

However, manually adding a "delete" to this function stops the leak:

```
void SwigDirector_CallbackHandler::Callback(unsigned int id, std::string message) {
  unsigned int jid  ;
  char * jmessage  ;

  if (!swig_callbackCallback) {
    MemLeak::CallbackHandler::Callback(id,message);
    return;
  } else {
    jid = id;
    jmessage = SWIG_csharp_string_callback((&message)->c_str()); 
    swig_callbackCallback(jid, jmessage);
    delete jmessage;
  }
}
```

Please, tell me if I'm doing something wrong ... or if the leak is a real problem to be solved in next release.

Thanks,
Martin

Below are my 6 reproducer files for Ubuntu (Mono).
First, execute the command:

```
make build
```

Then, execute the command:

```
make run
```

makefile:

```
SWIGDIR = /home/scada/host/swig-3.0.2

build: clean
    $(SWIGDIR)/preinst-swig -csharp -c++ -o LeakTest_wrap.cxx LeakTest.i
    g++ -c -fpic -I. LeakTest_wrap.cxx CppClass.cpp
    g++ -shared *.o -ldl -lnsl -lm -lpthread -lrt -o libMemLeak.so
    mono-csc -nologo -debug+ -out:runme.exe *.cs

run:
    env LD_LIBRARY_PATH=$$PWD mono runme.exe

clean:
    rm -f runme.* *_wrap.* *.o *.so `find . -name \*.cs | grep -v /MemLeakTest.cs`
```

LeakTest.i:

```
%module(directors="1") MemLeak

%include <std_string.i>

%feature("director") CallbackHandler;

%{
#include "CallbackHandler.h"
#include "CppClass.h"
using namespace MemLeak;
%}

%include "CallbackHandler.h"
%include "CppClass.h"
using namespace MemLeak;
```

CallbackHandler.h:

```
#ifndef RESPONSEHANDLER_H
#define RESPONSEHANDLER_H

#include <iostream>

namespace MemLeak
{

class CallbackHandler
{
public:
    CallbackHandler() {}
    virtual ~CallbackHandler() {}
    virtual void Callback(unsigned id, std::string message) {}
};

}

#endif //RESPONSEHANDLER_H
```

CppClass.h:

```
#ifndef MEMLEAK_H
#define MEMLEAK_H

#include "CallbackHandler.h"

namespace MemLeak
{

class CppClass
{
private:
    CallbackHandler* m_handler;

public:
    CppClass(CallbackHandler* hnd);
    virtual ~CppClass();
    void SendMessage(unsigned cnt);
};

}

#endif //MEMLEAK_H
```

CppClass.cpp:

```
#include "CppClass.h"

namespace MemLeak
{

CppClass::CppClass(CallbackHandler* hnd)
{
    m_handler = hnd;
}

CppClass::~CppClass()
{
}

void CppClass::SendMessage(unsigned cnt)
{
    m_handler->Callback(cnt, "Hello world. Eventually, this message leads to a memory leak. The longer the message is - the faster the memory leak appears. It happens because of a missing 'delete' in the SWIG-generated C++ code !!!");
}

}
```

MemLeakTest.cs:

```
using System;

class MemLeakTest
{
    static CppClass m_cppobj;

    class Handler : CallbackHandler
    {
        public Handler()
        {
        }

        public override void Callback(uint id, string message)
        {
            Console.Write("Callback: " + id + " ...\r");
        }
    }

    static void Main()
    {
        m_cppobj = new CppClass(new Handler());

        uint cnt = 1;
        while (true)
        {
            m_cppobj.SendMessage(cnt++);
        }
    }
}
```

**Comment by wsfulton** [comment] 2016-12-18 21:08
The directorargout typemap can be used to fix it. Here is a patch:
```patch
diff --git a/Lib/csharp/std_string.i b/Lib/csharp/std_string.i
index 5f8fa44..726b51c 100644
--- a/Lib/csharp/std_string.i
+++ b/Lib/csharp/std_string.i
@@ -43,6 +43,7 @@ class string;
    $result.assign($input); %}
 
 %typemap(directorin) string %{ $input = SWIG_csharp_string_callback($1.c_str()); %}
+%typemap(directorargout) string %{ free($input); %}
 
 %typemap(csin) string "$csinput"
 %typemap(csout, excode=SWIGEXCODE) string {
@@ -90,6 +91,7 @@ class string;
    $result = &$1_str; %}
 
 %typemap(directorin) const string & %{ $input = SWIG_csharp_string_callback($1.c_str()); %}
+%typemap(directorargout) const string & %{ free($input); %}
 
 %typemap(csvarin, excode=SWIGEXCODE2) const string & %{
     set {
```
Note that I have used free instead of delete because valgrind points out that malloc is used to create the memory:
```
Mismatched free() / delete / delete []
   at 0x4C2F24B: operator delete(void*) (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x8AED0DB: SwigDirector_CallbackHandler::Callback(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (example_wrap.cxx:399)
   by 0x8AECD43: MemLeak::CppClass::SendMessage(unsigned int) (CppClass.cxx:17)
...
 Address 0x949c910 is 0 bytes inside a block of size 202 alloc'd
   at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
   by 0x63025D: ??? (in /usr/bin/mono-sgen)
...
```
I checked and this stops the memory leak too and clearly is the correct solution on mono. Any suggestions as to how we can check what Microsoft do on Windows as that is the most used platform and they tend to use C++ more than C, so may require `delete` or `delete[]`. I believe their code is all open-source now, but have not tried looking.

**Comment by ojwb** [comment] 2022-02-03 00:30
Still reproduces with current SWIG git master and mono.

**Comment by ojwb** [comment] 2022-02-03 00:46
Closing as a duplicate of #998.

**Closed by ojwb** 2022-02-03 00:46 UTC
Labels: C#
