### ISSUE TITLE
Objective-C inline forward declaration

### ISSUE THREAD

**Issue by dmigous** [swig/swig#319] opened 2015-02-01 22:26 UTC
Hello
I want to add forward declaration to *_proxy.h Objective-C header. Tried to do this by adding to swig file:

```
%inline %{
  @class VectorProduct;
%}
```

But getting error

` Error: Illegal token '@'.`

I understand that objective-c is not supported at master branch, but maybe someone will give me a hint how to fix that?

**Comment by Feng999** [comment] 2016-05-26 03:12
Did you solve your problem ？ I have the same problem， Hope to get your reply.

**Comment by ojwb** [comment] 2016-05-26 03:29
`%inline` tells SWIG to try to wrap the code inside the block, which is why it fails.  You probably want `%begin`:

```
%begin %{
@class VectorProduct;
%}
```

This is not a bug in SWIG, so closing.  Support requests, etc are really better directed to the mailing list than the bug tracker.

**Closed by ojwb** 2016-05-26 03:29 UTC

**Comment by Feng999** [comment] 2016-05-26 03:41
Thanks for your reply； I have another question：can i use director in objc？ and is it convenient to tell me why objc  was abandoned？

**Comment by wsfulton** [comment] 2016-05-26 06:52
No-one has stepped forward to bring the objective C wrappers in the gsoc2012-objc branch to acceptable standard for incorporating into the master branch and releasing with SWIG. SWIG development is an all volunteer effort, so it requires someone interested in objective C to step forward and finish the work. I don't think directors are working given this is an advanced feature and some of the basic features are not yet working.

**Comment by Feng999** [comment] 2016-05-26 08:45
Got you. Thank you very much- -.
