### ISSUE TITLE
Support for docstring broken in Ruby?

### ISSUE THREAD

**Issue by lballabio** [swig/swig#538] opened 2015-10-01 10:21 UTC
It's very possible that I'm writing something wrong. However, processing the following interface file with `swig -c++ -ruby test.i` (swig 3.0.7) results in a Ruby wrapper that doesn't compile:

```
%module(docstring="module docstring") Foo

%feature("docstring") Foo::Foo %{
First line
of a multi-line docstring.
%}
class Foo {};

%feature("docstring") Bar::Bar "Single-line docstring"
class Bar {};
```

The resulting `test_wrap.cxx` contains the docstrings verbatim and unescaped, as in:

```
First line
of a multi-line docstring.
SWIGINTERN VALUE
_wrap_new_Foo(int argc, VALUE *argv, VALUE self) {
    ...
}
```

for the multi-line docstring and

```
Single-line docstringSWIGINTERN VALUE
_wrap_new_Bar(int argc, VALUE *argv, VALUE self) {
    ...
}
```

for the single-line one.
Moreover, the module docstring is discarded.

The same interface file creates all docstrings correctly when processed with `swig -python`.

**Comment by vadz** [comment] 2015-10-01 11:48
Has this worked before, i.e. is it a regression or just something that was never implemented?

**Comment by lballabio** [comment] 2015-10-01 12:19
I just added docstrings to the interfaces, so I don't know. I kind of assumed it was working because it's documented at <http://swig.org/Doc3.0/Ruby.html#Ruby_nn65>, but I hadn't tried it before.

**Comment by ojwb** [comment] 2016-01-11 21:08
PR#582 has a patch to implement adding the module docstring.

**Comment by ojwb** [comment] 2016-09-12 00:39
I've closed https://sourceforge.net/p/swig/bugs/1380/ as a duplicate of this.

**Comment by wsfulton** [comment] 2019-01-06 00:04
The Ruby docstring support was added in 594483bbda07106f703615db51436feb56017cfb for swig-1.3.32. I checked the swig-1.3.32 release and it was broken so looks like it never worked despite it being documented. I'm about to commit a fix.

**Closed** 2019-01-06 00:20 UTC
Labels: Ruby
