### ISSUE TITLE
C++ Direct initialization is not supported/parsed correctly

### ISSUE THREAD

**Issue by rolftheunissen** [swig/swig#101] opened 2013-10-30 12:13 UTC
The following line, c++ direct initialization of a integer, leads to a parse error:

```
int a(3);
```

480: Error: Syntax error in input(1).

Furthermore, constants defined using direct initialization are not wrapped as constants:

```
const int b(static_cast<int>(ENUM_ITEM));
```

is translated as function with an argument.

**Comment by ojwb** [comment] 2022-03-16 00:35
Both still the case for current git master.

**Comment by ojwb** [comment] 2022-07-05 03:23
Closing as a duplicate of #869 (which was reported well after this, but gives more examples).

**Closed by ojwb** 2022-07-05 03:23 UTC
Labels: parser, C++
