### ISSUE TITLE
Python converts NULL default argument to 0 instead of None

### ISSUE THREAD

**Issue by kkaempf** [swig/swig#365] opened 2015-03-24 15:11 UTC
https://github.com/Openwsman/openwsman/issues/59 raises an issue with default arguments in Python.

A function definition of

     WsXmlDocH invoke( client_opt_t *options, const char *resource_uri, const char *method, WsXmlDocH data = NULL) {

gets converted to the following Python code

     def invoke(self, options, resource_uri, method, data=0):

instead of

     def invoke(self, options, resource_uri, method, data=None):

**Comment by jspreston** [comment] 2015-04-06 15:39
I've run into what I think is the same problem, and I think I can give some more specific info.  This error does not occur with version 3.0.2, but does with 3.0.5.  It seems to only come up with typedef'd pointer types in class member functions, I've created a minimal example here:

https://gist.github.com/jspreston/cf702e2dae00c1c3717c

in test_hello.py, only the final line fails, giving the following error:

```
Traceback (most recent call last):
  File "test_hello.py", line 24, in <module>
    hc.classprint3(hello.MY_TWO)
  File "/home/sci/jsam/code/Projects/Utah/tmp/swigtest/hello.py", line 132, in classprint3
    return _hello.MyClass_classprint3(self, n, t)
NotImplementedError: Wrong number or type of arguments for overloaded function 'MyClass_classprint3'.
  Possible C/C++ prototypes are:
    MyClass::classprint3(MyNums,MyT)
    MyClass::classprint3(MyNums)

Makefile:11: recipe for target 'test_hello' failed
make: *** [test_hello] Error 1
```

again, the example works fine with SWIG version 3.0.2.

**Comment by ojwb** [comment] 2015-04-06 16:16
@jspreston That's entirely unrelated to this issue.  There have been some fixes in that area since 3.0.5, so it would be worthwhile checking with current git master.  If it still happens there, can you open a new issue for that please?

**Comment by jspreston** [comment] 2015-04-06 16:44
Sorry, superficially looked like it might be the same problem.  The problem persists in the current HEAD, I've opened a new issue (issue #376)

**Comment by ojwb** [comment] 2015-04-10 22:28
@kkaempf It looks like the issue is that SWIG isn't seeing through a `typedef` to recognise that `WsXmlDocH` is actually a pointer.

I filled in the missing details of your example to give:

```
%module foo

typedef void * WsXmlDocH;

WsXmlDocH invoke( client_opt_t *options, const char *resource_uri, const char *method, WsXmlDocH data = NULL);
```

Processing that I can reproduce your issue:

```
$ ../preinst-swig -python test.i && grep 'def invoke' foo.py
def invoke(options, resource_uri, method, data=0):
```

If I switch the typedef to a `#define` like so:

```
%module foo

#define WsXmlDocH void *

WsXmlDocH invoke( client_opt_t *options, const char *resource_uri, const char *method, WsXmlDocH data = NULL);
```

Then that works:

```
$ ../preinst-swig -python test.i && grep 'def invoke' foo.py
def invoke(options, resource_uri, method, data=None):
```

The code in the python backend is allowing for people using `NULL` as the default parameter for a non-pointer value, which is rather bogus but works in C++ where `NULL` is defined to `0`, and is seen in the wild.

Looking at `Source/Swig/typeobj.c` there's a comment that's pertinent:

```
 * It is very important for developers to realize that the functions in this
 * module do *NOT* incorporate higher-level type system features like typedef.
 * For example, you could have C code like this:
 *
 *        typedef  int  *intptr;
 *
 * In this case, a SwigType of type 'intptr' will be treated as a simple type and
 * functions like SwigType_ispointer() will evaluate as false.  It is strongly
 * advised that developers use the TypeSys_* interface to check types in a more
 * reliable manner.
```

Sadly, that's the only reference to `TypeSys` in the SWIG sources, so I'm not sure what function should be used here instead.  I think it must mean "functions in `typesys.c`, and `SwigType_typedef_resolve_all` looks promising.

This patch seems to fix this case:

```
diff --git a/Source/Modules/python.cxx b/Source/Modules/python.cxx
index 0e4a402..635f71b 100644
--- a/Source/Modules/python.cxx
+++ b/Source/Modules/python.cxx
@@ -1922,7 +1923,10 @@ public:
        if (Len(v) == 1) {
          // This is just a lone 0, but it needs to be represented differently
          // in Python depending on whether it's a zero or a null pointer.
-         if (SwigType_ispointer(t))
+         SwigType * true_type = SwigType_typedef_resolve_all(t);
+         bool ispointer = SwigType_ispointer(true_type);
+         Delete(true_type);
+         if (ispointer)
            return NewString("None");
          else
            return v;
@@ -1958,8 +1962,12 @@ public:
       return NewString("True");
     if (Strcmp(v, "false") == 0 || Strcmp(v, "FALSE") == 0)
       return NewString("False");
-    if (Strcmp(v, "NULL") == 0 || Strcmp(v, "nullptr") == 0)
-      return SwigType_ispointer(t) ? NewString("None") : NewString("0");
+    if (Strcmp(v, "NULL") == 0 || Strcmp(v, "nullptr") == 0) {
+      SwigType * true_type = SwigType_typedef_resolve_all(t);
+      bool ispointer = SwigType_ispointer(true_type);
+      Delete(true_type);
+      return ispointer ? NewString("None") : NewString("0");
+    }
 
     // This could also be an enum type, default value of which could be
     // representable in Python if it doesn't include any scope (which could,
```

@wsfulton Does that look OK to you?

If so, I'll commit with a testcase something like this:

```
%module foo

typedef void * WsXmlDocH;

WsXmlDocH invoke( int x = NULL, const char *resource_uri = NULL, const char *method = 0, WsXmlDocH data = NULL, WsXmlDocH data2 = 0);
```

With the patch, that results in:

```
def invoke(x=0, resource_uri=None, method=None, data=None, data2=None):
```

**Comment by wsfulton** [comment] 2015-04-10 23:29
@ojwb, yes, that all looks good. The type does need resolving in order to determine if it is a pointer. Thanks.

**Comment by ojwb** [comment] 2015-04-13 06:21
@kkaempf I'm struggling to produce a testcase which fails before this fix - what is/are the exact prototype(s) for `invoke` which SWIG is wrapping in your case?

**Comment by vadz** [comment] 2015-04-22 01:28
@ojwb The test case of #376 shows the same problem I think, so I'm going to add it to the test suite, apply your patch and commit both these tickets if you don't object. Thanks for finding the fix!

**Comment by ojwb** [comment] 2015-04-22 01:57
Ah, so that was actually the same issue after all.

@vadz Please feel free to commit.  I don't have a newer patch, except for some non-functioning attempts to add a regression test.

**Closed** 2015-04-23 13:11 UTC
