### ISSUE TITLE
New nodejs implament node-api node-addon-api

### ISSUE THREAD

**Issue by jinfeihan57** [swig/swig#2362] opened 2022-09-12 15:40 UTC
Is there any plan to support [Node-api](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html) or [node-addon-api](https://github.com/nodejs/node-addon-api) ?

**Comment by ojwb** [comment] 2022-09-19 00:44
I don't think we've had an active SWIG/Javascript maintainer for some time now, so realistically it needs someone to contribute a patch.

**Comment by jinfeihan57** [comment] 2022-09-20 07:46
Does swig have a development guide? It is convenient for others to enter the development quickly.

**Comment by wsfulton** [comment] 2022-09-20 16:39
Developers guide is here: https://swig.org/Doc4.0/Extending.html#Extending. That is rather old though and swig-4.1 docs are not published yet. There have been some updates to in master, so probably best to view using https://htmlpreview.github.io/?https://github.com/swig/swig/blob/master/Doc/Manual/Extending.html

**Comment by wsfulton** [comment] 2022-09-22 18:53
This is a duplicate of #1243. I suggest following up in that issue.

**Closed by wsfulton** 2022-09-22 18:53 UTC
Labels: Javascript
