### ISSUE TITLE
swig_obj: unreferenced local variable

### ISSUE THREAD

**Issue by Cilyan** [swig/swig#1697] opened 2020-01-06 19:06 UTC
Generation of code using `-python -builtin` flags on Swig 4.0.1 makes Visual Studio 2017 raise a bunch of warnings:
```
warning C4101: 'swig_obj': unreferenced local variable
```
This seems to happen for functions that wrap a member method without parameters, like delete, get, cast, ...

**Comment by vadz** [comment] 2020-01-06 23:17
FWIW I don't recommend compiling SWIG-generated code with maximum (in this case `/W4`) warning level, this will often result in tons of warnings.

**Comment by Cilyan** [comment] 2020-01-07 15:30
Not really tons, without `-builtin`, the code compiles without warnings, and only this one is present when compiling with builtin option (well, many times, but this is generated code).

However, the correction seems a bit more complicated than I expected as the code originates from the `python.cxx` file. In my generated code (140K lines), it seems that actually the `num_arguments` (that ends up in the `swig_obj[]` array size is always 1 bigger than needed. But I may miss some corner cases...?

**Comment by ojwb** [comment] 2022-01-27 01:48
I think vadz point is essentially there's not a lot to gain from turning on some classes of warning (unused variable/parameter/function for example) for generated code.  If the compiler can see they're unused, it can avoid generating any code for them.

However it's often convenient to not have to special-case warnings per file in a project which has some generated and some hand-written source files, so while it's certainly not a top priority clean patches to eliminate warnings in generated code usually get merged promptly, and otherwise such warnings get addressed eventually.

I had a quick look and it seems here the issue is that the `swig_obj` variable gets generated for any function which has parameters, but the `this` parameter on methods isn't taken into account in the "has parameters" condition.  Testing a fix.

**Closed** 2022-01-27 09:34 UTC
Labels: Python
