### ISSUE TITLE
Very bad performance of version 4.0.0 relative to 3.0.12

### ISSUE THREAD

**Issue by burnss887** [swig/swig#1546] opened 2019-05-23 18:02 UTC
On version 4.0.0 swig.exe used very more RAM relative to 3.0.12. (may memory leaks?).
If on 32-bit version 3.0.12 wrapping correct,that on version 4.0.0 process was crashed.
Alos, on version 3.0.12 wrapping time ~ 22minutes - 100% wrapped, but on version 4.0.0 wrapping time ~19minutes - 13% wrapped, and process was crashed.

Regards,
Ivan.

**Comment by ojwb** [comment] 2022-01-27 04:56
I've noticed while debugging with `-debug-tmsearch` that SWIG now seems to repeat typemap searches when older versions only searched once.  Maybe that's connected.

**Comment by ojwb** [comment] 2022-01-30 04:58
Testing, the number of typemap searches is essentially unchanged between 3.0.12 and 4.0.2.  I tried a few testcases and a few target languages.  Unfortunately I don't remember exactly what I was doing when I noticed the apparent duplicate typemap searches, just that I was doing a git bisect and made a mental note to investigate later.  I wish I'd made a physical note now.

Also no noticeable speed change in my tests.

@burnss887 It seems either you're tickling a particular problem case, or else the sheer size of what you're wrapping is the trigger - at least I'm guessing this is a huge library and if so I suppose a reproducer isn't easy to supply?

Can you profile the 4.0.x run and see where the time is spent?

Does SWIG 4.0.x end up swapping when SWIG 3.0.12 didn't?

**Comment by ojwb** [comment] 2022-03-04 04:22
I tried generating Xapian's Python bindings with SWIG 3.0.13 and SWIG 4.0.2 (3.0.13 instead of 3.0.12 since I happen to have a build to hand), and 4.0.2 is actually has a slightly **lower** peak max resident according to `time` (and is also slightly faster):

3.0.13: 
```
1.60user 0.01system 0:01.63elapsed 99%CPU (0avgtext+0avgdata 68648maxresident)k
0inputs+4832outputs (0major+17685minor)pagefaults 0swaps
```
4.0.2:
```
1.31user 0.03system 0:01.35elapsed 99%CPU (0avgtext+0avgdata 66648maxresident)k
64inputs+4944outputs (0major+14934minor)pagefaults 0swaps
```

Similarly for Java:

3.0.13:
```
1.10user 0.07system 0:01.18elapsed 99%CPU (0avgtext+0avgdata 43804maxresident)k
0inputs+2536outputs (0major+10287minor)pagefaults 0swaps
```
4.0.2:
```
0.98user 0.02system 0:01.01elapsed 99%CPU (0avgtext+0avgdata 40748maxresident)k
240inputs+2552outputs (1major+8287minor)pagefaults 0swaps
```

So I'm going to close this as unreproducible.  If you can provide more information such that we can usefully investigate, please do and we can reopen.

**Closed by ojwb** 2022-03-04 04:22 UTC
