### ISSUE TITLE
[Fr] Racket has moved to Chez Scheme

### ISSUE THREAD

**Issue by andrewcrook** [swig/swig#2291] opened 2022-06-15 15:18 UTC
I wonder if the MzScheme/Racket support is moving to Chez Scheme in line with Racket’s changes?

**Comment by ojwb** [comment] 2022-06-15 21:14
We've not had an active maintainer for SWIG's mzscheme support since ~2006 so it really needs somebody who knows Racket and is motivated to step forward and make it happen.

Closing as a duplicate of #920.  If you're interested in volunteering to work on this, please follow up there.

**Closed by ojwb** 2022-06-15 21:14 UTC
