### ISSUE TITLE
The link http://www.dabeaz.com/cgi-bin/wiki.pl in README is dead

### ISSUE THREAD

**Issue by AnushS4t1qbit** [swig/swig#802] opened 2016-09-26 23:49 UTC

**Comment by ojwb** [comment] 2016-09-27 02:04
Also a number of links to it throughout the documentation...

@dabeaz I know you've had issues with mass spamming of the SWIG wiki in the past - have you given up and deliberately removed it, or is this a temporary issue and we should expect it to reppear?

**Comment by wsfulton** [comment] 2016-09-27 06:55
Dave and I have talked about using the wiki in Github instead and remove the old wiki altogether. However, he hasn't managed to get a data dump out of the wiki so I think we'll have to port the useful bits manually. I intended to do this a few years ago, but haven't got around to it. Most of the old contents can be wiped in my opinion, so ought not to take too long. I suggest posting to swig-devel to discuss any further as Dave is not on Github.

**Comment by dabeaz** [comment] 2016-09-27 08:58
At the moment, I have renamed the wiki because I wasn't sure if it was active or not.  I can restore it, but it begs the question of what to do with the wiki generally.  At the moment, it is a magnet for spam and all sorts of crazy behavior.  For example, bots creating hundreds of thousands of accounts.   I have had editing and all sorts of features disabled for some time now.   Open to ideas on this.

Cheers,
Dave

**Comment by dabeaz** [comment] 2016-09-27 11:35
Oh, I'm on Github, but I'm probably not connected to the Swig project if it's there (note to self: I should fix that).  On the subject of a data dump, I'm not sure how easy it would be or not.  The wiki is frankly kind of a mess and it's not the most easy thing to navigate or interpret on the back end.  

Cheers,
Dave

**Comment by ojwb** [comment] 2016-09-28 01:25
I think it's probably simplest to temporarily restore the wiki (read-only is fine), move any useful content into the documentation by just taking it from the wiki web front-end (HTML formatting makes that easier than wiki markup would), eliminate all links to the wiki, then shut it down for good.

A wiki is very easy to update, but generating a PR for a change isn't a very high bar - you can even do it entirely via a webbrowser for a documentation edit, and on the plus side it doesn't require yet another account (assuming you already have a github account).  And it's much more spam resistant - I don't recall ever seeing a spam PR.

**Comment by wsfulton** [comment] 2016-09-30 06:41
@dabeaz, sorry, didn't realize you were on Github. I can add you to http://github.com/swig/swig has been on Github for a couple of years now and I can add you as a project admin or developer if you like, just let me know.

@ojwb, the wiki is viewable. I grabbed a html download of it a while ago with the intention of copying the best bits into the Gihub wiki. I really ought to get around to doing that.

**Comment by ojwb** [comment] 2016-09-30 21:08
> @ojwb, the wiki is viewable

It was just returning a completely blank page, hence this report (and I confirmed that was the case - otherwise I'd have just closed this issue as invalid...)

> I grabbed a html download of it a while ago with the intention of copying the best bits into the Gihub wiki. I really ought to get around to doing that.

One issue I quickly noticed is that spammers have replaced some pages, so if you've just grabbed the latest version you may not have all the content.  E.g. the FAQ is now the useless:

http://www.dabeaz.com/cgi-bin/wiki.pl?SwigFaq

The (perhaps) useful version is:

http://www.dabeaz.com/cgi-bin/wiki.pl?action=browse&id=SwigFaq&revision=49

While the reported issue is fixed, perhaps we should repurpose this ticket as "sort out migrating useful content out of the wiki so we can shut it down"?

**Comment by wsfulton** [comment] 2017-01-05 19:33
I've migrated what I could from the old wiki to the Github wiki. I've just posted to the swig-devel list about this too.

I should mention that I also moved the interesting COM stuff to the branch containing COM development - d05748e041e7583b074c0bec4bbdf2eb90a431c5.

**Closed by wsfulton** 2017-01-05 19:33 UTC
Labels: documentation

**Comment by vadz** [comment] 2017-01-05 23:56
FWIW if anybody is interested in the old unfinished COM backend, I tried to revive it some time ago. I abandoned my efforts because we finally decided to use C# backend with .NET-to-COM interop instead, but I did make some improvements to it which I could push somewhere...

**Comment by ojwb** [comment] 2017-01-06 00:53
@vadz You pushed a rebased branch with some fixes on top about 18 months ago (#426) - was there more than that?

**Comment by vadz** [comment] 2017-01-06 02:12
Yes, I have a dozen more commits from about the same time. The trouble is that the last one is marked as "WIP: make COM test suite pass", so the test suite still doesn't really pass and I would need to deal with the "WIP" part (I use this prefix to mean that it should not be pushed out in the current state)...
