### ISSUE TITLE
memory not include in .cxx files

### ISSUE THREAD

**Issue by Drgzidjiboy4ik** [swig/swig#2338] opened 2022-08-15 17:23 UTC
Hello.

According to https://gcc.gnu.org/gcc-11/porting_to.html `<memory>` has to be included explicitly.

I've built swig using gcc 11 and the problem is that `<memory>` is not included into generated .cxx files, doing this **manualy** fixes the compilation errors and my Python scripts work everything works fine with c++ smart_pointers.

Could you consider it a bug? Ir this latests compilers support is not eimplemented yet?

**Comment by wsfulton** [comment] 2022-08-22 22:01
We use gcc-11 and it works fine. Are you using the swig-4.0.2 sources or the latest master sources? What's your patch?

**Comment by ojwb** [comment] 2022-08-23 22:26
(Fixed the initial report to escape `<memory>` which was getting eaten by markdown processing.)

**Comment by ojwb** [comment] 2022-09-01 00:23
SWIG's testsuite contains a number of smart-pointer testcases and passes with GCC 12.2, so it looks like there's a `#include <memory>` missing in some case that's not currently tested, or else this has been fixed since the version you're testing with (which you don't seem to specify).

@Drgzidjiboy4ik I think we really need a reproducer to be able to address this.

**Comment by ojwb** [comment] 2022-09-19 04:48
@Drgzidjiboy4ik Ping - there's not much we can do if we can't reproduce your problem.

**Comment by ojwb** [comment] 2022-11-07 17:50
We've no way to reproduce the problem and the reporter is unresponsive, so closing.  The reporter didn't specify a version but it is plausible this has been fixed since the version they were using (`git log -S'<memory>'` shows changes which pull in `<memory>` after 4.0.2, which was the latest stable release when this ticket was opened).

If anyone's able to reproduce this with SWIG 4.1.0, please supply a reproducer and we can reopen.

**Closed by ojwb** 2022-11-07 17:50 UTC
Labels: C++11
