### ISSUE TITLE
malformed operator == in director when generating c# code from c++ class 

### ISSUE THREAD

**Issue by jszirani** [swig/swig#1936] opened 2021-01-27 21:19 UTC
Hi, 

I am currently using swig 4.0.2 and it appears that a weird operator method is generated when trying to output the director for a c++ class that has operator == as a pure virtual

Here's the intermediate file that I am using:

````
%module(directors="1") mytest 
%{
class IIcon {
public:
  virtual ~IIcon() = default;
  virtual size_t getWidth() const = 0;
  virtual size_t getHeight() const = 0;
  virtual double getAnchorX() const = 0;
  virtual double getAnchorY() const = 0;
  virtual bool operator ==(const std::shared_ptr<IIcon>& rhs) const = 0;
};
%}

%feature("director") IIcon;

class IIcon {
public:

  virtual ~IIcon() = default;
  virtual size_t getWidth() const = 0;
  virtual size_t getHeight() const = 0;
  virtual double getAnchorX() const = 0;
  virtual double getAnchorY() const = 0;
 
  %rename(Equals) operator ==;  
  virtual bool operator ==(const std::shared_ptr<IIcon>& rhs) const = 0;
};
````

and this is the command line I am using

`swig.exe -c++ -cppext cpp -namespace MyTest -module test -csharp IconTest.il`

if I look at IIconTest_wrap.h, I see 

`virtual bool operator  =  = (std::shared_ptr< IIcon > const &rhs) const;`

And that is not what is expected.

**Comment by wsfulton** [comment] 2021-02-03 23:10
Duplicate of #1642.

**Closed by wsfulton** 2021-02-03 23:10 UTC
