### ISSUE TITLE
Can Swig warn about non-wrapped types other than base classes?

### ISSUE THREAD

**Issue by sjoubert** [swig/swig#2674] opened 2023-09-08 08:26 UTC
I don't know if this is really an issue/a missing behavior/a design choice. When wrapping code into Python (for my use case but I guess this applies for any target language) I didn't find a way to list the non-wrapped types that appears in the exposed API. In Python Swig generates a generic object wrapping which has no specific methods. The issue is I have no way to know which class I missed until I try to use them in Python.

On small libraries this is ok to do be hand, but on large API it is easy to miss a parameter or return type. What I'm looking for is something like warning 401 but for any type usage not just base classes.

I also wrap my code in Java and I have a somewhat workaround to detect those missing types. The generated wrapped Java produces one class (file) per types, those not wrapped have a name pattern starting with `SWIGTYPE_p`. So for now I can list those files and check for the missing wrapped type. However, I'm planning on dropping the Java wrapping and only keep the Python one, so this workaround will not be available anymore since there are not class files in the generated wrapping code for Python.

So, have I missed an option or warning that can report types that are not wrapped? Is there another way of checking for missing wrapped bits?

**Comment by wsfulton** [comment] 2023-09-09 22:43
Looking for the `SWIGTYPE_` type wrapper classes in Java is a good way to detect missing type information. I'm afraid that there  is no solution that I can think of for Python. 

Duplicate of #1054, please monitor this issue.

**Closed by wsfulton** 2023-09-09 22:43 UTC
