### ISSUE TITLE
Garbage collection C++/Python

### ISSUE THREAD

**Issue by antoineluong** [swig/swig#1215] opened 2018-03-23 17:10 UTC
When inheriting in Python from a class defined in C++, the instantiated objects cannot be garbage-collected if they contain some kind of self-reference.

I think it is the same issue as described in http://swig.10945.n7.nabble.com/Making-C-class-garbage-collection-ready-Python-td14359.html

- example.h
```C++
class BaseClass {
    public:
        BaseClass();
};
```
- example.cc

```C++
#include "example.h" 

BaseClass::BaseClass() {

}
```
- example.i
```
%module example

%{
#include "example.h"
%}

%include "example.h"
```
- Compilation steps (SWIG 3.0.12)
```
swig -c++ -python example.i
g++ -c example.cc
g++ -I/usr/include/python2.7 -fPIC -shared example_wrap.cxx example.o -o _example.so
```
- Python usage
```python
import gc
from example import BaseClass

class DerivedClass(BaseClass):
    def __init__(self):
        BaseClass.__init__(self)
        self.f = self.func

    def func(self):
        pass

for i in range(10):
    DerivedClass()

print(len([o for o in gc.get_objects() if isinstance(o, DerivedClass)]))
```
Is it a normal behavior? Is there a workaround to avoid this problem?

**Comment by wsfulton** [comment] 2018-03-23 21:05
SWIG provides the director feature for deriving Python classes from wrapped C++ classes. Have you tried that?

**Comment by antoineluong** [comment] 2018-03-26 18:02
Yes, the result is the same when enabling the director feature.

**Comment by ojwb** [comment] 2018-03-26 22:08
To reliably test this you should call `gc.collect()` before checking `gc.get_objects()`.  That doesn't change your example's behaviour, but it does make a difference in some similar cases.

The obvious workaround is to use a weak reference:

```
import gc
from example import BaseClass
import weakref

class DerivedClass(BaseClass):
    def __init__(self):
        BaseClass.__init__(self)
        self.f = weakref.ref(self.func)

    def func(self):
        pass

for i in range(10):
    DerivedClass()

print(len([o for o in gc.get_objects() if isinstance(o, DerivedClass)]))
```

This prints `0`.

I can reproduce the problem without SWIG being involved:

```
import gc

class BaseClass(object):
    def __init__(self):
        pass

    def __del__(self):
        pass

class DerivedClass(BaseClass):
    def __init__(self):
        BaseClass.__init__(self)
        self.f = self.func

    def func(self):
        pass

for i in range(10):
    DerivedClass()

gc.collect()
print(len([o for o in gc.get_objects() if isinstance(o, DerivedClass)]))
```

This prints `10`.  The key thing seems to be that `BaseClass` has a `__del__` method - without that the objects get garbage collected.

SWIG generates a no-op `__del__` method for this case (SWIG's one just does `return None`, which is presumably a no-op - I can't see any docs on `__del__` having a return value at least).  It looks like this can be turned off with `-noproxydel`, and if I specify that when running SWIG on your original example then I get `5`.  If I add `gc.collect()` then I get `0`.

If you're generating Python wrappers and don't care about ancient Python versions (<= 2.2 or something like that) then you really want to specify `-O` to SWIG and that enables `-noproxydel` implicitly (as well as using modern classes and some other useful things).

This really should have been made the default long ago, but it wasn't and changing in mid 3.0.x is potentially disruptive.  We're already planning to change this in SWIG 4.0.

We probably should document that using `-O` is desirable in most cases.  Currently the manual doesn't appear to mention `-O` or `-modern` **at all**!

**Comment by antoineluong** [comment] 2018-03-27 08:34
Thanks for the detailed answer, I will look into it.

Besides, is the `-O` option compatible with the `-builtin` option? The result of the test is still 10 when using both options.

**Comment by ojwb** [comment] 2018-03-27 10:51
`-O` actually has the effect of a number of different options, including `-modern`.  AIUI, both `-builtin` and `-modern` specify different ways to wrap classes in Python so I'm not sure it makes sense for both to be active at once, but it doesn't look like SWIG currently tries to make the mutually exclusive.  But I'm definitely not a Python expert so maybe I don't understand exactly what each option does.

**Comment by antoineluong** [comment] 2018-05-02 10:15
My bad for directing this in the wrong direction, in my case the `-builtin` option is definitely needed for performance reasons. Because of that, I still get this rather problematic behavior, with or without the `-O` or `-modern` options, leading to various leaks.

Has anyone encountered this issue yet and found a solution?

**Comment by wsfulton** [comment] 2019-01-20 23:11
With commit 4a48e59, the `__del__` method is no longer generated. I don't understand why `-builtin` prevents the garbage collection from occurring given the tp_del slot is not used. Maybe with some debugging in the Python interpreter we could find out. Nevertheless I'm closing this ticket as @ojwb's excellent analysis and suggested use of weakref solves the problem with `-builtin`.

**Closed by wsfulton** 2019-01-20 23:11 UTC
Labels: Python

**Comment by ojwb** [comment] 2019-01-21 04:45
I wondered if using the newer `tp_finalize` instead of `tp_dealloc` might help (https://www.python.org/dev/peps/pep-0442/).  Requires Python 3.4, but we could continue to use `tp_dealloc` for older Python if it did.

However, a quick check suggests it makes no difference here.
