### ISSUE TITLE
error : Syntax error in input(1)

### ISSUE THREAD

**Issue by kothapraveen** [swig/swig#2910] opened 2024-05-17 11:43 UTC
Hi Team,

Currently am trying to convert CPP to C# using swig but am facing below error.

.h(6) error : Syntax error in input(1).

Header code line:
[System::Serializable]

**Comment by ojwb** [comment] 2024-05-17 22:51
If that's what is really in your header file then SWIG is correct since `[System::Serializable]` isn't valid C++, e.g. GCC complains:

```
testcci:1:1: error: expected unqualified-id before ‘[’ token
    1 | [System::Serializable]
      | ^
```

`[System::Serializable]` actually looks like C# not C++, so I'm guessing you just pasted the wrong text.

SWIG's parser does have a number of limitations, but it's hard to know what you're actually hitting and whether it's even a SWIG problem.  Can you provide a minimal reproducer which parses with a C++ compiler but fails with SWIG?

**Comment by ojwb** [comment] 2024-06-01 21:17
Closing as either invalid or incomplete (unclear to me which).  If you're trying to feed SWIG C# as input to wrap, then that's not supported - the input needs to be C or C++.  Otherwise we can't do anything without a way to reproduce the problem - if you provide a reproducer, we can reopen.

**Closed by ojwb** 2024-06-01 21:17 UTC
