### ISSUE TITLE
[Python] cannot import swig package in site-packages using swig >= 3.0.9

### ISSUE THREAD

**Issue by paleozogt** [swig/swig#769] opened 2016-08-20 21:15 UTC
This is somewhat similar to #691, however the details are slightly different (and its fix doesn't fix this problem).

I distribute my library as a package, where the wrapper py file is named `__init__.py`.  This worked fine with swig 3.0.8 and previous, but the changes to `swig_import_helper` seems to have broken it.

Here is a minimal example:

```
#!/bin/bash

# swig compile
mkdir pkg
echo "%module module" > module.i
echo "from . import module" > pkg/__init__.py
swig -python -outdir pkg module.i
mv pkg/module.py pkg/__init__.py
gcc -fPIC -shared -o pkg/_module.so module_wrap.c `python-config --cflags --ldflags`

# make a virtualenv to simulate whl installation
virtualenv -p `python-config --exec-prefix`/bin/python venv
cp -r pkg venv/lib/python2.7/site-packages

# can we import the package?
venv/bin/python -c 'import pkg'
```

which gives

```
Already using interpreter /usr/bin/python
New python executable in ~/Development/swig-example/.build/venv/bin/python
Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pkg/__init__.py", line 18, in <module>
    _module = swig_import_helper()
  File "pkg/__init__.py", line 17, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _module
```

**Comment by ojwb** [comment] 2016-08-20 21:46
We also hit this with Xapian's Python bindings recently - we used to rename the generated `.py` file to `__init__.py` and this stopped working recently.  The SWIG docs seem to suggest that this isn't expected to work, so we assumed it was just by chance that it did before the recent changes:

> By default, SWIG generates proxy Python code – one *.py file for each *.i interface. The `__init__.py` files, however, are not generated by SWIG

see http://www.swig.org/Doc3.0/Python.html#Python_nn72

For now we're running the SWIG-generated wrappers through a rewriting script which replaces the insanely complicated conditional import code with just:

```
from . import _xapian
```

That works fine in this case for Python 2.6, 2.7 and 3.x.

Most of the complexity there is due to trying to support ancient Python 2.x versions which nobody has actually used for years, and the plan is that SWIG 3.1 will drop support for those and only support 2.6 and up, so I was going to try to sort this out in SWIG once that had happened, rather than have to worry about ancient versions of Python I have no easy way to test with.  But if someone is keen to address this sooner, that would be great.

FWIW, you're welcome to adapt our rewrite scripts if you want - they're MIT/X licensed:

https://github.com/xapian/xapian/blob/master/xapian-bindings/python/fixup-swig-py2-wrapper
https://github.com/xapian/xapian/blob/master/xapian-bindings/python3/fixup-swig-py3-wrapper

As well as fixing up the import code, these scripts strip out various other workarounds for ancient Python 2.x, and also simplify code which aims to allow the same wrapper to work with Python 2.x and Python 3.x (we need custom typemaps in some cases because of the `bytes` vs `string` changes, so need to generate separate wrappers anyway).  The rewritten wrappers actually reduce the time to do `import xapian` by a measurable amount (albeit small - a few milliseconds IIRC).

**Comment by paleozogt** [comment] 2016-08-22 15:55
Thanks for the info @ojwb.

While I'll need to implement your workaround just to get going, I wonder how SWIG should deal with this in future versions.

In `swig_import_helper`, the `version_info >= (2, 6, 0)` branch works fine.  I wonder if we could do a smarter series of fallbacks.  For example, try the `version_info >= (2, 7, 0)` part first, and then if that fails, fall back to the `(2,6,0)` part.

Something like this?
```from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_module')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            from os.path import dirname
            import imp
            fp = None
            try:
                fp, pathname, description = imp.find_module('_module', [dirname(__file__)])
            except ImportError:
                import _module
                return _module
            if fp is not None:
                try:
                    _mod = imp.load_module('_module', fp, pathname, description)
                finally:
                    fp.close()
                return _mod
    _module = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_module', [dirname(__file__)])
        except ImportError:
            import _module
            return _module
        if fp is not None:
            try:
                _mod = imp.load_module('_module', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _module = swig_import_helper()
    del swig_import_helper
else:
    import _module
del _swig_python_version_info```

**Comment by paleozogt** [comment] 2016-08-22 16:16
Also, I've noticed that the python importing stuff is hard-coded into `python.cxx`.  Could we have a flag that lets us modify how the importing is done?  It could be something like
   `swig -python -import_style simple`
which would just do
   `from . import _module`
whereas 
   `swig -python -import_style compat`
would do the complicated `swig_import_helper` stuff.

Additionally there could be
`swig -python -import_style none`
which would leave the import block out.  Then `%pythonbegin` could be used to implement custom import logic.

**Comment by ojwb** [comment] 2016-08-23 05:59
My knowledge of the intricacies of Python import handling and how it has changed between versions really isn't up to understanding the current code, nor your amended version I'm afraid.  That's why I went for rewriting the output until 3.1 allows us to remove most of it.

If we're going to have controllable import logic (which seems worth considering) it'd be better to specify it all in the interface file I think - otherwise you'd have to set `-import_style none` on the command line and the `%pythonbegin` with the import logic in the interface file, and you've then split up the runes needed to make that work.  Also if you're already adding things with `%pythonbegin` which you expect to appear above the import code you need to be careful about the order.

But if there was a global `pythonimport` feature with a default value of the current import code then for my case I could just do:

```
%feature(pythonimport) "from . import _xapian";
```

And a more complex case like your replacement logic could be passed as a block:

```
%feature(pythonimport) %{
from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_module')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            from os.path import dirname
            import imp
            fp = None
            try:
                fp, pathname, description = imp.find_module('_module', [dirname(__file__)])
            except ImportError:
                import _module
                return _module
            if fp is not None:
                try:
                    _mod = imp.load_module('_module', fp, pathname, description)
                finally:
                    fp.close()
                return _mod
    _module = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_module', [dirname(__file__)])
        except ImportError:
            import _module
            return _module
        if fp is not None:
            try:
                _mod = imp.load_module('_module', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _module = swig_import_helper()
    del swig_import_helper
else:
    import _module
del _swig_python_version_info
%}
```

**Comment by paleozogt** [comment] 2016-08-23 13:41
Oh I like `%feature(pythonimport)`.  That's the simplest way to do it.  :)

**Comment by ojwb** [comment] 2016-08-24 01:36
@wsfulton Any thoughts on `%feature(pythonimport)` as described above?

**Comment by mromberg** [comment] 2016-09-09 06:19
> But if there was a global pythonimport feature with a default value of the current import code then for my case I could just do:
> 
> %feature(pythonimport) "from . import _xapian";
> 
> And a more complex case like your replacement logic could be passed as a block:
> 
> %feature(pythonimport) %{

  I really like this idea!   The default value could be the exact same thing that swig puts into each module right now.  This code attempts to do "the right thing" for many cases.  But as recent history has shown, folks can get very creative with how they store and import swig generated python modules (both the shadow module and the C module).   This feature is a nice way for a wrapper writer to do things whatever way they want and support whatever python versions they want.

  The only 2 cents I'd add is that perhaps the name should be a bit more specific as to what the block of code associated with the feature actually does.  The name "pythonimport" strikes me as too generic and could be taken to mean much more than the purpose it actually serves.  The feature is code which imports the C wrapper module.  So, maybe something like "python_import_c_module".  I'm terrible with names and this may be too much.  But the idea is to make it clear what specific thing the feature is doing.

**Comment by wsfulton** [comment] 2016-09-09 06:47
I like this idea. %feature("pythonimport") is okay with me. Full documentation should make it clear what it does.

**Comment by ojwb** [comment] 2016-09-10 19:16
OK, will work on a patch when I have a bit of time (but that could be a while, so if anyone else wants to look at this please feel free - just ping me to check I'm not already working on it).

**Comment by XeCycle** [comment] 2016-09-23 00:21
I'm affected by this and downgraded to 3.0.8.  Before that I tried `%module(package="abc") mod`, but it did not even change the produced import code.

Having read this thread I got the impression that we are going to tell the user to write `%feature(pythonimport)` if the default fails?  Well that does make sense, if the user has a really complicated setup, but I'd prefer a default that works for common cases.  Maybe we can add a user-provided `package="abc"` to the import code?

**Comment by ojwb** [comment] 2016-09-23 02:23
@XeCycle I think it's reasonable to expect the default should actually work, at least for cases which are documented as supported, and I'd encourage people to submit patches when that's not the case.

By my reading of the docs, it seems installing the generated `xapian.py` as `xapian/__init__.py` isn't supported - you're expected to write your own `__init__.py`, but I'd rather avoid an extra file.  So this working with 3.0.8 was presumably by luck.

Perhaps that restriction is worth lifting, and this case should work and be documented as supported - I contemplated implementing that, but the current import logic is rather complex and I don't really understand the details of how this works in even one of the many Python versions this code aims to support.  I'd certainly not object if someone worked on that (provided they took care not to cause regressions in other cases).

But more generally you probably know how the generated wrapper is actually going to be used, so it's handy to be able to replace the default import code if you care enough to fine-tune such things - in our case we can replace a few dozen lines of code with just: `from . import _xapian`

**Comment by XeCycle** [comment] 2016-09-23 03:23
@ojwb yes, I agree that installing `xapian.py` as `xapian/__init__.py` is not worth supporting, but my case is that I install `mod.py` and `_mod.so` as `pkg/mod.py` and `pkg/_mod.so`, which, as far as my limited knowledge of python goes, is a sane setup.

Regarding the addition of `%feature(pythonimport)`, it is well worth a bump in minor version (I have no idea what is our versioning policy but this is what semver suggests); but this regression is caused by 3.0.8 -> 3.0.9, so it makes more sense to me that we fix it in a future 3.0.x without adding new features, and leave this ultimate fix for something like 3.1.0.

**Comment by mromberg** [comment] 2016-09-23 04:54
> my case is that I install mod.py and _mod.so as pkg/mod.py and pkg/_mod.so, which, as far as my limited knowledge of python goes, is a sane setup.

  It may or may not be.  Python imports are way more complicated than they need to be.  How are you expecting to import mod.py (import mod, import pkg.mod, etc)?  Without an __init__.py file pkg is not a python package (unless using python 3 and implicit namespace packages).  Both mod.py and _mod.so are in the global namespace (and always were).  So the pkg directory must be on the PYTHONPATH and the imports would be "import mod", "import _mod".

  If pkg does have an __init__.py then it is a python package and the swig code should now treat both mod.py and _mod.so as being in the pkg python package.  The wrapper code also checks for _mod.so being in the global namespace (for backwards compatibility).   In this case the imports are "import pkg.mod" and "import pkg._mod".

  But I'm not exactly sure what is breaking in your case without a few more details.

**Comment by XeCycle** [comment] 2016-09-23 07:36
Oh sorry, digged into it and found that our setup actually did not break.  I did not install a dependent library, and expected the error to be importing of that failed; the error message said "No module named _swig_module" and totally confused me.  Did not realize that until strace -e open showed the file is actually found...

Btw our package does have a hand-written __init__.py, together with some other .py files, and swig-generated .py .so all in the package dir.

My apologies again.  The error message was just too confusing, and downgrading to 3.0.8 happened to show my expected error message...

**Comment by wsfulton** [comment] 2016-09-23 17:33
@XeCycle is there some improved error message we could add into latest swig that is clear in swig-3.0.8 and not swig-3.0.10?

**Comment by wsfulton** [comment] 2016-12-01 19:26
The commit just mentioned adds an option to the `%module` directive instead of using the proposed `%feature` - features need attaching to something being parsed and so adding a module option is more appropriate.

Here's what I think is a summary of the status of this ticket: 
- The new customization option gives the option to replace the SWIG generated import code for non-standard importing.
- @XeCycle import problem was a false alarm.
- @paleozogt is using a non-standard import approach so can now use the new customization option.
- @mromberg, can you see if your new module importing can be adapted to support @paleozogt's use case?  If not we'll have to accept the regression and then let's close this ticket.

**Comment by wsfulton** [comment] 2016-12-18 14:22
i'll close this unless there are any objections

**Comment by ojwb** [comment] 2016-12-19 01:56
The issue @XeCycle had seems to be now covered by #848.

**Comment by mromberg** [comment] 2016-12-19 20:28
> @mromberg, can you see if your new module importing can be adapted to support @paleozogt's use case? If not we'll have to accept the regression and then let's close this ticket.

  I'm sure that the import helper code could be made to support this use case.  This use case covers a feature that is currently not documented as being supported by swig.   Right now the swig documentation covers swig generating code for python *modules*.  This use case requires swig to generate code that also works for python *packages*.  The 'mv pkg/mod.py pkg/__init__.py' line turns the module into a package.

  Right now the swig documentation says that __init__.py should be written by hand.  This use case (if supported) means that ALL of the swig generated code (not just the import helper code) needs to be prepared to be a python package and not just a module.  I have no idea how deep this rabbit hole is.

  Before swig-1.3.9 _mod.so was never loaded into the pkg namespace.  It was always in the global namespace.   This bug (for me it is hard to consider this as anything else) has a side effect of causing the mod.py > __init__.py "trick" to work.  

  The use case now does not work because the _mod.so module is now correctly loaded into the pkg package by importlib.   The swig generated import helper code assumes that the code is part of a python *module* and looks for the C component in the same package as that module.  However a top level package is not itself in a package.  It is in the global namespace.   So the import helper code looks for _mod in the same namespace.   And _mod.so is not there.  It is in pkg/_mod.so.

  So, swig could support this new requirement.  And the requirement is:  All swig generated code (pure python and C) can function as either a python package or as a python module.  My guess is that this will get messy.

**Comment by ojwb** [comment] 2016-12-19 21:23
> This use case (if supported) means that ALL of the swig generated code (not just the import helper code) needs to be prepared to be a python package and not just a module. I have no idea how deep this rabbit hole is.

FWIW, we've been turning the SWIG-generated Xapian bindings into a Python package by just renaming the wrapper for years.  The only tweak I'm aware of is that we now have to patch the import code, but only since about 4 months ago due to changes in the boilerplate import code SWIG adds.

**Comment by wsfulton** [comment] 2016-12-22 19:22
Okay, let's not try support the 'new' requirement. If anything, let's just make the documentation clearer in this respect.

**Comment by vadimcn** [comment] 2017-01-10 06:39
Just hist this with lldb on Windows (which uses Python3).

The culprit seems to be [this line](https://github.com/swig/swig/blob/master/Source/Modules/python.cxx#L849): if wrapper script has been renamed to `__init__.py`, `__name__` evaluates to the package name, in this case simply `lldb`. 
Now, `lldb`.rpartition('.')[0] returns an empty string, because when string doesn't contain the separator, str.rpartition(sep) is [defined to return](https://docs.python.org/2/library/stdtypes.html?highlight=rpartition#str.rpartition) `('', '', str)`.

Wouldn't it be simpler to use the `__package__` variable, which had been there since Python 2.6?

cc: @mromberg

**Comment by mromberg** [comment] 2017-01-12 18:46
> Wouldn't it be simpler to use the __package__ variable,

  I remember trying this and having trouble with it because this attribute is set in an inconsistent manner by python itself:

https://lists.gt.net/python/dev/831132

  So, the value of this attribute varies based on exactly which python importer was used.   If swig were to use it then swig would need to account for all the permutations of python versions and loader types.  The name attribute seems to be more consistent as every python loader is required to set it using the package the module belongs to.

**Comment by ismail** [comment] 2017-04-26 13:12
Using swig 3.0.12 the issue with lldb still exists as explained in https://github.com/swig/swig/issues/769#issuecomment-271498532

**Comment by wsfulton** [comment] 2018-11-22 19:39
Patch #1282 enables the use case that broke in 3.0.9 where the generated module py file can be simply renamed as `__init__.py`. It uses `__package__` if set. Note that this change will go into SWIG 4, where the solution is known to work for the reduced set of supported Python versions (2.7, 3.2+), although I think it ought to work with Python 2.6 too.

Can those affected by this bug please test it and confirm the fix.

**Closed by wsfulton** 2018-11-22 19:39 UTC
Labels: Python
