### ISSUE TITLE
[C#] Invalid generated code for getter/setter

### ISSUE THREAD

**Issue by christophe-calmejane** [swig/swig#2573] opened 2023-05-09 10:38 UTC
I'm forced to use `#define constexpr` in my swig interface file before including my c++ header due to other parsing errors with the `constexpr` keyword.
Unfortunately it also converts class constants values to read/write values, so I use `%immutable` to force the value as read-only to have swig generate the c# getter (and not the setter).

Although this seems to be working, the generated c# code is invalid.

```swig
#define constexpr
%immutable Foo::Constant;
%inline %{
class Foo
{
public:
    static constexpr size_t Constant = 64;

    Foo() noexcept {}
    ~Foo() noexcept = default;
};
%}
```

This is the generated c# code:
```csharp
public class Foo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Foo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Foo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Foo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Foo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          swigTestPINVOKE.delete_Foo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static uint Constant {
    get {
      uint ret = swigTestPINVOKE.Foo_Constant_get();
      return ret;
    }   public Foo() : this(swigTestPINVOKE.new_Foo(), true) {
  }

}
```

See how the `public static uint Constant {` block is not properly closed, causing c# parsing error.
I have the same result (although I get an expected swig wrap.cxx compilation error) if I comment the `%immutable` instruction.

Maybe this is an edge case due to my `#define` instruction, or maybe there is a hidden bug in the c# generator.

**Comment by ojwb** [comment] 2023-05-09 21:13
The `#define constexpr` isn't at fault, and `%immutable` isn't either as this reduced version generates similarly duff code:

```
%inline %{
struct Foo {
    static int C = 64;
};
%}
```

It looks like it's a simple missing `}` on the getter/setter block, but I don't see where this gets generated.  One for @wsfulton I think.

---

FWIW, `#define constexpr const` avoids the problem in your original code:

```
#define constexpr const
%inline %{
class Foo
{
public:
    static constexpr size_t Constant = 64;

    Foo() noexcept {}
    ~Foo() noexcept = default;
};
%}
```

This gives:
```
  public Foo() : this(xPINVOKE.new_Foo(), true) {
  }
 
  public static readonly uint Constant = xPINVOKE.Foo_Constant_get();
```

**Comment by christophe-calmejane** [comment] 2023-05-10 07:31
> FWIW, `#define constexpr const` avoids the problem in your original code

It does for this simple test case, unfortunately I cannot do this for my whole c++ header file I need to include as it would transform all my `constexpr` to `const` (especially my problematic `constexpr friend bool operator==(...)`).

I'll try to take a look at the code, I wasn't able to create an even simpler test case, thanks for providing one!

**Comment by ojwb** [comment] 2023-05-21 06:17
I've now found where the problem is at least.

With this patch:

```
--- a/Source/Modules/csharp.cxx
+++ b/Source/Modules/csharp.cxx
@@ -2947,6 +2950,9 @@ public:
     Language::staticmembervariableHandler(n);
     wrapping_member_flag = false;
     static_flag = false;
+    if (!generate_property_declaration_flag) {
+      Printf(proxy_class_code, "\n  }/*HERE*/\n\n");
+    }
     generate_property_declaration_flag = false;
 
     if (static_const_member_flag)
```

we get a valid `Foo.cs` from my minimised testcase above, ending:

```
  public static int C {
    set {
      xPINVOKE.Foo_C_set(value);
    } 
    get {
      int ret = xPINVOKE.Foo_C_get();
      return ret;
    } 
  }/*HERE*/

  public Foo() : this(xPINVOKE.new_Foo(), true) {
  }

}
```

It looks like the conditional just below my patch is meant to generate this closing `}` but `static_const_member_flag` is false so it doesn't.  It's set by:

```
bool static_const_member_flag = (Getattr(n, "value") == 0);
```

And `n` has a `value` attribute.  Here's what `n` looks like:

```
+++ cdecl - 0x7f1fd13a79d0 ----------------------------------------
| access       - "public"
| cplus:staticbase - 0x7f1fd13a7670
| feature:cs:enum - "proper"
| feature:except - "0"
| hasvalue     - "1"
| ismember     - "1"
| kind         - "variable"
| name         - "C"
| nextSibling  - 0x7f1fd13c2570
| parentNode   - 0x7f1fd13a7670
| storage      - "static"
| sym:name     - "C"
| sym:overname - "__SWIG_0"
| sym:symtab   - 0x7f1fd13a7810
| type         - "int"
| value        - "64"
| valuetype    - "int"
| variableHandler:feature:immutable - (nil)
| view         - "variableHandler"
| 
```

I don't really understand the logic here, but I wonder if this flag has the reversed sense to what it should.

@wsfulton Hopefully this is more obvious to you...

**Comment by wsfulton** [comment] 2023-11-16 20:24
Hi @christophe-calmejane, am going to look at this shortly. Can you provide a link to the constexpr parsing problem? I can't find any such issues reported.

**Comment by ojwb** [comment] 2023-11-16 20:31
@wsfulton Probably https://github.com/swig/swig/issues/302#issuecomment-1543471590

**Comment by wsfulton** [comment] 2023-11-16 20:40
> The `#define constexpr` isn't at fault, and `%immutable` isn't either as this reduced version generates similarly duff code:
> 
> ```
> %inline %{
> struct Foo {
>     static int C = 64;
> };
> %}
> ```

This is not valid C++ and so it it's not really reasonable to expect SWIG to handle this in any good way, so really the `#define constexpr` workaround is not producing valid code. 

> `bool static_const_member_flag = (Getattr(n, "value") == 0);`

If the static member variable has a value, then by implication it must be const/constexpr. That's the logic and it is correct when provided valid C++ code! The logic could of course be changed in some way though to accept invalid C++, but I'd need to think how to wrap it though.

**Comment by ojwb** [comment] 2023-11-16 21:03
Oh yes, I missed that this wasn't valid.  Easy to do as it's valid is either `static` is removed or `const` added.  Issuing an error would be helpful I think.  Here are what some compilers say:

```
$ g++ -c test.cc
test.cc:2:16: error: ISO C++ forbids in-class initialization of non-const static member ‘Foo::C’
    2 |     static int C = 64;
      |                ^
$ clang++ -c test.cc
test.cc:2:16: error: non-const static data member must be initialized out of line
    static int C = 64;
               ^   ~~
1 error generated.
```

**Closed** 2023-11-17 07:50 UTC
Labels: C#

**Comment by christophe-calmejane** [comment] 2023-11-17 08:03
The thing is, all compilers accept
```
class Foo
{
public:
  static auto constexpr Bar = "Hello";
};
```
as valid code.
I've seen this a lot of this in many projects, and I cannot just modify the source code easily before SWIGing it.

**Comment by christophe-calmejane** [comment] 2023-11-17 08:11
This is very valid anyway and doesn't parse currently:
```
class Foo
{
public:
    static auto constexpr Constant = 64;

    Foo() noexcept {}
    ~Foo() noexcept = default;
};
```

Does your commit fixes that (without having to hack some constexpr define)?

**Comment by wsfulton** [comment] 2023-11-18 11:27
I see #2713 has been created to track this, thanks.
