### ISSUE TITLE
Swig Javascript help

### ISSUE THREAD

**Issue by wolfviking0** [swig/swig#1523] opened 2019-04-30 00:06 UTC
Hi,

I am currently working with swig but I am facing an issue in javascript.

Currently I am creating an array inside the script size, and I want to set the value in c++ and then use the array with flatbuffers.

As an example in java it will be something like:

    private byte[] _memory = new byte[1024];
    MyCode.setMemory(_memory, _memory.length)
    ....
    // I can use the memory to create my flatbuffers object.

The c++ code look like :
   
     int MyCode::setMemory(unsigned char *ptr, int size);

In javascript I was planing to use 

     var memory = new Uint8Array(1024);
     MyCode.setMemory(memory, memory.length)

Unfortunately, the code failed with the error Error: in method '...', argument 2 of type 'unsigned char'. 

What I am doing wrong ? Any suggestion ?

Thanks

**Comment by TropicalIsland** [comment] 2019-05-03 21:59
Hi there, I'm by no means a reputable source on SWIG but I think I can help you out.

The issue is that javascript as a language does not have the concept of pointers, having only value and reference types which most of the time appear to behave the identically. 

`new` doesn't create a pointer in this sense, it simply sets `this` to a new object which is then constructed by the constructor function which will reference `this` assigning properties to the object. This means when you pass `memory` to `MyCode.setMemory`, `memory` has the equivalent type of `unsigned char`, and not `unsigned char*` which is required, hence the error.

There are two ways to resolve this, I'll show the new version first and add the old version for the sake of it.

### New
Have a look at this [interface](https://github.com/swig/swig/blob/master/Lib/javascript/v8/typemaps.i). This allows you to pass value types in your target language and have them behave like pointers in native. Your example would look a little bit like this,

```c++
%include <typemaps.i>
int MyCode::setMemory(unsigned char *INPUT, int size) {/*impl*/};
```
and your javascript example can remain as is.

### Old
If you wondered how it was done before typemaps, have a look at this [example](https://github.com/swig/swig/tree/master/Examples/javascript/pointer), in particular where it includes the interface, [cpointer.i](https://github.com/swig/swig/blob/master/Lib/cpointer.i). This interface is provided by SWIG and allows you to define aliases to native pointer types that you can access in your target language. In the example, they define `intp` which is an `int*`. The interface then also generates methods for your pointer proxy like new, copy and delete. 

For your case you would have need to have something like 
```c++
%include cpointer.i
%pointer_functions(unsigned char, ucharp);
```
in your interface, and then your js example would look more like
```javascript
var memory = new Uint8Array(1024);
var memoryptr = MyCode.new_ucharp();
MyCode.ucharp_assign(memoryptr, memory);
MyCode.setMemory(memoryptr, memory.length);
```
although I don't know for sure whether that would work and hopefully it is clear why using typemaps is preferred.

Hope this helps!

**Comment by wolfviking0** [comment] 2019-05-04 00:29
@TropicalIsland Thanks for you response, I will prefer use %include <typemaps.i>.

I am not strong with Swig, and I am not able to use your new example. In my case I am using a [.i] file.
 I do not put the implementation inside it, I have my c++.

So I tried to use your example adding only the signature 
%include <typemaps.i>
int MyCode::setMemory(unsigned char *INPUT, int size);

Still have the same issue.
Thanks

**Comment by wolfviking0** [comment] 2019-05-12 22:26
@TropicalIsland after digging a little bit, I made some progress following you idea using typemap.
May be I am wrong but I pass the first element of the array to the function : 

`var memory = new Uint8Array(10);
swig.setMem(memory.length, memory[0])`

Unfortunately there is something wrong. In my sample I initialize my array with the value 1.

But on the c++ side if I print the value the result are not just 1. I can try to update the value from the C++ side but the memory keep always the same value in the js side.

I made a simplistic sample on GitHub (https://github.com/wolfviking0/MySwigTest) may be you have another idea to solve my issue. Here the output I have.

`
// JS SIDE PRINT MEMORY
Uint8Array [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]

// C ++ SIDE PRINT MEMORY
AL --> 0 / 1
AL --> 1 / 76
AL --> 2 / 242
AL --> 3 / 117
AL --> 4 / 1
AL --> 5 / 1
AL --> 6 / 0
AL --> 7 / 0
AL --> 8 / 0
AL --> 9 / 160

// C++ SIDE PRINT MEMORY AFTER SET VALUE TO 10
AL --> 0 / 10
AL --> 1 / 10
AL --> 2 / 10
AL --> 3 / 10
AL --> 4 / 10
AL --> 5 / 10
AL --> 6 / 10
AL --> 7 / 10
AL --> 8 / 10
AL --> 9 / 10

// JS SIDE PRINT MEMORY
Uint8Array [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]

`

**Comment by TropicalIsland** [comment] 2019-05-14 18:09
@wolfviking0 
Good progress! I have run your example as follows and received the following output:

```javascript
var MySwig = require("./MySwig").MySwig

console.log(MySwig.version())

var swig = new MySwig()
var memory = new Uint8Array(10);
console.log(memory)
swig.setMem(memory.length, memory[0])
console.log(memory)

memory.set([1,1,1,1,1,1,1,1,1,1])
console.log(memory)
swig.setMem(memory.length, memory[0])
console.log(memory)
```

```console
Me@mycomputer ~/D/s/p/MySwigTest> node MySwigTest.js
0.0.0
Uint8Array [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
AL --> 0 / 10
AL --> 1 / 10
AL --> 2 / 10
AL --> 3 / 10
AL --> 4 / 10
AL --> 5 / 10
AL --> 6 / 10
AL --> 7 / 10
AL --> 8 / 10
AL --> 9 / 10
Uint8Array [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
Uint8Array [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
AL --> 0 / 10
AL --> 1 / 10
AL --> 2 / 10
AL --> 3 / 10
AL --> 4 / 10
AL --> 5 / 10
AL --> 6 / 10
AL --> 7 / 10
AL --> 8 / 10
AL --> 9 / 10
Uint8Array [ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ]
```
I can't reproduce the error you give above. The swig wrapper will coerce the type from a javascript number object to unsigned char * so that should not be an issue.

I can't see what this wrapper acheives however as the memory still holds the initial value in js. I know that array types can be manipulated directly in v8 but I am unsure what facilities SWIG provides to this end.

**Comment by wolfviking0** [comment] 2019-05-14 19:48
Hi @TropicalIsland thanks, to took the time to take a look at it.

The similar code in C# or Python allow me to set the content of the array from c++ directly.

If you prefer I would like to have the last log with Uint8Array [ 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 ]

In my real use case the, the native code as a pointer to a flatbuffer data, and I just want in the most optimize way pass the unsigned char* directly to the memory of the script languages.

**Comment by wolfviking0** [comment] 2019-05-16 04:29
Hi @TropicalIsland,

I updated my repo with a version working fine, I am not sure if I using the correct syntax or approach but at least it's working.

I just reimplement the function to be doing what I want in the .i file.


    %typemap(in)        (int size, unsigned char *ptr) {
        if (args[0]->IsUint8Array()) {
            v8::Local<v8::Uint8Array> myarr = args[0].As<v8::Uint8Array>();
            arg2 = myarr->Length ();
            unsigned int offset = myarr->ByteOffset();
            arg3 = (unsigned char*)((unsigned char*)myarr->Buffer()->GetContents().Data() + offset);
        } else {
            SWIG_exception_fail(SWIG_ArgError(res1), "Illegal argument " "2"" must be of type '" "Uint8Array""'"); 
        }
    }

**Comment by ojwb** [comment] 2022-01-27 05:10
It seems you found a solution, so closing.  If I've misunderstood please reopen (or ask to reopen - I think maybe only maintainers can reopen).

**Closed by ojwb** 2022-01-27 05:10 UTC
