### ISSUE TITLE
No error for invalid namespace name %std

### ISSUE THREAD

**Issue by clintonstimpson** [swig/swig#368] opened 2015-03-26 15:23 UTC
For Java, I have a typemap like this:

```
%typemap(jstype) std::vector<std::string>, const %std::vector<std::string>&, std::vector<std::string>&  "List<String>"
```

which results in 

```
swig: DOH/base.c:36: DohDelete: Assertion `0' failed.
```

If I fix the typo by removing the extra '%'

```
%typemap(jstype) std::vector<std::string>, const std::vector<std::string>&, std::vector<std::string>&  "List<String>"
```

then it works.

I am expecting a meaningful error message besides the assertion.

**Comment by ojwb** [comment] 2015-03-27 00:00
I created `issue368.i` containing:

```
%typemap(jstype) std::vector<std::string>, const %std::vector<std::string>&, std::vector<std::string>&  "List<String>"
```

And processed it like so with current git master:

```
./preinst-swig -java -c++ -module tmp issue368.i
```

But I get no assertion failure.

Can you supply a complete short self-contained example which demonstrates the assertion failure along with the command line used to process it?

**Comment by clintonstimpson** [comment] 2015-03-27 04:58
I did the same thing, an issue368.i file containing the one typemap line.

I call it like this
$ /usr/bin/swig -java -c++ -module tmp issue368.i 
swig: DOH/base.c:36: DohDelete: Assertion `0' failed.
Aborted (core dumped)
$ echo $?
134

$ /usr/bin/swig -version
SWIG Version 3.0.5
Compiled with g++ [x86_64-redhat-linux-gnu]
Configured options: +pcre
Please see http://www.swig.org for reporting bugs and further information

$ cat /etc/redhat-release 
Fedora release 21 (Twenty One)

I even tried this, and I still get the problem:
git clone https://github.com/swig/swig.git
cd swig
./autogen.sh
./configure
make
./preinst-swig -java -c++ -module tmp ~/issue368.i
And I get this:
swig: DOH/base.c:36: DohDelete: Assertion `0' failed.
Aborted (core dumped)


My ~/issue368.i file contains one line:
%typemap(jstype) std::vector<std::string>, const %std::vector<std::string>&, std::vector<std::string>& "List<String>"

**Comment by ojwb** [comment] 2015-03-27 05:18
Curiously it now fails for me too - not sure what I managed to actually test before, but I can now reproduce.  Sorry about that.

It's trying to delete `cparse_unknown_directive` from `CParse/cscanner.c` line 808, and it's apparently not a "DOH" object.  That's because `Swig_copy_string()` just uses `malloc()` - that ought to be `NewString()` - fixed in 6b6b360.  Thanks for spotting that - it's a regression I introduced in 3.0.4.

However, there's still no error for this case.  I'm not sure why, but that isn't a (recent) regression, as it doesn't with SWIG 2.0.12 either.  As you say, this really should give an error message.

**Comment by clintonstimpson** [comment] 2015-03-27 13:27
Thanks for fixing the segfault!
I had been using swig 2.0.x for quite some time with this typo, so you're right, there's no recent regression for catching the typo.  Its only with the swig upgrade did I start seeing a segfault.

**Comment by ojwb** [comment] 2015-03-27 22:29
I've now added a regression test too.

Checking with `-debug-typemap` I see that without the `abort()`, SWIG just adds the typemap to its list, `%` and all, so it simply won't be used.  It's essentially the same as if you'd accidentally written `xstd::vector` there.

I feel we ought to detect cases such as this where the type isn't syntactically valid, though given a very similar typo in the same location couldn't be flagged up, it doesn't seem a major issue.

**Comment by ojwb** [comment] 2016-09-11 21:45
Retitling - the assertion failure is fixed, but there's still an issue here.

**Closed** 2022-02-15 02:10 UTC
Labels: parser
