### ISSUE TITLE
Concatenated strings syntax error

### ISSUE THREAD

**Issue by mdblack98** [swig/swig#1764] opened 2020-03-23 14:37 UTC
This type of statement in C produces a syntax error from the concatenated string in the format.
fprintf(fout, "%"PRIll"%c", (int64_t)freq, resp_sep);

**Comment by ojwb** [comment] 2022-01-19 05:41
I don't really understand how you're feeding a **statement** like that to SWIG - SWIG wraps declarations rather than statements and any statements in a function body are essentially ignored by SWIG by skipping from the opening `{` to the closing `}`:

```
$ cat test2.i
%module foo
int f() {
 fprintf(fout, "%"PRIll"%c", (int64_t)freq, resp_sep);
 THIS IS NOT VALID C CODE EVEN!
}
$ swig -php test2.i
```

More generally though, concatenation of string literals is handled:

```
$ cat test.i
%module foo
#define PRIll "lld"
const char * const FOO = "%"PRIll"%c";
$ swig -php test.i
```

Note that you will need to define `PRIll` for SWIG though - it won't know to define it based on seeing `#include <whatever>` (SWIG can't know what to define it to since its value can vary by platform and compiler).  I'm assuming this was the cause of your issue, so closing.  If it wasn't, please reopen and include a small self-contained reproducer.

**Closed by ojwb** 2022-01-19 05:41 UTC

**Comment by mdblack98** [comment] 2022-01-19 06:04
Actually that concatenation in the C code is perfectly valid.  It's been in Hamlib for two decades and compiled on every OS that has ever existed.

**Comment by ojwb** [comment] 2022-01-19 08:35
I didn't say it wasn't valid.

I closed the issue because SWIG also accepts it in my tests. You didn't
supply a self-contained test case though - if you still have an issue with
SWIG here please provide one and we can reopen.
