### ISSUE TITLE
decltype(EXPRESSION) fails to parse for some valid EXPRESSIONs

### ISSUE THREAD

**Issue by kematy** [swig/swig#1589] opened 2019-07-14 04:06 UTC
When I use swig4.0.0 compiling json11 project,I encounted an
Error: Syntax error in input(3).Does Swig4 not support c++11 yet?can anyone solve it?

codelist:
```
template < class T, class = decltype(&T::to_json) >
    Json(const T & t) : Json(t.to_json()) {}

    // Implicit constructor: map-like objects (std::map, std::unordered_map, etc)
    template <class M, typename std::enable_if<
        std::is_constructible<std::string, decltype(std::declval<M>().begin()->first)>::value
        && std::is_constructible<Json, decltype(std::declval<M>().begin()->second)>::value,
            int>::type = 0>
    Json(const M & m) : Json(object(m.begin(), m.end())) {}

    // Implicit constructor: vector-like objects (std::list, std::vector, std::set, etc)
    template <class V, typename std::enable_if<
        std::is_constructible<Json, decltype(*std::declval<V>().begin())>::value,
            int>::type = 0>
    Json(const V & v) : Json(array(v.begin(), v.end())) {}
```

**Comment by ojwb** [comment] 2021-09-29 04:27
SWIG supports many but not all C++11 features.

The error reporting for parse errors like this doesn't really help pin point the problem, but here it appears to be the `decltype` - this simpler example fails to parse too (but GCC compiles it):

```
template <decltype(true) X = true>
void A() { }
```

I think this is actually documented as a current limitation in the manual:

> SWIG supports <tt>decltype()</tt> with some limitations. Single variables are allowed, however, expressions are not supported yet.

Both `std::declval<M>().begin()->first` and `true` are expressions.

**Comment by ojwb** [comment] 2021-09-29 04:30
Another example from #1590:

```
template < class T, class = decltype(&T::to_json) >
Json(const T & t) : Json(t.to_json()) {}
```

**Comment by wsfulton** [comment] 2022-11-26 01:35
Parsing && in template parameters in the following is covered by #2228.
```c++
template <class M, typename std::enable_if<
        std::is_constructible<std::string, decltype(std::declval<M>().begin()->first)>::value
        && std::is_constructible<Json, decltype(std::declval<M>().begin()->second)>::value,
            int>::type = 0>
```
Removing &&:
```c++
template <class M, typename std::enable_if<
        std::is_constructible<std::string, decltype(std::declval<M>().begin()->first)>::value,
            int>::type = 0>
```
still results in a syntax error as the following is not recognised as an expression:
```c++
(std::declval<M>().begin()->first)
```
This is after commit 2a1711e4364afe0250282e032650e3ac543e73a3 and 15692f0e89a75131a56732b828ba88a82fa67203 which adds support for decltype and expressions. The new testcase in 15692f0e89a75131a56732b828ba88a82fa67203 has the expression parsing problem reported in this issue commented out.

@ojwb, given you're most familiar with SWIG's expressions, perhaps you could have a look at this when you get a chance? This is the non-template usage of the expression that needs fixing:
```c++
#include <utility>
#include <vector>
  void f(bool c = std::is_constructible<std::string, decltype(std::declval<std::vector<std::pair<int, int>>>().begin()->first)>::value) {}
```
What a headache!

**Comment by ojwb** [comment] 2023-05-17 02:02
Reviewing in more detail, the original reported parse error was fixed by wsfulton in 2a1711e4364afe0250282e032650e3ac543e73a3 - that case now gives:

```
test.i:1: Warning 344: Unable to deduce decltype for '&T::to_json'.
test.i:6: Error: Syntax error in input(1).
```

SWIG 4.1.0 failed to parse it much earlier:

```
test.i:1: Error: Syntax error in input(1).
```

The other examples above now parse (some give `Warning 344: Unable to deduce decltype for '&T::to_json'.` or similar, but that's a different issue really, and that limitation is at least documented).

**Comment by ojwb** [comment] 2023-05-17 06:18
Digging into the example, this is (since wsfulton's improvements) no longer a decltype issue as such, but a general limitation on parsing expressions which can be reproduced using a default value too, e.g. this also fails to parse:

```
int x(int y = std::declval<M>().begin()->first) { return y; }
```

Pulling that expression apart, there's a lot of aspects of it we don't handle though, and poking why not the answer in each case seems to be that trying to do so introduces more shift/reduce conflicts into the grammar.

However, it occurs to me that at least for `decltype` we could skip to the closing matching `)` on a parse error, grab the text from inside the parentheses, emit warning 344, and continue parsing.  After arguing with bison for a while I've managed to implement that and opened #2593.

**Closed** 2023-05-17 20:08 UTC
Labels: C++11

**Comment by wsfulton** [comment] 2023-07-25 21:17
I added a testcase in 94ab6990752966758af5af3d6e43be9ae782eca8 to show how the templated constructors in the provided Json class can now be used after recent improvements in SWIG. There is no attempt at trying to use the `enable_if` template parameters to help, but without them, it is challenging as there are 3 constructors all taking one mandatory parameter and one defaulted template parameter for `%template` to choose from. However, the exact template SWIG chooses does not actually matter in this case.
