### ISSUE TITLE
swig 4.1.1 still generates 'import imp' code

### ISSUE THREAD

**Issue by mcepl** [swig/swig#2683] opened 2023-10-02 21:16 UTC
I don’t understand it. According to https://github.com/swig/swig/issues/1621 swig should generate code using `importlib` since at least 4.0.0, but with 4.1.1 I still see in the generated code
 in `./build/lib.linux-x86_64-cpython-311/M2Crypto/m2crypto.py`:

```py
from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_m2crypto', [dirname(__file__)])
        except ImportError:
            import _m2crypto
            return _m2crypto
        if fp is not None:
            try:
                _mod = imp.load_module('_m2crypto', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _m2crypto = swig_import_helper()
    del swig_import_helper
else:
    import _m2crypto
```

**Comment by ojwb** [comment] 2023-10-02 23:12
Since 4.0.0, the only remaining use of `import imp` in the SWIG code is in `Examples/python/performance/harness.py` and checking `Examples/python/class` I get very different (and much simpler) import logic.

I think the problem must be on your side - it probably sounds obvious, but make sure you're actually looking at the files you just generated, check you don't have multiple SWIG installs, and also `git grep 'import imp'` or equivalent in your own code to check you're not specifying custom import logic.

**Comment by ojwb** [comment] 2023-10-10 20:01
No feedback, but we just don't generate this code any more so it seems the problem has to be elsewhere so closing.  If you can really reproduce this with SWIG git master, please provide a self-contained way to reproduce it.

**Closed by ojwb** 2023-10-10 20:01 UTC
Labels: Python

**Comment by mcepl** [comment] 2023-10-17 14:33
On Tue Oct 10, 2023 at 10:01 PM CEST, Olly Betts wrote:
> No feedback, but we just don't generate this code any more so
> it seems the problem has to be elsewhere so closing.  If you can
> really reproduce this with SWIG git master, please provide a
> self-contained way to reproduce it.

I apologize for not replying sooner, but I am too overwhelmed with my actual job. 

I can reproduce with this CI job on GitLab https://gitlab.com/mcepl/m2crypto/-/jobs/5311408853 

python3:
    image: python:3
    when: always
    script:
        - apt-get update -q -y
        - apt-get install -y swig libssl-dev python3-dev openssl python3-setuptools python3-twisted python3-pip tappy
        - python3 -mpip install --user -r dev-requirements.txt
        - python3 setup.py build
        - PYTHONPATH=$(readlink -f build/lib.*) python3 -mtap discover -v

python:3 Docker container is apparently based on
Debian/bookworm. I see in log that 36-swig4.0_4.1.0-0.2_amd64.deb
has been installed.

Any thoughts? Thank you.

Matěj

**Comment by ojwb** [comment] 2023-10-17 18:47
There's code (generated with SWIG 2.0.10) using `import imp` checked into your repo:

```
$ git grep -w imp
src/M2Crypto/m2crypto.py:        import imp
src/M2Crypto/m2crypto.py:            fp, pathname, description = imp.find_module('_m2crypto', [dirname(__file__)])
src/M2Crypto/m2crypto.py:                _mod = imp.load_module('_m2crypto', fp, pathname, description)
src/M2Crypto/six.py:    MovedAttribute("reload_module", "__builtin__", "importlib" if PY34 else "imp", "reload"),
```

It seems much more plausible that this file ends up getting used rather than that SWIG 4.1.0 manages to generate `import imp` despite not containing code to do so - I'd suggest trying deleting (or updating) `src/M2Crypto/m2crypto.py`.

**Comment by mcepl** [comment] 2023-10-17 21:06
Right, that’s it. I wanted (for keeping compatibility with CentOS 7, which I still support) to use old swig. You are correct. Sorry for bothering you, it is truly PEBKAC.

**Comment by ojwb** [comment] 2023-10-18 00:21
These things happen to all of us - glad it's resolved.
