### ISSUE TITLE
The csharp director generates unnecessary dynamic_cast which makes compiling without rtti impossible

### ISSUE THREAD

**Issue by wwizz** [swig/swig#884] opened 2017-01-27 14:51 UTC
The csharp director generates unnecessary dynamic_cast which makes compiling without rtti impossible.

I see other languages having option to compile without rtti?

**Comment by wsfulton** [comment] 2017-01-27 19:38
Closing as duplicate of #449.

**Closed by wsfulton** 2017-01-27 19:38 UTC
