### ISSUE TITLE
Deprecation warning when compiling finalize method in Java 9

### ISSUE THREAD

**Issue by sjoubert** [swig/swig#1237] opened 2018-04-20 10:13 UTC
I'm using Swig 3.0.12, I've recently updated my java installation:
```shell
$ java --version
openjdk 9.0.4
OpenJDK Runtime Environment (build 9.0.4+12-Debian-4)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-4, mixed mode)
```
and I get the following output when compiling the Java code generated by Swig:
```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```
```
...
/some/java/class/generated/by/swig/MyClass.java:44: warning: [deprecation] finalize() in Object has been deprecated
  protected void finalize() {
                 ^
...
Note: Some input files additionally use or override a deprecated API.
100 warnings
```

Manually adding `@SuppressWarnings("deprecation")` to all the `finalize` methods seems to work. Unfortunately this is not a solution as this is code generated by swig.

I don't know what's the best approach for swig here (generate the suppression annotation or find a replacement for `finalize`) as I'm not a Java expert.

In the mean time, does one see a workaround that could allow me to silence these warnings without having to manually patch the generated code each time I call swig?

**Comment by vadz** [comment] 2018-04-20 18:32
AFAICS, the replacement of `finalize()` is supposed to be [PhantomReference](https://docs.oracle.com/javase/7/docs/api/java/lang/ref/PhantomReference.html), available since always (1.2) or [java.lang.ref.Cleaner](https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html), but the latter is 9+ only and so probably can't be used yet.

I'm not sure if using `PhantomReference` really provides any advantages in SWIG case (i.e. if the usual pitfalls of `finalize()` matter here), and while it seems like we could use it by deriving all SWIG-generated objects from it, it would require some work, so for now suppressing the deprecation warning looks like the simplest, and not obviously worst, thing to do.

**Comment by wsfulton** [comment] 2018-04-24 06:41
It would be good to discuss in more detail what the proper fix is too. A file with some jdk9 only typemaps providing the Cleaner implementation would be a good start.

**Comment by ojwb** [comment] 2018-04-24 21:49
I looked into this a few months ago as a client was hitting issues with SWIG-wrapped C++ objects not getting released in a timely fashion from Java, which could be reproduced with a simple loop such as:

```
        for (int x = 1; x < count; x++) {                                                                                                                                                     
            Foo foo = new Foo();                                                                                                                                                    
        }                                                                                                                                                                                     
```

The text below summarises where I got to, but they decided to just restart the process more often rather than pursue this further so I don't know if `Cleaner` and/or `PhantomReference` actually works better.  I've been meaning to raise this for discussion but lately new stuff seems to hit my todo pile as fast as I can process things.

Further investigation led me to conclude this is a pure Java issue with the code SWIG currently generates - the following simple Java program seems to have fairly pathological memory usage behaviour:

```
class Circle {
  private transient long p;
  protected transient boolean f;

  protected void finalize() throws Throwable {
    delete();
    super.finalize();
  }

  public synchronized void delete() {
    if (p != 0) {
      if (f) {
        f = false;
      }
      p = 0;
    }
  }

  public Circle(int r) {
    p = r;
    f = (p == 0);
  }
}

public class runme {
  public static void main(String argv[]) 
  {
    int count = 10000000;
    if (argv.length > 0) {
      count = Integer.parseInt(argv[0]);
    }

    for (int x = 1; x < count; x++) {
      Circle c = new Circle(x);
      if (x % 10000 == 0) System.gc();
    }

    System.out.println("Done");
  }
}
```

Compiled like so:

```
$ javac runme.java
Note: runme.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Then run like so:

```
$ /usr/bin/time java runme 1000000
Done
11.02user 0.18system 0:05.68elapsed 197%CPU (0avgtext+0avgdata 157012maxresident)k
0inputs+64outputs (0major+11044minor)pagefaults 0swaps
$ /usr/bin/time java runme 2000000
Done
46.27user 0.18system 0:23.56elapsed 197%CPU (0avgtext+0avgdata 266124maxresident)k
0inputs+64outputs (0major+11337minor)pagefaults 0swaps
$ /usr/bin/time java runme 3000000
Done
102.16user 0.39system 0:51.09elapsed 200%CPU (0avgtext+0avgdata 365660maxresident)k
0inputs+96outputs (0major+12082minor)pagefaults 0swaps
$ /usr/bin/time java runme 4000000
Done
181.71user 0.48system 1:28.50elapsed 205%CPU (0avgtext+0avgdata 466684maxresident)k
0inputs+128outputs (0major+12243minor)pagefaults 0swaps
```

So increasing the number of iterations 1x,2x,3x,4x results in the "maxresident" increasing by around 100000k each time and the runtime increasing super-linearly.

It seems from the documentation `System.gc()` is just a hint, and the JVM is free to ignore it, but it's clearly doing something as the program is much faster with it commented out (4000000 takes 1.75 seconds elapsed rather than over 3 minutes).  Also, without that call, the run time appears to increase linearly (as you'd expect to happen).

It looks to me like the finaliser is somehow a factor.  If I comment out the finaliser (and restore the `System.gc()` call) then 4000000 takes 1.99 seconds elapsed, with nicely bounded memory usage and
apparently linear scaling as the number is increased.

I get a deprecation warning when compiling (which I think is due to the finaliser as they seem to be deprecated in a recent JDK version) and as far as I can make out the modern Java replacement is to register objects with `java.lang.ref.Cleaner`:

https://docs.oracle.com/javase/9/docs/api/java/lang/ref/Cleaner.html

It looks like `Cleaner` was added in JDK 9, but the lower level features it uses have been available since 1.2.

**Comment by wsfulton** [comment] 2018-06-08 06:52
Indeed there is no guarantee that finalization will occur. In practise finalization is done in a the finalizer thread which is a low priority thread and so if the CPUs are busy (eg running other Java code), it won't get a chance to run. If you put a small sleep into that loop, you'll most likely find that the low priority finalizer thread will have more time to run and hence clean up native memory. This problem is particularly prevalent on older (single core) machines. Memory management and Java performance tuning with native code is a black art and not for the feint-hearted.

**Comment by wsfulton** [comment] 2018-06-08 07:04
For anyone looking for a challenge, I'd really like to see some proposed alternative solutions using PhantomReference.

**Closed** 2019-02-21 21:55 UTC
Labels: Java, enhancement
