### ISSUE TITLE
Syntax Error Occuring

### ISSUE THREAD

**Issue by arghyatiger** [swig/swig#1214] opened 2018-03-22 13:31 UTC
I'm trying to build an interface for a c++ library using SWIG for python. Can someone explain the issue ?

![screen shot 2018-03-22 at 6 58 58 pm](https://user-images.githubusercontent.com/22373140/37773306-4120cf18-2e03-11e8-90f7-18266e3c1dc2.png)

![screen shot 2018-03-22 at 6 59 09 pm](https://user-images.githubusercontent.com/22373140/37773317-47764032-2e03-11e8-8620-d70ba810c8f6.png)

![screen shot 2018-03-22 at 6 59 39 pm](https://user-images.githubusercontent.com/22373140/37773326-4c34e7b8-2e03-11e8-92bf-04327c61f687.png)

![screen shot 2018-03-22 at 6 59 18 pm](https://user-images.githubusercontent.com/22373140/37773328-4fc51e20-2e03-11e8-9654-69624c4359e1.png)

**Comment by arghyatiger** [comment] 2018-03-22 13:31
Would this be anything to do with the wstring type ?

**Comment by arghyatiger** [comment] 2018-03-22 13:35
@ismail  @vmiklos @klickverbot @djmitche @kkaempf  could anyone provide some insight on why this might be happening?

**Comment by vmiklos** [comment] 2018-03-22 21:14
Sorry, no idea. Probably good to not mass-ping unrelated people. ;-)

**Comment by ojwb** [comment] 2018-03-22 21:57
Not sure why you think this should work - `L` isn't a valid string prefix in Python:

https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

Not a bug, so closing.

And very uncool to ping a list of people.  You're abusing volunteers.

**Closed by ojwb** 2018-03-22 21:57 UTC
