### ISSUE TITLE
Unitialized variables from python.cxx::functionWrapper

### ISSUE THREAD

**Issue by gtroxler** [swig/swig#255] opened 2014-10-28 14:59 UTC
The functionWrapper creates code with uninitialized variables such as:

```
try {
  if (upcall) {
    Swig::DirectorPureVirtualException::raise("test::ClassA::initialize");
  } else { 
    result = (test::ErrorStatus)(arg1)->initialize();
  }
} catch (Swig::DirectorException&) {
  SWIG_fail;
}
resultobj = SWIG_From_int(static_cast< int >(result));// HERE THE result IS NOT INITIALIZED
```

Generally speaking it is not an issue and the result can also not be initialized since the default value is unknown. But if G++ checks strictly for uninitialized variables this leads to compilation failures. I think the line 

```
resultobj = SWIG_From_int(static_cast< int >(result));
```

should be moved inside the else{} below the:

```
result = (test::ErrorStatus)(arg1)->initialize();
```

I think the code corresponds to lines arround 2718 in python.cxx

**Comment by ojwb** [comment] 2016-09-09 03:33
Looking at the generated code by current git master, `Swig::DirectorPureVirtualException::raise("test::ClassA::initialize");` results in `throw DirectorPureVirtualException("test::ClassA::initialize");` and `SWIG_fail` is a macro which expands to `goto fail`.

So the only code path which can reach the line which uses `result` will have initialised it.  So AFAICS this only leads to compilation failures if the compiler is too dumb to see that the function call can't return **and** you compile with `-Werror`.

Generating wrappers which compile without warnings is nicer, so I guess this is worth keeping open, but I'm not sure how easy it would be to fix.  Perhaps marking `Swig::DirectorPureVirtualException::raise()` with the `noreturn` attribute when compiling with GCC is the simplest solution.

**Comment by IanS4t1qbit** [comment] 2017-06-09 18:24
We have encountered this bug, or one like it.  SWIG 3.0.11.

Use case:
- Pure virtual function returning a basic type in a director-enabled class

Example:
**ExampleClass.h**
class ExampleClass {
    virtual size_t GetValue() = 0;
}

**ExampleClass.i**
%feature("director") ExampleClass;

**interfacePYTHON_wrap.cxx**
...
size_t result;  // **<-- result is not initialized**
...
director = SWIG_DIRECTOR_CAST(arg1);
upcall = (director && (director->swig_get_self()==obj0));
if (upcall) {
    Swig::DirectorPureVirtualException::raise("ExampleClass::GetValue");
} else {
     result = (size_t)((ExampleClass const *)arg1)->GetValue();
}
...
resultobj = SWIG_From_size_t(static_cast< size_t >(result));
return resultobj;

**Error: variable 'result' is used uninitialized whenever 'if' condition is true**

**Comment by ojwb** [comment] 2017-06-09 22:47
As I said above, the compiler warning is a false positive (there's no code path which leads to use `result` without it first being initialised), so there isn't a bug here as such.

A patch to generate wrappers that compile without such warnings would certainly be welcome though.

**Comment by ojwb** [comment] 2022-01-24 21:49
It looks like this has been fixed since.  Testing with what seems a suitable example from the testsuite:

```
make -C Examples/test-suite/python PY3=1 director_basic.cpptest
```

The generated code now initialises `result`:

```
SWIGINTERN PyObject *_wrap_ConstPtrClass_getConstPtr(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  ConstPtrClass *arg1 = (ConstPtrClass *) 0 ;
  void *argp1 = 0 ;           
  int res1 = 0 ;
  PyObject *swig_obj[1] ;
  Swig::Director *director = 0;
  bool upcall = false;    
  int *result = 0 ;
                                          
  if (!args) SWIG_fail;
  swig_obj[0] = args;
  res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_ConstPtrClass, 0 |  0 );
  if (!SWIG_IsOK(res1)) {
    SWIG_exception_fail(SWIG_ArgError(res1), "in method '" "ConstPtrClass_getConstPtr" "', argument " "1"" of type '" "ConstPtrClass *""'");
  }
  arg1 = reinterpret_cast< ConstPtrClass * >(argp1);
  director = SWIG_DIRECTOR_CAST(arg1);
  upcall = (director && (director->swig_get_self()==swig_obj[0]));
  try {
    if (upcall) {
      Swig::DirectorPureVirtualException::raise("ConstPtrClass::getConstPtr");
    } else {
      result = (int *)(arg1)->getConstPtr();
    }
  } catch (Swig::DirectorException&) {
    SWIG_fail;
  } 
  resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(result), SWIGTYPE_p_int, 0 |  0 );
  if (director) {
    SWIG_AcquirePtr(resultobj, director->swig_release_ownership(SWIG_as_voidptr(result)));
  }
  return resultobj;
fail:
  return NULL;
} 
```

I couldn't trivially determine what version the fix was in.

It's hard to fully confirm this as the initial report lacks a complete reproducer, and the more recent example is invalid (no closing `;` on the class definition in the header) and incomplete (the interface file doesn't actually enable directors, nor include the header).  I'm going to close this based on my own testing, but if you can still reproduce then please reopen with a complete self-contained reproducer.

**Closed by ojwb** 2022-01-24 21:49 UTC
Labels: Python
