### ISSUE TITLE
octave 4.2 support

### ISSUE THREAD

**Issue by opoplawski** [swig/swig#847] opened 2016-12-07 20:29 UTC
I'm seeing swig code fail with octave 4.2 with:
```
/builddir/build/BUILD/mathgl-2.3.4/i686-redhat-linux-gnu_serial/lang/mathglOCTAVE_wrap.cxx: In function 'void SWIG_InstallBinaryOps(int, int)':
/builddir/build/BUILD/mathgl-2.3.4/i686-redhat-linux-gnu_serial/lang/mathglOCTAVE_wrap.cxx:2099:46: error: 'op_lshift' is not a member of 'octave_value'
 if (!octave_value_typeinfo::lookup_binary_op(octave_value::op_##name,tid1,tid2)) \
                                              ^
/builddir/build/BUILD/mathgl-2.3.4/i686-redhat-linux-gnu_serial/lang/mathglOCTAVE_wrap.cxx:2099:46: error: 'op_rshift' is not a member of 'octave_value'
 if (!octave_value_typeinfo::lookup_binary_op(octave_value::op_##name,tid1,tid2)) \
                                              ^
/builddir/build/BUILD/mathgl-2.3.4/i686-redhat-linux-gnu_serial/lang/mathglOCTAVE_wrap.cxx: In function 'octave_value_list Fmathgl(const octave_value_list&, int)':
/builddir/build/BUILD/mathgl-2.3.4/i686-redhat-linux-gnu_serial/lang/mathglOCTAVE_wrap.cxx:138571:27: error: 'octave_call_stack' has not been declared
     octave_function *me = octave_call_stack::current();
                           ^~~~~~~~~~~~~~~~~
```

**Comment by ojwb** [comment] 2016-12-07 23:01
Looks like there's support for at least Octave 4.0 from #460, which was a patch from you.  Are you able to provide a patch for this too?

**Comment by opoplawski** [comment] 2016-12-08 22:03
Not at the moment.  I'm not an octave developer (I just package it for Fedora) and I don't understand the API changes.  I've made a request on the octave developers list for help, but no response so far.

**Comment by kwwette** [comment] 2016-12-16 14:37
I regularly use the SWIG Octave module and have helped maintain it in the past, so unless else jumps in first I can look at this. It will probably make me a week or two to get round to this though. I'll have to also backport Octave 4.2 for the Travis builds.

**Comment by kwwette** [comment] 2017-01-03 03:00
I've nearly got Octave 4.2 support ready to go, but there's one aspect I need some help with.

It looks like in 4.2 Octave has switched to throwing C++ exceptions to indicate "Octave errors" - previously it used an error state variable, and did not throw an exception. This means that the Octave verision of `SWIG_Error()` now issues C++ exceptions. I'm guessing that this will affect how SWIG handles Octave errors in general - in particular it currently breaks the `exception_order` test. I'm not sure of the correct way to handle this.

@wsfulton, or anyone else, any ideas?

**Comment by wsfulton** [comment] 2017-01-03 07:13
I guess you need to generate code that is compliant with any new Octave recommendations for handling errors. Presumably this means adding in try catch blocks to catch the appropriate Octave exception. Seems like quite a fundamental non-backwards compatible change to Octave and so I suggest you check for the Octave version in the testcase to modify how the test is expected to work. I don't quite follow how the test would break, but presumably the exception order is different and you can rewrite it to test the new ordering behaviour.

**Comment by besser82** [comment] 2017-01-14 19:03
Should be fixed in https://github.com/swig/swig/pull/875.  I backported these changes to SWIG on Fedora Rawhide.

**Comment by kwwette** [comment] 2017-01-22 01:46
Octave 4.2 support has now been merged into SWIG. Please confirm that this issue is now fixed.

**Comment by kwwette** [comment] 2017-01-26 00:06
@opoplawski - are you able to confirm that this issue is now fixed for you?

**Comment by besser82** [comment] 2017-01-26 08:33
@kwwette I can confirm your changes fixed the issue; rebuilt some heavy-duty Octave-wrappers with it and it works.

**Comment by kwwette** [comment] 2017-01-26 11:56
@besser82 - thanks for the feedback, I think we can therefore close this issue.

@wsfulton - please feel free to go ahead with a new SWIG release with Octave 4.2 support.

**Closed by kwwette** 2017-01-26 11:56 UTC
Labels: Octave

**Comment by wsfulton** [comment] 2017-01-26 22:40
I'm planning to release swig-3.0.12 tomorrow.
