### ISSUE TITLE
Valid preprocessor expression marked w/ Warning 202 Syntax error

### ISSUE THREAD

**Issue by burlen** [swig/swig#2481] opened 2023-01-10 18:43 UTC
SWIG 4.1.1 incorrectly warns about a syntax error in the following preprocessor block:
```C++
#if defined(_WIN32)
#define SENSEI_IMPORT __declspec(dllimport)
#define SENSEI_EXPORT __declspec(dllexport)
#define SENSEI_HIDDEN
#elif __GNUC__ >= 4
#define SENSEI_IMPORT __attribute__((visibility("default")))
#define SENSEI_EXPORT __attribute__((visibility("default")))
#define SENSEI_HIDDEN __attribute__((visibility("hidden")))
#else
#define SENSEI_IMPORT
#define SENSEI_EXPORT
#define SENSEI_HIDDEN
#endif
```

SWIG reports:
```
/Users/bloring/sensei/build/senseiConfig.h:13: Warning 202: Could not evaluate expression '__GNUC__ >= 4'
/Users/bloring/sensei/build/senseiConfig.h:13: Warning 202: Syntax error
```

I've tried changing the syntax to `#elif defined(__GNUC__) && (__GNUC__ >= 4)` yet the warning persists. Both of those are valid CPP expressions so I think SWIG should not flag these as warning or error.

note: this issue does not occur with SWIG 4.0.2

**Comment by burlen** [comment] 2023-01-10 18:47
maybe related to #1465

**Comment by ojwb** [comment] 2023-01-10 22:01
I can't seem to trigger this warning based on the information provided.  Can you provide a complete self-contained reproducer?

**Comment by ojwb** [comment] 2023-01-10 22:06
And there's definitely code to handle undefined macros in expressions:

```
      } else if (token == SWIG_TOKEN_ID) {
        /* Defined macros have been expanded already so this is an unknown
         * macro, which gets treated as zero.
         */
        stack[sp].value = 0;
        stack[sp].svalue = 0;
        stack[sp].op = EXPR_VALUE;
```

**Comment by ojwb** [comment] 2023-01-23 21:48
```
$ cat x.h
#define SENSEI_VERSION "1.2.3"
#define SENSEI_VERSION_MAJOR 1
#define SENSEI_VERSION_MINOR 2
#define SENSEI_VERSION_PATCH 3

#if defined(_WIN32)
#define SENSEI_IMPORT __declspec(dllimport)
#define SENSEI_EXPORT __declspec(dllexport)
#define SENSEI_HIDDEN
#elif __GNUC__ >= 4
#define SENSEI_IMPORT __attribute__((visibility("default")))
#define SENSEI_EXPORT __attribute__((visibility("default")))
#define SENSEI_HIDDEN __attribute__((visibility("hidden")))
#else
#define SENSEI_IMPORT
#define SENSEI_EXPORT
#define SENSEI_HIDDEN
#endif
$ swig -python -module x x.h
$ swig -c++ -python -module x x.h
$ swig -Wall -Wextra -python -module x x.h
$ swig -Wall -Wextra -c++ -python -module x x.h
$
```

The code is meant to handle this case and (as demonstrated in the session above) it does for me.  No further details from the submitter so closing as not reproducible.

**Closed by ojwb** 2023-01-23 21:48 UTC

**Comment by karosc** [comment] 2024-02-16 12:54
Wow, I'm having this same problem in my project. I'm stuck at 4.0.2 unless I resort to adding the following to my  c-code:

```C
#ifndef SWIG
#include "export_header.h"
#else
#define EXPORT_MACRO
#endif
```

**Comment by wsfulton** [comment] 2024-02-16 19:35
What's the exact definition of `EXPORT_MACRO` in your case @karosc? Can you try master where the issue here first raised has been fixed and will go into swig-4.2.1 due to be released in about a week.

**Comment by ojwb** [comment] 2024-02-16 20:10
I think it's probably the whole contents of `export_header.h` we need to see rather than just the definition of `EXPORT_MACRO` since this is apparently the same problem which would mean it's with evaluating a preprocessor expression.

**Comment by ojwb** [comment] 2024-02-16 20:27
I had an idea that this could be due to Unicode whitespace, and I can easily **visually** reproduce the original reported error:

```
$ cat try.h
#if __GNUC__ >= 5
#elif __GNUC__ >= 4
#else
#endif
$ gcc -Wall -W -c -x c try.h
$ swig -python -module x try.h
try.h:2: Warning 202: Could not evaluate expression '__GNUC__ >= 4'
try.h:2: Warning 202: Syntax error: expected operator
```

Here the whitespace after `__GNUC__` is actually U+00A0 (non-breaking space).  GCC will complain if it tries to evaluate the expression, but it seems not in this case.  However clang does warn even without `-W` options:

```
$ clang -c -x c try.h
try.h:2:15: warning: treating Unicode character as whitespace [-Wunicode-whitespace]
#elif __GNUC__ >= 4
              ^
1 warning generated.
```

Also the reported source and error message have only ASCII spaces (though perhaps that could be misreported - we do get reports where the source or output clearly hasn't just been cut and pasted).

I'd suggest inspecting the source carefully for invisible Unicode oddities though.  E.g. for my "reproducer":

```
$ cat -vet try.h
#if __GNUC__ >= 5$
#elif __GNUC__M-BM- >= 4$
#else$
#endif$
```

So I don't know if this is the explanation, but maybe SWIG should warn about it anyway as it could occur in SWIG-specific preprocessor checks and it's quite confusing.

BTW GCC does catch this if it actually evaluates the condition (and it's an error):

```
try.h:2:15: error: token " " is not valid in preprocessor expressions
    2 | #elif __GNUC__ >= 4
      |               ^
```

**Comment by karosc** [comment] 2024-02-17 01:26
I simplified my nomenclature a bit to make a point, but I can provide some more info now. First off. the project I am working on is python c-extension. The repo in which swig is built is the python package, and the c-code is in there as a git submodule; so the links below may bring you to either repo, but both are present in the build environment.

I tried building the latest swig from source and using that to compile my project. I did this in a github workflow, so you can take a look at [the project](https://github.com/karosc/swmm-python/tree/dev_swig) and the [build results](https://github.com/karosc/swmm-python/actions/runs/7937550781/job/21674943446). The latest swig from the master branch (4.2.1) still has [the same problem](https://github.com/karosc/swmm-python/actions/runs/7937550781/job/21674943446#step:6:513), complaining about a syntax error [where I first use the export macro](https://github.com/pyswmm/Stormwater-Management-Model/blob/459db1d4dfc61ff994ae01f92eae64e378e08915/src/outfile/include/swmm_output.h#L32). You can find in past workflow runs that [using swig4.0.2 succeeds](https://github.com/karosc/swmm-python/actions/runs/7937358146/job/21674393567#step:5:82). The macro is defined in a header [generated by cmake](https://github.com/pyswmm/Stormwater-Management-Model/blob/459db1d4dfc61ff994ae01f92eae64e378e08915/src/outfile/CMakeLists.txt#L33-L39).

```C
generate_export_header(swmm-output
    BASE_NAME swmm_output
    EXPORT_MACRO_NAME EXPORT_OUT_API
    EXPORT_FILE_NAME swmm_output_export.h
    STATIC_DEFINE SHARED_EXPORTS_BUILT_AS_STATIC
)
``` 

Consequently, the file is not in the repo, but the contents are as follows:

```C

#ifndef EXPORT_OUT_API_H
#define EXPORT_OUT_API_H

#ifdef SHARED_EXPORTS_BUILT_AS_STATIC
#  define EXPORT_OUT_API
#  define SWMM_OUTPUT_NO_EXPORT
#else
#  ifndef EXPORT_OUT_API
#    ifdef swmm_output_EXPORTS
        /* We are building this library */
#      define EXPORT_OUT_API __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define EXPORT_OUT_API __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef SWMM_OUTPUT_NO_EXPORT
#    define SWMM_OUTPUT_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef SWMM_OUTPUT_DEPRECATED
#  define SWMM_OUTPUT_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef SWMM_OUTPUT_DEPRECATED_EXPORT
#  define SWMM_OUTPUT_DEPRECATED_EXPORT EXPORT_OUT_API SWMM_OUTPUT_DEPRECATED
#endif

#ifndef SWMM_OUTPUT_DEPRECATED_NO_EXPORT
#  define SWMM_OUTPUT_DEPRECATED_NO_EXPORT SWMM_OUTPUT_NO_EXPORT SWMM_OUTPUT_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SWMM_OUTPUT_NO_DEPRECATED
#    define SWMM_OUTPUT_NO_DEPRECATED
#  endif
#endif

#endif /* EXPORT_OUT_API_H */

```

The usage of the macro is in [output_header.h](https://github.com/pyswmm/Stormwater-Management-Model/blob/459db1d4dfc61ff994ae01f92eae64e378e08915/src/outfile/include/swmm_output.h), with an exerpt below:

```C
#ifndef SWMM_OUTPUT_H_
#define SWMM_OUTPUT_H_



#define MAXFILENAME 259    // Max characters in file path
#define MAXELENAME 31      // Max characters in element name

// This is an opaque pointer to struct. Do not access variables.
typedef struct Handle *SMO_Handle;


#include "swmm_output_enums.h"
#include "swmm_output_export.h"

#ifdef __cplusplus
extern "C" {
#endif


int EXPORT_OUT_API SMO_init(SMO_Handle *p_handle);
int EXPORT_OUT_API SMO_close(SMO_Handle p_handle);
int EXPORT_OUT_API SMO_open(SMO_Handle p_handle, const char *path);
```

**Comment by ojwb** [comment] 2024-02-17 04:03
Yes, that's a completely different issue (and not a preprocessor syntax error).  SWIG doesn't know about `__attribute__` (it's not a standardised feature, and it's a hard enough job just trying to keep up with standard C and particularly C++ features, without trying to also support compiler-specific features).

The answer to your problem is to just ensure `EXPORT_OUT_API` is defined to an empty value for SWIG.  Typically this happens without additional effort as use of `__attribute__` in portable codebases needs to be conditional on something like `#ifdef __GNUC__` and SWIG doesn't define `__GNUC__` (clang also supports `__attribute__` but it also defines `__GNUC__`).

**Comment by ojwb** [comment] 2024-02-17 18:47
Sounds more like a cmake problem to me - the appropriate definition of `EXPORT_OUT_API` for SWIG is just an empty value.  If whatever it sets worked with 4.0.2 then feel free to open a new ticket.  Please provide a reproducer that eliminates cmake though.
