### ISSUE TITLE
swig: output parameter char ** (as a pointer to a char *)

### ISSUE THREAD

**Issue by spilorenzo** [swig/swig#1133] opened 2017-10-23 13:51 UTC
I'm having trouble with swig and char ** as pointer to a variable char * (not as a list of char *!!!). I couldn't find out a way to wrap the pointer to a char *.

I'm using swig on my virtual machine with OS ubuntu installed.

The aim is to write the result of the concatenation in the char * referenced by the pointer.

The following is my code:

File pointers.cpp:

    #include "pointers.h"
    #include <string.h>
    #include <stdlib.h>
    #include <stdio.h>

    void conc(char *str1, char *str2, char **res){
      strcpy(*res,str1);
      strcat(*res,str2);
    }

File pointers.h

    void conc(char *str1, char *str2, char **res)

File pointers.i

    %module pointers
    %{
    #define SWIG_FILE_WITH_INIT
    #include "pointers.h"
    %}

    %include "typemaps.i"
    %include "cpointer.i"
    %include "cstring.i"

    %typemap(in,numinputs=0) char** (char* tmp) %{
      $1 = &tmp;
    %}
    %typemap(argout) char** (PyObject *obj)%{
       obj = PyUnicode_FromString(*$1);
       $result = SWIG_Python_AppendOutput($result,obj);
     %}
     %typemap(freearg) char** %{
       free(*$1);
     %}
     %include "pointers.h"
     extern void conc(char *str1, char *str2, char **res);

File setup.py:

    from distutils.core import setup, Extension

    pointers_module = Extension('_pointers',
                           sources=['pointers_wrap.cxx', 'pointers.cpp'],
                           )

    setup (name = 'pointers',
       version = '0.1',
       author      = "SWIG Docs",
       description = """Simple swig example from docs""",
       ext_modules = [pointers_module],
       py_modules = ["pointers"],
       )

Finally, the python main:

    import pointers
    result = pointers.conc("Hello ","World!");
    print(result)

And all of them are compiled with terminal commands:

    swig -c++ -python pointers.i
    python setup.py build_ext --inplace 

But I got an `Segmentation Fault (core dumped)` when the code compute `strcpy(*res,str1)`.
So when *res is used.

Can anyone help me? Thks.

**Comment by ojwb** [comment] 2018-03-11 20:52
This function seems an awkward API to wrap (or indeed to use from C/C++) - `res` needs to point to existing storage of size at least `strlen(str1) + strlen(str2) + 1`, so you'll need to allocate a temporary buffer (e.g with `malloc()`), then call `conc()`, then convert the value now in the buffer to a Python string, and then deallocate the buffer.

There's no way SWIG can know how big a buffer it would need to allocate, so this can't be handled automatically.  So this is not a bug in SWIG so I'm going to close this issue.

BTW, usage questions are really better directed to the mailing list - far more people read that than read incoming bug reports.

**Closed by ojwb** 2018-03-11 20:52 UTC
